### ISSUE TITLE
Field Manual only has two pages

### ISSUE THREAD

**Issue by maroontin** [oitsjustjose/Geolosys#100]
## Versions:

- Minecraft Forge: 14.23.2.2654
- Geolosys: 1.8.10c
- JourneyMap (optional): 5.5.2
- ImmersiveEngineering (optional): 0.12-80

## What happens:
The Field Manual only has two pages. THe cover page and a second empty one.

## What should happen:
The manual should have all the pages.

## Additional Comments:
I also have quite the few other mods installed and will provide a list as needed

**Comment by oitsjustjose** [comment]
Works fine for me, has something tampered with your Geolosys book translation, like a resource pack?

**Comment by maroontin** [comment]
I've got Faithful for Mods installed. When I deinstall it the pages are gone still

**Comment by oitsjustjose** [comment]
I still haven't been able to replicate this. Try downloading the next release when it comes out and see if it causes any problems still. Closing until then, because I'm genuinely clueless.

**Comment by oitsjustjose** [comment]
Oh! It's the language setting!! I'll have a fix in 1.9.1 :)
