### ISSUE TITLE
[request] have ore deposit blocks be recognisable as ore blocks by astral sorcery

### ISSUE THREAD

**Issue by majijn** [oitsjustjose/Geolosys#101]
## Versions:

- Minecraft Forge:14.23.3.2673
- Geolosys: 1.8.10c

## What should happen:   I asked around the AS discord and this is what the pick is looking for when using its right click functionality 
![image](https://user-images.githubusercontent.com/18368034/39224168-2188d4b8-4846-11e8-8a64-772cf1746cd5.png)
if they did it would actually give me a reason to bother making an infused pickaxe!

## Additional Comments:
is the issue template something I should also follow for requests? I just went with it given im unsure right now.

**Comment by oitsjustjose** [comment]
I'll look into it!
