### ISSUE TITLE
1.12 config is all stuffed up

### ISSUE THREAD

**Issue by Zygus42** [oitsjustjose/Geolosys#102]
## Versions:

- Minecraft Forge:forge-1.12.2-14.23.3.2673-installer-win
- Geolosys:Geolosys-1.12.2-1.8.10c
- JourneyMap (optional):journeymap-1.12.2-5.6.0b2

## What happens:
The geolosys_ores.json config file looked fine on first inspection, but when i went to make changes, I noticed that all of the size+chance+blacklist sections were one out of phase with the rest of the sections.  I deleted the file and respawned it again and same result.

## Logs (if necessary):
[geolosys_ores.zip](https://github.com/oitsjustjose/Geolosys/files/1945483/geolosys_ores.zip)

**Comment by oitsjustjose** [comment]
I mean, I don’t know what you expected to happen?!? You can’t just delete part of a config file and expect it to just be ok with missing values. If you don’t want a feature, then 0 out all the values.

**Comment by oitsjustjose** [comment]
(Totally misunderstood the bug report originally)

So, I don't see the problem with the attached JSON file - care to clarify??

**Comment by Zygus42** [comment]
Maybe I misunderstood the config ?  Is each section meant to look like this:
  "coalSize": 64,
  "coalChance": 8,
  "coalDimBlacklist": [
    -1,
    1
  ],
  "coalMinY": 8,
  "coalMaxY": 78,

In that order ?  If so, maybe I misread it.  I was seeing it as:
  "coalMinY": 8,
  "coalMaxY": 78,
  "cinnabarSize": 40,
  "cinnabarChance": 6,
  "cinnabarDimBlacklist": [
    -1,
    1
  ],
and thinking that the coal and the cinnabar were mixed up.  Looking at it again, I think I was just mistaken.  Probably the hayfever I've been having :(  messes with your ability to think logically.
