### ISSUE TITLE
1.12 Field Manual not correcting from config

### ISSUE THREAD

**Issue by Zygus42** [oitsjustjose/Geolosys#103]
## Versions:
- Minecraft Forge:forge-1.12.2-14.23.3.2673-installer-win
- Geolosys:Geolosys-1.12.2-1.8.10c
- JourneyMap (optional):journeymap-1.12.2-5.6.0b2

## What happens:
Default config for coal is
  "coalMinY": 8,
  "coalMaxY": 78,

but the field manual shows the coal page as
![2018-04-26_14 23 48](https://user-images.githubusercontent.com/20757445/39289189-a662c01e-495d-11e8-853f-ad043b4362c8.png)

## What should happen:
The field manual should adjust those figures based on the config values.

**Comment by oitsjustjose** [comment]
This is just how the manual works. That’s why it starts by saying “this is assuming default config a”.

Coming up with a dynamic book would be quite a lot, so I don’t expect it happening.

**Comment by Zygus42** [comment]
Ok, I get that that might be difficult, but what I was pointing out was that those are the default settings in your config, and they don't match the default numbers in your book.......

**Comment by oitsjustjose** [comment]
Oh! Yeah, I’ve already updated that text. It’ll be in the next release :)
