### ISSUE TITLE
Values set in the Config GUI are reset when the game reloads.

### ISSUE THREAD

**Issue by The-Fireplace** [oitsjustjose/Geolosys#106]
## Versions:

- Minecraft Forge: 14.23.3.2678
- Geolosys: 1.8.10c
- JourneyMap (optional):
- ImmersiveEngineering (optional):

## What happens:
Reloading the game causes the values set in the config gui to be reset

## What should happen:
The config values are saved between sessions.

## Additional Comments:
Without looking at the code, if I had to guess, I'd say you aren't saving the config values to the file when the config gui closes. If this is the case and you want help/examples, PM me on Discord.

**Comment by The-Fireplace** [comment]
Before reloading the game:
![image](https://user-images.githubusercontent.com/5914284/39669391-1d57056e-50b0-11e8-83f4-b33cba54c882.png)
After returning to the main menu, exiting the game, and loading it again:
![image](https://user-images.githubusercontent.com/5914284/39669402-753451a6-50b0-11e8-8e41-4d2303b236df.png)

**Comment by oitsjustjose** [comment]
Already fixed this a few commits ago.
