### ISSUE TITLE
OresAllEasy Compatibility

### ISSUE THREAD

**Issue by AlexRover** [oitsjustjose/Geolosys#108]
Hello, there was a great fashion for ores and other things, for convenience and simplicity OresAllEasy, but your mod is fine in your field, I adore the TFC and now I'm only playing with your creativity, and I have a question, could you work on compatibility with OresAllEasy

**Comment by AlexRover** [comment]
Over the past year, the minecraft has simply been transformed by mods, it's your creation, and dynamic trees, and chisels and bits, and a lot more, I play and can not stop, Immersive provides wonderful machines, addons add steam and trains, , could I have dreamed of such a couple of years ago, no, before if they did something more than one block, it was still crap, and here it is, all of you, and you are also working on the new look of the minecraft, and I would like that this work would be compatible with others, of course you It's probably easier to add ore yourself, but in that fashion, not only the ores, it has alloys and dust and ingots, in general, everything that can be, but there is no such fine way of ore generation. Try if not unite, then at least make a worthy compatibility

**Comment by oitsjustjose** [comment]
I'll look into what mechanics might make sense to merge between OresAllEasy and Geolosys - and if OresAllEasy even has an API I can tap into :)

**Comment by oitsjustjose** [comment]
So I haven't seen any other interest in this feature and the API didn't seem to straight-forward, so I'm closing this for now. Should more interest arise, I'll gladly re-open it and address it!
