### ISSUE TITLE
Config Parser not accepting negative numbers correctly

### ISSUE THREAD

**Issue by brisingraerowing** [oitsjustjose/Geolosys#110]
## Versions:

- Minecraft Forge: 2691
- Geolosys: 1.9.1
- JourneyMap (optional): -
- ImmersiveEngineering (optional): -

## What happens:
Geolosys reports that a custom ore generation is invalid with this line:
            `"ebwizardry:crystal_ore:0", 96, 12, 32, 20, "ebwizardry:crystal_ore:0", [1, -1]`

## What should happen:
The ore is generated

## Logs (if necessary):
Will add if requested

**Comment by oitsjustjose** [comment]
Don't use quotes :)

` ebwizardry:crystal_ore:0, 96, 12, 32, 20, ebwizardry:crystal_ore:0, [1, -1]`

**Comment by brisingraerowing** [comment]
Now it looks like this:
`ebwizardry:crystal_ore:0, 96, 12, 32, 20, ebwizardry:crystal_ore:0, [1, -1]`
but is still invalid.

**Comment by oitsjustjose** [comment]
Huh.. This could be my fault - I had to change the parser around some to include the dimensional blacklist. What mod is "ebwizardry"? I'd like to try this myself.

**Comment by brisingraerowing** [comment]
[Electroblob's Wizardry](https://minecraft.curseforge.com/projects/electroblobs-wizardry)

**Comment by oitsjustjose** [comment]
Checked it, your entry is fine - I renamed the title according to what the issue actually is. I've already fixed it.

**Comment by brisingraerowing** [comment]
Good to hear! This is a cool mod.
