### ISSUE TITLE
[Suggestion] Better variants of coal burn progressively longer?

### ISSUE THREAD

**Issue by darthvader45** [oitsjustjose/Geolosys#112]
As of the latest version on CurseForge, all non-vanilla variants of coal burn for 2400 ticks.  I'd like to suggest a tiered system for the coal variants that makes the deeper variants (i.e. bituminous and anthracite) more valuable.

Vanilla Coal: 1600 (i.e. smelts 8 items, leave at default)
Peat: 2400 (same)
Lignite: 3200 (smelts 16 items, one stack smelts 16 stacks)
Bituminous: 4000 (smelts 20 items, a stack would smelt 20 stacks)
Anthracite: 4800 (smelts a whopping 24 items, just a stack would smelt 1536 items or 24 stacks)

Given their rarity in comparison to vanilla coal even with Fortune III (I am actually using a Fortune III Unbreaking III pick I randomly got from enchanting my diamond pickaxe with the 30 level enchant.  No joke.), it would still technically be balanced out rather well.

**Comment by oitsjustjose** [comment]
...they do have very similar tiering already - have you tested them to confirm? I know JEI had a bug with them at one point.

**Comment by darthvader45** [comment]
JEI still has a bug with em, afaik.  Gotta bug em to fix it, heh.  Pun intended.  Also, seems they currently only have a fix for duplicate fuel entries for items with multiple oredict names.  And yes, after testing, you are indeed correct, they have almost the exact tiering I was looking for.  Great job with that.  Seems bituminous could be cut from 24 to 20, and 32 to 24.  Anthracite may be a bit OP.
