### ISSUE TITLE
Ecology Compatibility

### ISSUE THREAD

**Issue by darthvader45** [oitsjustjose/Geolosys#113]
I would love to see if this mod could work with Ecology, primarily with the coal variants.  As in, they could release progressively less pollution, with anthracite being the best as it is practically almost free of the pollutants that bituminous/soft coal is known for.

https://minecraft.curseforge.com/projects/ecology-mod

**Comment by oitsjustjose** [comment]
Since there hasn't been specific demand from others for this integration and the API isn't particularly easy to tap into, I'm closing this for now. It's open for discussion should a lot more people also request this integration.
