### ISSUE TITLE
quick question regarding the blocked vanilla ore spawns

### ISSUE THREAD

**Issue by majijn** [oitsjustjose/Geolosys#118]
is the way for me to get vanilla ores along with geolosys ores by set the settings  on the json file to chance 0; then adding the ores and their samples in the custom ore entries? or is there an easier way to do it?

**Comment by oitsjustjose** [comment]
If you want them, you'll have to create your own custom geolosys entries again - there's no option to *not* disable Vanilla spawning if you choose to enable one of the ores.

**Comment by majijn** [comment]
okay! but that will make them spawn again alongside your ores right? I didnt want to put the work into it before knowing if it'll work as I was hoping it would haha.

**Comment by oitsjustjose** [comment]
Correct, it will :)

**Comment by majijn** [comment]
I just wondered, will doing this break the IE compat with the miner?

It hasnt come up yet for me because im not that deep in IE yet, so I havent tested it.

**Comment by oitsjustjose** [comment]
Break it how? The IE compat should work if you have it enabled, but the chances for IE ores are based on the chances in the Geolosys ores config file.

So if you've set them all to 0, then yes, it'll be broken. But you can disable the compat.

**Comment by majijn** [comment]
yes I set them to 0 on the json, I should have foreseen that would mess things up! thanks for confirming it!
