### ISSUE TITLE
BetterWithMods Compatibility

### ISSUE THREAD

**Issue by owetre18** [oitsjustjose/Geolosys#119]
## What happens:
Ore clusters smelt to ingots.

## What should happen:
Ore clusters, according to how BWM works, should smelt to nuggets, not ingots.

## Additional Comments:
I know this can be done with CraftTweaker, but native support would be amazing.

Also, I'm loving your mod! Nice touch of realism to our beloved blocky game.

**Comment by oitsjustjose** [comment]
Sure, easy to do and I'll work on it shortly.

**Comment by owetre18** [comment]
Thanks so much! This will greatly help with the pack I'm working on.
