### ISSUE TITLE
GravelOres Compatibility

### ISSUE THREAD

**Issue by owetre18** [oitsjustjose/Geolosys#120]
## What happens:
Gravel ores are replaced by your ores when you approach them in the world.

## What should happen:
They should stay gravel ores, or perhaps turn into your own (renamed) version of Gravel Ores.

**Comment by oitsjustjose** [comment]
Another easy implementation, I'll look into it in the next week :)

**Comment by owetre18** [comment]
Thanks again! Again, this will help with the pack I'm working on. :)
