### ISSUE TITLE
[SUGGESTION] Guide/Wiki Page for adding custom ores?

### ISSUE THREAD

**Issue by Habeeb-M** [oitsjustjose/Geolosys#123]
Right now I can't find a guide for making custom ores, which I know is possible.

**Comment by oitsjustjose** [comment]
It's an entire chunk of comments in the config...


        # Format is:
        # modid:block:meta, deposit size, min Y, max Y, chance to gen in chunk, block to use as sample, [dimension blacklist] Example:
        # actuallyadditions:block_misc:3, 32, 13, 42, 20, actuallyadditions:block_misc:1, [1, -1]
        S:"Custom Ore Entries" <
         >

So you would use `actuallyadditions:block_misc:3, 32, 13, 42, 20, actuallyadditions:block_misc:1, [1, -1]` if you wanted to add Black Quartz to custom generation.

**Comment by Habeeb-M** [comment]
I see. I didn't see that when I checked the configs earlier, but now I see it. Is deposit size the amount of blocks in the vein? Is it exact? Is the chance a percentage or is it one in every x chunks?

**Comment by oitsjustjose** [comment]
It’s randomized approximate quantity. The chance is percentage. Higher chance = more likely.

**Comment by Habeeb-M** [comment]
Thanks!

**Comment by Habeeb-M** [comment]
What is the percentage out of? Is it the percentage that chunk will have a vein?

**Comment by oitsjustjose** [comment]
Out of a hundred, but there are other factors into the actual occurrence of it generating.
