### ISSUE TITLE
Crash with newest version

### ISSUE THREAD

**Issue by owetre18** [oitsjustjose/Geolosys#124]
## Versions:

- Minecraft Forge: 1.12.2-14.23.3.2698
- Geolosys: 1.9.3

## What happens:
Game crashes loading the mod, before title screen

## What should happen:
Game should start

## Logs (if necessary):
Crash report: https://pastebin.com/sC2Bdbi2

## Additional Comments:
Game crashed twice like this.

**Comment by oitsjustjose** [comment]
Right you are - sorry! My gradle build needed to be cleaned as it was using an old cached file that needed to be removed. Fixed this, re-releasing on CurseForge now

**Comment by owetre18** [comment]
Thank you!
