### ISSUE TITLE
NetherEx Quartz changing to Assorted Quartz in the nether when approached

### ISSUE THREAD

**Issue by renadi** [oitsjustjose/Geolosys#128]
## Versions:

- Minecraft Forge:   14.23.3.2702
- Geolosys:   1.12.2-1.9.3

## What happens:
When in the nether NetherEx Ores(gloomy/lively/fiery/icey quartz ore, a quartz which uses the same background as gloomy/lively netherrack and netherrack quartz which is essentially vanilla nether quartz) convert to assorted quartz in the nether.  other mods might be as well, it's hard to tell as they seem to change before I can get close enough to see the item name.  Vanilla quartz seems unchanged.

## What should happen:
nothing, I think, for the most part the netherex ores should remain as they are unless they're disabled.

**Comment by oitsjustjose** [comment]
This is a result of `Retroactively replace existing ores in world` = true

If you don’t want ores to be exchanged for Geolosys ones, set this to false.

**Comment by renadi** [comment]
Is there a way to specify this by dimension or modid?
I would prefer it do it in the overworked but not the nether.

**Comment by oitsjustjose** [comment]
Alright, I'll probably add a block blacklist for the ore converter, so that if you don't want a specific block to be converted you can say so.

That'll probably come out in the 1.9.4 release - I've gotta write it first.
