### ISSUE TITLE
[Request] Conquest Reforged Compatibility

### ISSUE THREAD

**Issue by SirChamomile** [oitsjustjose/Geolosys#129]
I get that this is a big ask. If you don't feel up to it, just delete this comment. Not asking for texture compatibility, our community can take care of that. Maybe this is something I could do with tweaks and configs, but it would be nice to have out of the box?

**Comment by oitsjustjose** [comment]
I've been looking into it but I have no idea how I'd manage this, honestly. I've barely got the time for new features, must less something quite this big. 

Sorry. If you get the tweaks and configs working, I'd be glad to promote them!
