### ISSUE TITLE
[Crash] Crash

### ISSUE THREAD

**Issue by JWTHDYTWA** [oitsjustjose/Geolosys#130]
## Versions:
- Minecraft Forge: 2705
- Geolosys: 1.9.2, 1.9.3
- JourneyMap (optional): 5.5.2
- ImmersiveEngineering (optional): 82

## What happens:
Game crashes on loading when Geolosys is on version 1.9.2+ (1.9.1 works fine)

## Logs (if necessary):
Crashlog: [:package:](https://gist.github.com/Warrock3280/f949fe444005342f451520d12876974c)

**Comment by oitsjustjose** [comment]
Can you attach your `geolosys.cfg` file? That'd be super helpful for debugging.

**Comment by JWTHDYTWA** [comment]
[Here is both geolosys.cfg and geolosys_ores.json](https://gist.github.com/Warrock3280/ca76e79f25d9d1f53851757faf875c10)

**Comment by oitsjustjose** [comment]
Part of it might be that you aren't including the dimensional blacklist at all.... I'm going to look into it.
