### ISSUE TITLE
Version 1.9.4 Crashes Game

### ISSUE THREAD

**Issue by avatarofmadness42** [oitsjustjose/Geolosys#132]
Versions:
- Minecraft Forge: 1.12.2-forge1.12.2-14.2302537
- Geolosys: 1.12.2-1.9.4
- JourneyMap (optional): 1.12.2-5.5.2
- ImmersiveEngineering (optional): 0.12-74
(Other mods can be included if required)
 What happens:
During the Forge loading screen, when the loader reaches the 2nd loading stage, the game crashes to desktop. The launcher also closes.
What should happen:
The game should boot up normally, and allow me to play the game.
Logs (if necessary):
Logs would be included if I could get them. I had one chance to get the log, but passed it by in an attempt to try again. I have not had the chance since, after about 5-7 further attempts at loading the game.

**Comment by Bullorg74** [comment]
I also crash on loading with 1.9.4 reverted back to 1.9.3 and it works as before.

Forge 14,23,4,2707

Log attached

[crash-2018-06-15_12.48.51-client.txt](https://github.com/oitsjustjose/Geolosys/files/2105782/crash-2018-06-15_12.48.51-client.txt)

**Comment by oitsjustjose** [comment]
Thanks guys. I know exactly what the problem is - it's stupid Gradle (The build system required by forge). I renamed a folder / package from `Client` to `client` and now Gradle assumes they're the same thing.

They're clearly not.

Hotfix coming soon. Thanks.
