### ISSUE TITLE
Corsampler finds osmium with osmium turned off.

### ISSUE THREAD

**Issue by Bullorg74** [oitsjustjose/Geolosys#134]
## Versions:

- Minecraft Forge:14.23.4.2707
- Geolosys:1.9.4
- JourneyMap (optional):1.12.2-5.5.2
- ImmersiveEngineering (optional):0.12-82

## What happens:
I'm getting reports from people that they are getting osmium with the corsampler and that has been turned off in both geolosys configs and in immersive and has been off for several versions of my pack. And nobody found any in the previous versions.

## What should happen:
No osmium should be found.

## Additional Comments:
Not tested my self but streaming people have found it with the versions stated above.

**Comment by oitsjustjose** [comment]
Pretty sure this has been reported before and it’s not me, but I’ll confirm!

**Comment by Bullorg74** [comment]
Yeah when its 2 mods working together its always hard to know were to report. But I'll appriciate it if you confirm.

**Comment by Bullorg74** [comment]
I did some moree looking and the "osmium" I find with the core sampler. If I run a excavator I get Platinum. And platinum cant be found in the world at all as its own sample. Not even the /ie material list command lists platinum but it will list osmium. So I guess a conflict somewere due to the fact that osmium and platinum are "connected" . Just some more info I know its a closed thread.
