### ISSUE TITLE
Crash when hovering over (disabled?) Geolosys ingot in Engineer's Manual

### ISSUE THREAD

**Issue by copygirl** [oitsjustjose/Geolosys#135]
## Versions:
- **Minecraft Forge:** 14.23.4.2705
- **Geolosys:** 1.9.4
- **ImmersiveEngineering:** 1.1.9

## What happens:
When looking at the *Engineer's Manual*, it displays disabled *Geolosys* ingots as one of the possible ingredients. Hovering over them immediately crashed the game.

![Screenshot](https://user-images.githubusercontent.com/272586/41711037-6a39581c-7547-11e8-9271-062eddb8f1c0.png)

## What should happen:
Ideally, the ingots shouldn't even appear in the manual in the first place.

## Logs:
**Crash log:** https://paste.ee/p/5D6SC

## Additional comments:
Ingots don't appear in *JEI*. Have they perhaps been added to the ore dictionary even though they were not registered? Maybe it's actually *Immersive Engineering*'s fault.

**Comment by oitsjustjose** [comment]
Hmmmm. Do you have another mod that does oreDictionary unification by chance?

Otherwise, it's definitely 100% IE's fault, but I have no idea how.... I don't even initialize the item unless the config is enabled. If it's enabled in the config, then it's initialized. And the oreDictionary registration is done in the constructor of the Ingot object, so it's literally impossible for it to be added unless it was initialized - OR, unless you didn't *always* have them disabled and IE does some weird persistent caching.

**Comment by copygirl** [comment]
I had UniDict in the pack before, and did have them enabled as well, but I strongly believe I completely cleaned my instance afterwards and I can't find any place where this could be cached.

**Comment by oitsjustjose** [comment]
This has just become super mysterious. I'm gonna look into it.

**Comment by oitsjustjose** [comment]
So in my dev environment (which has an admittedly slightly-outdated IE install) this doesn't occur; I started *with* Geolosys ingots, saw them in the engineer's manual, and then removed them. Once removed, they no longer appear in engineer's manual.

I'm curious what other mod is breaking things here... but it might not be that. I'm updating my IE install now to see if it's a *newly implemented* bug.

EDIT: Wait, no i'm not, I forgot that my dev environment is set to get the latest version when I setup in Gradle, so I actually am up-to-date.

**Comment by copygirl** [comment]
I just found a possible cause for the bug: The server and client don't have the same config. So on the server, the ingots were disabled, and on the client, they weren't. Not sure if this is something you want to "fix" or not so I'll leave the issue open.

**Comment by oitsjustjose** [comment]
Closing because I don't know that I'm going to struggle with config-syncing. That's a headache that I'm not interested in pursuing, honestly.
