### ISSUE TITLE
How to identify surface clusters without WAILA or similar?

### ISSUE THREAD

**Issue by copygirl** [oitsjustjose/Geolosys#136]
I personally prefer playing the game without these mods, or at least try to. Without them, it seems pretty difficult to identify the cluster stones, especially in early game without the *Prospector's Pick*. The ingame book doesn't come with pictures of the clusters to identify them by color and breaking the stones drops a generic version of it. Both *Hematite* and *Limonite* ore turn into *Iron Clusters*.

**Comment by oitsjustjose** [comment]
Fair - are you suggesting that I try my hand at making a custom book UI that isn't just re-skinned vanilla?

I can't think of any other way really, that wouldn't inevitably be redundant with TOP / WAILA / HWYLA.

**Comment by copygirl** [comment]
Pictures could benefit the book in general as well, both in polish and usability. I did also get slightly bothered by the page numbers in the table of contents not lining up. ^^

Haven't other mods adopted Botania-style books before? I bet there's an open implementation out there you could clone.

**Comment by oitsjustjose** [comment]
I was actually looking at using something similar to what mangoose uses in Rustic / Adventurer's Workshop. They're great books that have awesome formatting.

**Comment by oitsjustjose** [comment]
I've been working on a new Guide GUI all day yesterday that solves this :)
