### ISSUE TITLE
Can't remove smelting recipes using CraftTweaker

### ISSUE THREAD

**Issue by copygirl** [oitsjustjose/Geolosys#137]
## Versions:
- **Minecraft Forge:** 14.23.4.2705
- **Geolosys:** 1.9.4
- **CraftTweaker:** 4.1.8

## What happens:
I have the following lines in my `.zs` script:
```
# Iron
furnace.remove(<minecraft:iron_ingot>);
furnace.remove(<minecraft:iron_ingot> * 2);
furnace.remove(<minecraft:iron_ingot>, <geolosys:cluster:0>);
# Gold
furnace.remove(<minecraft:gold_ingot>);
furnace.remove(<minecraft:gold_ingot> * 2);
furnace.remove(<minecraft:gold_ingot>, <geolosys:cluster:1>);
# Lead
furnace.remove(<immersiveengineering:metal:2>);
furnace.remove(<thermalfoundation:material:131>);
furnace.remove(<thermalfoundation:material:131> * 2);
furnace.remove(<thermalfoundation:material:131>, <geolosys:cluster:5>);
# Silver
furnace.remove(<immersiveengineering:metal:3>);
furnace.remove(<thermalfoundation:material:130>);
furnace.remove(<thermalfoundation:material:130> * 2);
furnace.remove(<thermalfoundation:material:130>, <geolosys:cluster:4>);
[...]
```
It appears that neither the `remove(output)` nor the more specific `remove(output, input)` lines are able to get rid of the smelting recipes that *Geolosys* adds.

Could this be becausethey are added dynamically? Would there be a way to remove or disable the recipes? I would like to disable furnace smelting for all except for low-level metals such as tin and copper.

**Comment by oitsjustjose** [comment]
There's a config for removing smelting entirely y'know :)

Again, I don't know what this is about. The CoFH mods do some stupid shit with smelting; for example, even with smelting disabled via the Geolosys config, they can still be smelted in a Redstone Furnace.

Sorry - I'm 99.96% sure this isn't me. I don't add smelting dynamically, I add it just like Vanilla does with a simple `try/catch` (if ingots are disabled) for smelting if there's no corresponding oreDict ingot already registered.

Closing for now - but lemme know if it's something I'm doing wrong. Forge modding is always changing :|

**Comment by copygirl** [comment]
Derp.
