### ISSUE TITLE
Nuclearcraft Compatibility

### ISSUE THREAD

**Issue by erindal** [oitsjustjose/Geolosys#138]
Nuclearcraft has 3 materials that are not obtained from ores:

https://ftb.gamepedia.com/Beryllium  (Drops when coal ore is mined)
https://ftb.gamepedia.com/Rhodochrosite (Drops when redstone ore is mined)
https://ftb.gamepedia.com/Fluorite (Drops when lapis ore is mined)

And they're unobtainable without generating vanilla ore or using silk touch.

Additionally, the uranium/yellorium ore drops both types of chunks, even if there's no mods that use yellorium. I didn't notice anything related to changing this in the config (and this probably deserves it's own issue).

**Comment by oitsjustjose** [comment]
I can do that, this is pretty easy!

> Additionally, the uranium/yellorium ore drops both types of chunks, even if there's no mods that use yellorium. I didn't notice anything related to changing this in the config (and this probably deserves it's own issue).

<img width="202" alt="screen shot 2018-06-26 at 8 11 40 am" src="https://user-images.githubusercontent.com/3887324/41910760-a30433d6-7918-11e8-90e3-59443cd650ba.png">

...

**Comment by erindal** [comment]
![image](https://user-images.githubusercontent.com/12499779/41930876-61356e02-794a-11e8-98b3-2a1a44fc10a0.png)

I'm very dumb, thank you.
