### ISSUE TITLE
Game freezes instead of opening the Field Manual

### ISSUE THREAD

**Issue by ZapikCZ** [oitsjustjose/Geolosys#139]
## Versions:

- Minecraft Forge: forge-14.23.4.2713
- Geolosys: Geolosys-1.12.2-1.9.4

## What happens:
The game freezes without a crash when attempting to open the Field Manual book.

## Additional Comments:
Pastebin of the modlist: https://pastebin.com/vGbnukTM

**Comment by oitsjustjose** [comment]
I've rewritten the manual for the next version of Geolosys, so I don't think there should be an issue with it in the future.

This often happens because of the language setting not having a translation - out of curiosity, what language are you set to?

**Comment by ZapikCZ** [comment]
Thank you very much.

Default English actually.
