### ISSUE TITLE
Doesn't generate in Andesite

### ISSUE THREAD

**Issue by copygirl** [oitsjustjose/Geolosys#141]
Default settings for `Blocks mineral deposits can replace` seem to use the wrong block metadata:
```
        S:"Blocks mineral deposits can replace" <
            minecraft:stone:0
            minecraft:stone:1
            minecraft:stone:2
            minecraft:stone:3
            minecraft:dirt:0
            minecraft:netherrack:0
        >
```

**`minecraft:stone:0`** - **Stone**
**`minecraft:stone:1`** - **Granite**
**`minecraft:stone:2`** - ~~Polished Granite~~
**`minecraft:stone:3`** - **Diorite**
`minecraft:stone:4` - ~~Polished Diorite~~
`minecraft:stone:5` - **Andesite**
`minecraft:stone:6` - ~~Polished Andesite~~

**Comment by oitsjustjose** [comment]
Yup, noticed this today when testing for an Underground Biomes Construct compat I made

**Comment by Dulciphi** [comment]
You made an underground biomes construct compat?!

**Comment by oitsjustjose** [comment]
Started, but had to give up.

**Comment by Dulciphi** [comment]
Very sad to hear that, although, I suspect there might be a workaround together with Ore Stone Variants. I'm still checking out your latest work. Thank you
