### ISSUE TITLE
geolosys_ores.json config layout seems to be the same as before

### ISSUE THREAD

**Issue by majijn** [oitsjustjose/Geolosys#142]
## Versions:

- Minecraft Forge:14.23.4.27.32
- Geolosys:2.0

## What happens:
it looks exactly the same as before to me when I renamed the old one and had a new one generate.
though it says it's supposed to have a new layout on the changelog

**Comment by oitsjustjose** [comment]
Yours doesn't look something like this?

<img width="567" alt="screen shot 2018-07-13 at 3 13 34 pm" src="https://user-images.githubusercontent.com/3887324/42709697-572584b6-86af-11e8-828f-9321533197ae.png">

This is mine, after I JUST updated from Geolosys 1.9.5 to 2.0.0 on my singleplayer pack.

**Comment by majijn** [comment]
![geo2 0](https://user-images.githubusercontent.com/18368034/42710970-827f790a-86e6-11e8-8264-1bc9f8d6cbfe.png)
mine generates as this
![geopre2 0](https://user-images.githubusercontent.com/18368034/42711186-40bb303a-86e7-11e8-9454-f195ffb81caa.png)
and here's the old one

**Comment by oitsjustjose** [comment]
It shouldn't do this.... but like I said in the changelog, you should definitely just backup and delete your old one to let a new one generate.

**Comment by majijn** [comment]
that's what I did,changing the name made it generate a new one ,

I guess I'll redownload the mod see if that fixes it

**Comment by majijn** [comment]
redownloading seems to have fixed that! 
sorry for bothering you

I have no clue why it did that though.
