### ISSUE TITLE
Prospecting Pick keeps chunk borders when broken

### ISSUE THREAD

**Issue by Reisai** [oitsjustjose/Geolosys#144]
## Versions:

- Minecraft Forge: 14.23.4.2707
- Geolosys: 1.12.2-2.0.0

## What happens: 
When the prospecting pick breaks, the chunk border display stays

## What should happen: 
The chunk borders should disappear when the prospecting pick breaks

## Additional Comments:
You can't see how much durability is remaining, in numbers, through the F3+H extra information tooltips

**Comment by oitsjustjose** [comment]
I'll add the F3+H thing - it's because the durability is stored via NBT.

As for the chunk borders - I'm going to remove them entirely. It takes away from the immersion of the game seeing these big borders.

**Comment by oitsjustjose** [comment]
[9bd1de2](https://github.com/oitsjustjose/Geolosys/commit/9bd1de266b757c61623a0f9b66909e85ab4db012) closes this :)
