### ISSUE TITLE
possible Geolosys_ores.json bug?

### ISSUE THREAD

**Issue by Trinsdar** [oitsjustjose/Geolosys#145]
## Versions:
- Minecraft Forge: 14.23.4.2739
- Geolosys: 2.0.0
- JourneyMap (optional):
- ImmersiveEngineering (optional):

## What happens:
Every time I launch the game the geolosys_ores.json has all it numbers within set to zero.

## What should happen:
It should stay the way it's been edited

## Logs (if necessary):
Latest: https://paste.dimdev.org/akafopecic.md

I'm not sure if you need the debug log as it probably doesn't have any more info.

## Additional Comments:
I'm not sure if this is a bug or just an error I made in the config.

**Comment by oitsjustjose** [comment]
No, it shouldn't stay the way it's been edited. If you've messed up the formatting or deleted lines entirely, it puts them back with default values of 0 (or empty lists in the case of blacklists).

This is working as intended.

**Comment by Trinsdar** [comment]
I must have accidently deleted a line or something then. good to know it's just an error on my part.
