### ISSUE TITLE
Geolosys refuses to recognize contenttweaker samples.

### ISSUE THREAD

**Issue by Trinsdar** [oitsjustjose/Geolosys#146]
## Versions:

- Minecraft Forge:14.23.4.2739
- Geolosys: 2.0.0
- Contenttweaker 4.6.0
- JourneyMap (optional):
- ImmersiveEngineering (optional):

## What happens:
Geolosys keeps saying that the custom samples I made using contenttweaker do not exist, yet they do exist.

## What should happen:
Geolosys should recognize it as a valid block.

## Logs (if necessary):
https://paste.dimdev.org/gasimuqusi.md

## Additional Comments:
this is the exact line: https://paste.dimdev.org/cagopibuba.css

https://github.com/The-Acronym-Coders/ContentTweaker/issues/123

**Comment by oitsjustjose** [comment]
Huh... have you tried with Content Tweaker v 1.12.2-4.5.0?

I'm comparing with SevTech:Ages and it _seems_ like your entries should work - no obvious typos or anything. I know SevTech:Ages uses the same thing and that's the version of Content Tweaker it's using, so it might be a new bug.. or it might very well be on my end!

**Comment by Trinsdar** [comment]
reverting to contenttweaker 4.5.0 didn't change a thing. it still refuses to recognize the samples.

**Comment by SkySom** [comment]
Files I had them present show that the block and meta indeed exist, so I'm not sure what issues could be on my side. If you've got any ideas that I can look into let me know, but I'm also clueless on my end.

**Comment by Trinsdar** [comment]
One note is that the current released version of sevtech uses version 1.9.3 of geolosys while I'm using version 2.0.0 of geolosys

**Comment by oitsjustjose** [comment]
I've been debugging this and it's working in my dev environment with a custom block I threw together really quickly. Only thing I can think of is that ContentTweaker is coming after Geolosys so the custom blocks "don't exist" yet.

I can make Geolosys load before ContentTweaker and post a beta here if you can test :)

**Comment by oitsjustjose** [comment]
Give [this](http://www.mediafire.com/file/e5ojdm9i0kyz8v1/Geolosys-1.12.2-2.0.1_debug.jar) a try?

**Comment by Trinsdar** [comment]
didn't work and wouldn't you want it to load after contenttweaker, not before?

**Comment by oitsjustjose** [comment]
I said before, I meant after. But shoot, I hoped that’d work.

**Comment by oitsjustjose** [comment]
So....

It's working for me. Granted, I'm not using the exact same setup as you are, but with CraftTweaker, ContentTweaker and B.A.S.E. installed I added this line to my Custom Ore Entries config:

`contenttweaker:sub_block_holder_0:2, 32, 13, 42, 20, contenttweaker:sub_block_holder_0:6, [1]`

I know this isn't *exactly* what you did, but the issue was with the sample and yet it worked for me:

![image](https://user-images.githubusercontent.com/3887324/43075796-dc41b122-8e4f-11e8-874b-f3927d1244bc.png)

**Comment by Trinsdar** [comment]
Looks like I'll have to add mods till I find the mod causing this.

**Comment by Trinsdar** [comment]
I may have narrowed it down to orespawn, basemetals, and silent's gems.

**Comment by Trinsdar** [comment]
well it's not orespawn

**Comment by Trinsdar** [comment]
that leaves silent's gems, base metals, or silent's lib.

**Comment by Trinsdar** [comment]
upon switching to just a content tweaker block for the ore it works, but it won't work with silent's gems multigem ores.

**Comment by Trinsdar** [comment]
and it won't work with base metals mercury ore.

**Comment by Trinsdar** [comment]
@oitsjustjose so I've determined it will only work with contenttweaker ores but not other mods ores.

**Comment by oitsjustjose** [comment]
I don't know why this is the case. Is there anything showing up in the logs from Geolosys letting you know there's an error and why?

(Also test with the newest Geolosys release, I haven't changed anything regarding this but it may have been any number of other things ¯\\\_(ツ)\_/¯ )

**Comment by Trinsdar** [comment]
no the latest release doesn't fix it and this is the only thing showing up related to it. `[10:36:09] [main/ERROR] [geolosys]: Entry silentgems:multi_gem_ore_classic, 40, 5, 45, 22, contenttweaker:sub_block_holder_0:3, [1, -1] is not valid. Reason: sample block does not exist`

**Comment by oitsjustjose** [comment]
Sorry this issue has been dead for a while-

See issue #166 - it's not a direct solution but once implemented it may solve your issue by adding its own sample?

**Comment by oitsjustjose** [comment]
Closing for staleness - let me know if anything changes :)
