### ISSUE TITLE
Nether Quartz no longer generate in the nether

### ISSUE THREAD

**Issue by Fireztonez** [oitsjustjose/Geolosys#148]
## Versions: 
- Minecraft Forge: 14.23.4.2705
- Geolosys: 2.0.0
- JourneyMap (optional): 5.5.2
- ImmersiveEngineering (optional): 0.12-84

## What happens:
When I go to the nether we don't have any quartz ore Generated in the world. I can say the problem came with Geolosys, but can't find any options for allow minecraft Nether Quartz to be generate again, without have set the Geolosys Quartz ore in the nether. (I want vanilla generation or similar gen).

## What should happen:
Have option to whitelist natural oregen (Other than Geolosys)

## Logs (if necessary):
Dont tink is needed, becose I don't think this is a bug

## Additional Comments:
If you need any other information, tell me...

Fireztonez

**Comment by oitsjustjose** [comment]
No nether quartz in the nether is by design. If it bothers you, you could add it as a custom mineral deposit!
