### ISSUE TITLE
Turn off Nether Diorite Andesite and Granite generation

### ISSUE THREAD

**Issue by Fireztonez** [oitsjustjose/Geolosys#149]
## Versions:

- Minecraft Forge:
- Geolosys: 2.0.0
- JourneyMap (optional): 5.5.2
- ImmersiveEngineering (optional): 0.12-84

## What happens:
![diorite-andesite-granite-nether](https://user-images.githubusercontent.com/19277301/43349541-8e71c072-91ce-11e8-8e22-28a0abb05cb9.png)

I don't know if is an intended feature with Geolosys, but in the Nether, there have now Diorite, andesite and Granite veins in the Nether... Personnally I didn't really like that and I whant to disable that for my modpack, but, we can't find any options for that. So, if this is intended Feature, can you add option to turn that off? And, if this is a bug, I hope you are able to fix that soon :D.

## What should happen:
Don't have that blocks gen in the nether ;)

## Logs (if necessary):
Tel me if you need, I will give you...

Fireztonez

**Comment by oitsjustjose** [comment]
Huh, I’ll look into it soon! Just had surgery today so I’ll be a bit..

**Comment by Fireztonez** [comment]
ok, no problem!
