### ISSUE TITLE
Configurable ore drops

### ISSUE THREAD

**Issue by Boodals** [oitsjustjose/Geolosys#150]
I would like to be able to configure what is dropped by the various ore blocks.
For example, currently mining limonite has a 20% chance to drop nickle, else it drops iron. This feature is hardcoded.
I would like to be able to configure cinnabar ore to have a chance of dropping cinnabar from Thaumcraft. Additionally I would like assorted quartz ore to have a chance of dropping certus quartz from Applied Energistics.
Having two variables would be nice: one for the chance of an item dropping (relative weight), and one for the number of items dropped. Maybe have variables to allow for multiple item types dropping together.
Having this configurable as opposed to enabling via mod detection would allow compatibility with any number of mods.
Obviously the existing ore drops should be changed to use this configuration setting.

**Comment by oitsjustjose** [comment]
Sounds like it would be easier to use [this mod](https://minecraft.curseforge.com/projects/block-drops-tweaker) than for me to make even more convoluted config options.

**Comment by oitsjustjose** [comment]
PS: certus quartz and charged certus quartz already drop from assorted quartz

**Comment by Boodals** [comment]
Oh, it certainly would be easier to use that. I had no idea that existed, thanks.
I should have double checked for quartz in the code. I just tried in-game with a handful of blocks and didn't get it.
