### ISSUE TITLE
Limonite ore drops iron cluster?

### ISSUE THREAD

**Issue by LemADEC** [oitsjustjose/Geolosys#151]
## Versions:
- Minecraft Forge: 1.12.2-14.23.4.2739
- Geolosys: 1.12.2-2.0.0
- Hwyla: Hwyla-1.8.26-B41_1.12.2.jar

## What happens:
According to debug screen and Hwyla, I've a Limonite ore block.
![image](https://user-images.githubusercontent.com/4776032/43371827-da9f3d72-9399-11e8-867a-0053394d946c.png)

According to the mob drop, it's iron ore.
![image](https://user-images.githubusercontent.com/4776032/43371854-337ed416-939a-11e8-9979-a75369c3914d.png)

## What should happen:
Block type should match its drop.

## Logs (if necessary):
no specific logs in console

## Additional Comments:
This an experimental modpack using default configurations (for now).

**Comment by oitsjustjose** [comment]
I think this is fine - this is exactly how it's intended to work... 

Just read through the manual and you'd see what it's supposed to drop anyways.

**Comment by LemADEC** [comment]
My bad, I was reading as lignite instead of limonite :)
