### ISSUE TITLE
No Geolosys ores in ExU2 Quarry Dimension

### ISSUE THREAD

**Issue by Thedrummonger** [oitsjustjose/Geolosys#152]
## Versions:

- Minecraft Forge: 14.23.4.2747
- Geolosys: 1.12.2-2.0.0
- Extra Utilities: 1.12-1.8.2

## What happens:
Neither geolosys ores or vanilla are spawning in extra utilities quarry dimension.

## What should happen:
Geolosys ores should be spawning similar to other dimentions

## Logs (if necessary):
Probably not necessary but on the off chance they are,
https://pastebin.com/JmgeasrM

## Additional Comments:
Extra utilities 2 features an item called the quantum quarry. This quarry mines in a separate dimension that is inaccessible outside of commands. Using the default geolosys configs, no geolosys ores are spawning in this dimension. Geolosys is however preventing vanilla ores from spawning in this dimension rendering this block useless when geolosys is installed. Would there be any way to 
either force geolosys ores to spawn in this dimension or blacklist geolosys from preventing vanilla ores from spawning there? 

Thanks!

**Comment by oitsjustjose** [comment]
I'll be looking into both the Deep Dark & Quantum Quarry issue. *Something's* invalidating the ability to generate an ore in those circumstances, but I don't know what. If the dimension isn't blacklisted, it should be calling to check if it can generate - so I'll play around with it in dev.

**Comment by oitsjustjose** [comment]
So, I've found that the "surface block" for the Deep Dark is what's causing the problem: The ores are generating! You just won't find a sample because of the weirdness that is how that dimension generates. The prospector's pick seems very confused though, so I'll try to fix that.

**Comment by Thedrummonger** [comment]
So I've done a bit more testing and unfortunately I think this issue might be void. Through some more testing I've found that the quantum quarry actually does pull in geolosys ore but the way the quantum quarry works is really odd. By default the quarry dimension is just stone and dirt with no ores anywhere. When the quarry begins to mine it picks a chuck, regenerates it and populates it with ores. After it's done with that chunk it regenerates it and starts over. When I was doing my original testing I was just running around the quarry dimension with world stripper trying to find ore. Since the quarry's weren't running at that moment no chunks had been populated with ores meaning i wouldn't find any. It does however seems very rare that the quantum quarry will actually populate a chuck with geolosys ores. If I had to guess I would guess that's because the quantum quarry expects every chuck to have a variety of ore not large veins every few chucks like geolosys does.

Apologies for the misinformation!

**Comment by oitsjustjose** [comment]
No worries!! I knew this mechanic of the quantum quarry, and I was actually confirming myself that the single chunk it populates was populating Geolosys deposits. 

I had to leave to take family to the doctor, but I still want to investigate a few things (like I want to make sure that it can generate more than one deposit even though it’s the “same” chunk.
