### ISSUE TITLE
[2.1.0] Clusters dont have oreDict

### ISSUE THREAD

**Issue by Cassiobsk8** [oitsjustjose/Geolosys#154]
## Versions:

- Minecraft Forge: 14.23.4.2747
- Geolosys: 2.1.0
- JourneyMap (optional): 5.5.2
- ImmersiveEngineering (optional): 0.12-84

## What happens:
I do not know if it was intended, but only zinc and osmium have oreDict.
I tried using the crafttweaker to add them and use it in the crushing table but it did not work or add as a recipe.

## What should happen:
if it is a bug they should be registered as an oredict and can be used in the crushing table of the magneticraft

## Logs (if necessary):
no logs

## Additional Comments:
https://imgur.com/a/vs7trgQ

**Comment by oitsjustjose** [comment]
What other mods do you have installed? When testing with the 2.1.0 release on Curse alongside Actually Additions (as shown in your image) I can see that all clusters have their oreDict names. I wonder what other mods might be toying with the oreDict :V

**Comment by Cassiobsk8** [comment]
As soon as I read "I wonder what other mods might be toying with the oreDict" a mod came in my mind (uniDict)
Sorry I missed this sooner.
adding this in the unidict config resolves this:

S:ownerOfEveryThing <
        **geolosys**        
        minecraft
        thermalfoundation
        nuclearcraft
        mekanism
        substratum
        ic2
        immersiveengineering
        techreborn
        jaopca
     >

**Comment by oitsjustjose** [comment]
Woah that's weird! On my server and singleplayer I have UniDict and it doesn't mess with anything. I wonder if it added support recently! Anyways, glad to see it resolved :)
