### ISSUE TITLE
Crash at Initialization

### ISSUE THREAD

**Issue by DrMinecraftful** [oitsjustjose/Geolosys#155]
## Versions:
- Minecraft Forge: 14.23.4.2707
- Geolosys: 1.9.3

## What happens:
Upon initializing geolosys my client crashes. It has ran multiply times before without issue.

## What should happen:
Should initialize.

## Logs (if necessary):
https://pastebin.com/vvxTedV6

## Additional Comments:
I restarted my PC, and updated java but to no avail. The only thing that worked was updating the mod to the newest version. However, I am using the modpack sevteck and cannot use an updated version. I tried running it by itself but still got the same error. I am using the crash log from the client that only had forge and Geolosys 1.9.3 since it is the same error and a smaller log.

**Comment by oitsjustjose** [comment]
It's a Mojang problem - they screwed up lang file names on their server. I'm literally posting a hotfix on curseforge right now because I don't know _when_ Mojang's gonna fix this

**Comment by DrMinecraftful** [comment]
Okay thank you for the quick replay.
