### ISSUE TITLE
[Questions] Custom ore gen | Other mods' ore gen

### ISSUE THREAD

**Issue by Davoleo** [oitsjustjose/Geolosys#157]
I don't know if there's a better place for questions, like a discord server, but I'll put it here, I hope it's fine

## Versions:

- Minecraft Forge: 2757
- Geolosys: 2.1.1
- JourneyMap (optional): 5.5.2
- ImmersiveEngineering (optional): 0.12 - 82

## Questions/Issue Description:
Custom veins doesn't generate, is this configuration written wrong?  https://gist.github.com/Davoleo/fd1f6341d3e5fc46db34db87d42a0858

Do I need to turn off other mods' ore generation manually, or does the mod do it by itself?

## Logs (if necessary):
I'll post one if you need it, just tell me

**Comment by oitsjustjose** [comment]
You MUST include metadata for ore and sample blocks on custom entries. In your case, just add `:0` at the end of all your `modid:block` pairs.

**Comment by Davoleo** [comment]
yeah, thanks I forgot about that, even if i read the description of the config, i'm a really distract person...

and about other mods ore gen? I suppose I need to turn it off...?

**Comment by oitsjustjose** [comment]
No worries!! And yes, you'd need to go manually disable them all unfortunately.
