### ISSUE TITLE
Breaking Geolosys ores with silk touch mass mining tools give full stacks

### ISSUE THREAD

**Issue by Naxdar** [oitsjustjose/Geolosys#159]
## Versions:

- Minecraft Forge: 1.12.2-14.23.4.2705
- Geolosys: 1.12.2-2.1.2
- JourneyMap (optional): true
- ImmersiveEngineering (optional): false

## What happens:
Breaking geolosys ores using silk touch tools that break multiple blocks at once (tinkers' hammer, redstone arsenal pickaxe) make every geolosys of that type drop twice as much items as before, up to a stack of 64 for every mined ore. The bug happens when at least 3 such geolosys ores are mined at once. 
That happens when the block mined gives a regular ore and not a cluster (with a minimal amount of mods, Hematite gets the bug).
Until the game is restarted, every geolosys ore mined will give multiple ore blocks even with single block (but still with silk touch) tools.

Example : 
You start on a new world, you place multiple Hematite ores and break at least 3 at once with a silk touch hammer, now every ore is giving you 2 regular ores, next time it will be 4, then 8, 16... etc up until you get full stacks for every Hematite ore.

## What should happen:
Only one regular ore for every geolosys ore mined.

## Logs (if necessary):
Nothing in the console.

**Comment by oitsjustjose** [comment]
Huh, I wonder if this has something to do with someone registering an entire *stack* into the oreDict? I'll look into it and enforce a stack size of 1.

**Comment by Naxdar** [comment]
It doesn't happen initially and it never happens if you use a regular silk touch pickaxe, the numbers go up when a hammer is used for example.
I tested and reproduced the bug with a minimal amount of mods (Geolosys, JEI+NEI, Tinkers' construct).

**Comment by oitsjustjose** [comment]
Tested this with TiCon like you did as well, and this seems to be fixed.
