### ISSUE TITLE
Samples Generate in shallow water

### ISSUE THREAD

**Issue by Octopork** [oitsjustjose/Geolosys#16]
Samples can generate in 1 block high water, no sign of generation in deeper water.

**Comment by oitsjustjose** [comment]
They generate in any water, and I don't know how I feel about it. I think I'm okay with it (if you're ballsy enough to go digging in the ocean) but you're right, it looks weird in 1-deep water. Thoughts on which  you'd prefer?: 

a. No samples in any water
b. No samples in shallow water
c. Samples anywhere

**Comment by jena-th** [comment]
c.

Plus if you can somehow alter the sample rendering to adapt itself to the closest fluid that would be nice !

**Comment by oitsjustjose** [comment]
I can't, that's why I'm not sure about what to do. If I could get them to render that'd be cool with me. 

I'm not proficient at MC's rendering still, so yeah.

**Comment by jena-th** [comment]
Look how Botania render the Altar, the altar can contain water or lava and render it, use this code :)
Okay, they're cheating, it's a TE :)

**Comment by Octopork** [comment]
If you can get them to render/behave correctly then have them spawn anywhere. If not i would rather have no samples under water than ugly air pockets everywhere.

**Comment by oitsjustjose** [comment]
Oh yeah, all has been fixed in the latest release via config option. Thanks for the input you guys!
