### ISSUE TITLE
[Question] Prospectors config

### ISSUE THREAD

**Issue by ghost** [oitsjustjose/Geolosys#162]
Sorry to ask this here, but I cannot find a comment/discussion thread?

What is the difference between "Prospector's Pickaxe Diameter" and "Prospector's Pickaxe Range" in the config?

**Comment by oitsjustjose** [comment]
Range is how the depth of the search
Diameter is the area that it checks *in* that range. 

So if you're facing North and your `diameter=5` and `range=3`, then it'll check a 3 x 5 x 5 (L x W x H) area; 3 blocks further north, and 2 blocks out each way (up down left and right)
