### ISSUE TITLE
Ore strata [suggestion]

### ISSUE THREAD

**Issue by Waynekosimoto** [oitsjustjose/Geolosys#163]
I don't know if anyone has actually made these suggestions, but would it be possible to add realistic deposits for coal or clay. Or if it's possible to config this already could you help? I mean adding coal, clay or other stuff as strata. Layers of coal that stretch for long distances. As pictured below:

![coal](https://user-images.githubusercontent.com/12769365/47252418-30e6e580-d40a-11e8-9401-9fd4e8040f5b.jpg)

**Comment by oitsjustjose** [comment]
I like this, but that's getting into making my own world-type which I'm specifically trying to avoid; making an ore-type generator that replaces that much terrain can run into a *lot* of problems.

Closing for now, but may revisit!

**Comment by Waynekosimoto** [comment]
@oitsjustjose Understandable it was just a crazy idea of mine.
