### ISSUE TITLE
No ores generate in world with v.2.1.3

### ISSUE THREAD

**Issue by Fireztonez** [oitsjustjose/Geolosys#164]
## Versions: 
Minecraft: 1.12.2
Geolosys: v. 2.1.3
Forge: 14.23.5.2768
# I don't think this mods caused the bug, but...:
Quark (For Realistic Terrain gen): r1.5-130
JourneyMap: 5.5.2
Immersive Engineering: 0.12-86

## What happens:
I create a new world and find somes ores samples (No problem with that), I do a World Stripper question to see the Generation of stones and ores. And surprise, there have just no ores at all...

I've done this many times to make sure that it is not a bad chance and that for X reason this vein there is not to generate (Because it happened to me a few times in survival to find samples, but that finally in the chunk there were no ores). But really, none of them generates, that once, strangely I saw a small part of a vein (cut to rebunk chunk) on more than fifty World Strip...

I know for the fact my config work because I have test and play this modpack for few mounts and I never get any Ore Gen Issue. And I have reinstall the porecedent version and everithing works:

Before the upgrade:
![geolosys_ores_old](https://user-images.githubusercontent.com/19277301/47764137-45dd3780-dc9a-11e8-913d-17416fc7bd7e.png)

After the upgrade:
![no_ores_bug](https://user-images.githubusercontent.com/19277301/47762127-ae73e680-dc91-11e8-8b26-ac44fbbfc1d3.png)

## What should happen:
The ores vein should possibly generate?!? I think this is the goal of that mod after all :D.

## Logs (if necessary):
Here the log. I look into the logs and it look tike the mod think itgenerate things, but there have no ores...:
-- I know there ahve several errors into the logs I have a lot of thing to fix into the modpack, but for what I see there ahve not really any errors from geolosys...

Complete Log file: https://gist.github.com/Fireztonez/1fb4567f5b997301458c6e168db9ee20
Geolosys Generation part: https://gist.github.com/Fireztonez/6e90dcb51041907d1c6368f46352160f

Fireztonez

**Comment by ZeroKaion** [comment]
I can confirm the same thing as above but I'm using Forge 2772 and have alot more mods. Using Biomes O Plenty as worldgen.

**Comment by oitsjustjose** [comment]
>_<

I totally forgot that was a part of the if-statement I deleted

Fixed in 231994f5d1828cf5f32a772d6afb4edeef50ef2d
