### ISSUE TITLE
[Suggestion] Surface samples based on ores found beneath

### ISSUE THREAD

**Issue by ShneekeyTheLost** [oitsjustjose/Geolosys#165]
Would it be possible for surface samples spawned be based on what ores are in that chunk? So, for example, if you are wandering around and saw a coal sample, that you knew that somewhere below it there was a coal vein? It would make a lot more sense, be a lot closer to how TFC surface deposits worked, and would make the mod far more useful to include in mod packs. 

At the moment, I'm working on a hardcore pack, and I'm heavily restricting early-game access, but I want the player to be able to find certain resources without needing to branch mine or have access to iron. This would be a way for a player to understand generally what ores are in the ground in an inexact manner, enabling them to secure resources without the need to do an excessive amount of mining.

**Comment by oitsjustjose** [comment]
It already does this? Samples spawn in the same chunk that an ore deposit is located - let me know if I don't understand the issue.

**Comment by ShneekeyTheLost** [comment]
The issue is that it doesn't. Example: just generated a world, had surface coal samples, but no coal in the entire chunk underneath. In fact, there were no ores at all in that chunk after coring it out. 

Furthermore, getting samples for ores which are not present in worldgen in the first place. For example, Sphalerite samples, when there is no tin spawning in world at all.

**Comment by oitsjustjose** [comment]
What version are you using? There was a bug in 2.1.3 where no ores spawned which was fixed in 2.1.3.1

**Comment by ShneekeyTheLost** [comment]
I think I got it now. I had to delete the config files for the initial install from 2.1.3 when I updated to 2.1.3.1 before it would work properly. Thank you very much!
