### ISSUE TITLE
Thaumcraft 6 Compatibility

### ISSUE THREAD

**Issue by Scrayyg** [oitsjustjose/Geolosys#171]
## Versions:
- Minecraft Forge: 14.23.5.2772
- Geolosys: 2.1.3.1
- Thaumcraft: 2.6.1.BETA26
## What happens:
When mining the Geolosys equivalents of Coal, Redstone, Quartz, and Diamond ore, you get normal drops.

## What should happen:
Thaumcraft 6 gives the above ores a chance to drop Rare Earths which does not seem to occur with the Geolosys ones.

**Comment by oitsjustjose** [comment]
Closing because Thaumcraft is unfortunately both incomplete and once again abandoned. 😢

**Comment by oitsjustjose** [comment]
Reopening because of [this](https://www.reddit.com/r/feedthebeast/comments/akeah5/thaumcraft_will_be_maintained_yes/) :smile:
