### ISSUE TITLE
Kimberlite problem

### ISSUE THREAD

**Issue by SeaPanzer28** [oitsjustjose/Geolosys#172]
## Versions:

- Minecraft Forge:14.23.5.2768
- Geolosys:2.1.3.1
- JourneyMap :5.5.3
- ImmersiveEngineering :0.12 - 86

## What happens: 
I found some kimberlite samples and so I started digging. But also after that I dug down the whole chunk from 48 to 61 under sea level, I found no kimberlite blocks. Is it normal?

## What should happen:
Actually find kimberlite, of course

**Comment by oitsjustjose** [comment]
Was it just that one time? Ore generation is rather random, any number of things could've happened to prevent it from generating.

If it isn't generating *anywhere* you look, then there's a problem.

**Comment by SeaPanzer28** [comment]
The generation of  the other ores is correct; it happended just with that cluster (which is the only kimberlite cluster I found so I can't compare it to other veins)

**Comment by oitsjustjose** [comment]
Well, try finding others and let me know if it’s still a problem :)

**Comment by SeaPanzer28** [comment]
Sure!

**Comment by SeaPanzer28** [comment]
Just found another cluster, all was fine, thank you!
