### ISSUE TITLE
[Enhancement Request] More custom ores options

### ISSUE THREAD

**Issue by JWTHDYTWA** [oitsjustjose/Geolosys#175]
Now adding custom vein entries is limited to few args in config. I think this mechanic should be more configurable, eg ability to register an array of ores for one entry which will generate mixed ore veins. Additionally it would be great to add any kind of probes for custom veins. Because it's no other suitable blocks to be used as probes.

**Comment by oitsjustjose** [comment]
While all of that *does* sound amazing, it seems a little outside of the scope of a config file. What about a Crafttweaker plug-in instead so you can use the relatively powerful ZenScript to register ores?

I’d have to look into how, but I’m hoping it’s not awful :smile:

**Comment by thewho333** [comment]
First of, I really enjoy your mod!

I would also like more options like:
- White/blacklist biomes
- Add multiple different size clusters of the same ore:
.. - Chance of less than 1. I would like to make very sparse "mega clusters" while still having small clusters closer to the surface. (1-10 oreblocks)

**Comment by oitsjustjose** [comment]
Alright, just finished CT compatibility. I have to rewrite functionality and API stuff to get things like multi-ore deposits and biomes to be used. It'll be work but it might not be awful.

**Comment by oitsjustjose** [comment]
Alright, just finished a VERY long writeup on how this'll work. If you're interested, [take a look](https://geolosys.readthedocs.io/en/latest/CraftTweaker/)!
