### ISSUE TITLE
crash log due to forestry being in the geolosys config

### ISSUE THREAD

**Issue by trilexcom** [oitsjustjose/Geolosys#176]
hi oitsjustjose thank you for making Geolosys its a great mod

i want to integrate, all the mods we have into Geolosys ore gen

can you please tell me if this is forestry issue ? Geolosys problem? so i can report it to the right people 

Thanks 

Trilex

## here is the config file for Geolosys

https://gist.github.com/trilexcom/e2216c59681dd7bc3e7255f63f349090

## Versions: 1.12.2

- Minecraft Forge: 2779
- Geolosys: 1.12.2-2.1.3.1
- JourneyMap (optional): 1.12.2-5.5.3
- ImmersiveEngineering (optional): 0.12-87

## What happens:

crashlog

## What should happen:

load

## Logs (if necessary):

https://gist.github.com/trilexcom/44eae8f4f3fe7bcc94da447488a67cd5

**Comment by oitsjustjose** [comment]
I believe the issue is that you **must** include Block metadata, 0 is probably the one you want. 

Try that and if the issue persists I’ll investigate further.

**Comment by trilexcom** [comment]
ok sure thanks

**Comment by trilexcom** [comment]
is this correct? forestry:resources:0, 45, 75, 25, 11, forestry:apatite, [1, -1]

**Comment by oitsjustjose** [comment]
Apatite (the sample block) will need it too :smile:

**Comment by trilexcom** [comment]
thank you bro

**Comment by trilexcom** [comment]
how is that ? 

            techreborn:ore:2, 4, 13, 42, 20, techreborn:storage2:3, [1, -1]
            techreborn:ore:3, 4, 13, 25, 15, techreborn:storage2:4, [1, -1]
            biomesoplenty:gem_ore:5, 4, 13, 25, 13, biomesoplenty:gem_block:5, [1, -1]
            biomesoplenty:gem_ore:4, 4, 13, 25, 14, biomesoplenty:gem_block:4, [1, -1]
            biomesoplenty:gem_ore:3, 4, 13, 25, 12, biomesoplenty:gem_block:3, [1, -1]
            projectred-exploration:ore:6, 4, 12, 25, 11, projectred-exploration:stone:11, [1, -1]
			forestry:resources:0, 45, 75, 25, 11, forestry:resource_storage, [1, -1]
            thaumcraft:ore_amber, 8, 12, 25, 11, thaumcraft:amber_block, [1, -1]

**Comment by oitsjustjose** [comment]
Try `forestry:resources:0, 45, 75, 25, 11, forestry:resource_storage:0, [1, -1]`

**Comment by trilexcom** [comment]
trying that now thank you again

**Comment by trilexcom** [comment]
worked thank you

**Comment by trilexcom** [comment]
testing it now

**Comment by oitsjustjose** [comment]
Great! Glad it worked!
