### ISSUE TITLE
Prospector's pick in some worlds(?) or biomes(s) is always in surface mode

### ISSUE THREAD

**Issue by RiverC** [oitsjustjose/Geolosys#177]
## Versions:

- Minecraft Forge: 1.12.2  14.23.5.2810
- Geolosys: 2.1.3.1 and 2.1.4
- JourneyMap (optional): 1.12.2-5.5.3
- ImmersiveEngineering (optional): 0.12-88

## What happens:
In some worlds/biomes the prospectors pick always reports what ore is "in this area", even one when is at the bottom of the world.

Examples: In the Lost Cities world generation, in some cases in Desert and Stone Beach biomes it seems to never switch to search.

## What should happen:
When you get low enough (?) it should start searching for nearby ores, regardless of biome or what structures are above you (?)

## Additional Comments:
I'm rather confused as to how / when the pick switches from 'surface' to 'search' mode, I thought it was just depth but it seems not.

**Comment by oitsjustjose** [comment]
"Depth" is determined by the dimension's sea level. Any proposals to other methods I could look into?

**Comment by oitsjustjose** [comment]
I'd like to ask - what's the Y level of the very bottom of a lost cities world? I'm curious as to how that's preventing it from working unless McJty has done something funny

**Comment by RiverC** [comment]
it's normal. It doesn't change it.

But the Wasteland type MIGHT lower sea level as a way to prevent water from spawning pretty much anywhere.

**Comment by oitsjustjose** [comment]
Alright, b38b4a242f0ad20463a6d75a59f54f86a6f4fa47 should fix this for you.
