### ISSUE TITLE
Furnace recipes missing: a specific cause and fix

### ISSUE THREAD

**Issue by kragnoth** [oitsjustjose/Geolosys#178]
forge : 1.12.2.2796
geolosys: Geolosys-1.12.2-2.1.4.jar

Issue: If you disable worldgen completely by deleting all lines in geolosys_ores.cfg and letting it regen with all zeroes, the smelting recipes dissappear.

I am doing this, because I want the ore replacements, but not the oregen.

Temporary fix: Setting blacklists to dimensions fixes this as well.

**Comment by oitsjustjose** [comment]
This is intended but I can disable this. Thanks for the FYI
