### ISSUE TITLE
coals compat for IE

### ISSUE THREAD

**Issue by majijn** [oitsjustjose/Geolosys#180]
it'd be neat if we could make coke from the coals added by your mod, the lignite and the bituminous coal could be used in a coke oven to get coke , I guess getting a coke per each 8 items they can smelt?
I dont know if you can coke peat, but the anthracite definitely cant be coked IRL I think.

**Comment by oitsjustjose** [comment]
This is a fantastic idea - better yet I’d love to have the better coals I add be fuels for the blast furnace directly, instead of as being able to be created into coal coke. It makes more sense that way in my opinion, as far as how it works in real life.

So, the coals would have half the burning time; instead of 12, 16, 24 and 32 they'd be 6, 8, 12 and 16. Remember that it takes "8" to forge 1 steel, so that means that anthracitic coal could create two steel from a single piece.

**Comment by majijn** [comment]
anthracite makes sense for steel because its usually extremely pure carbon, however its carbon is packed too tight together it may need to be crushed somehow to be used for the blast furnace

however lignite and bituminous coal wont be pure carbon, hence the need for coking to drive out the water and creosote/tars and sulfur
peat would contain a lot of sulfur so it definitely would need to be processed someway 

currently the values in out of the box IE for steel are 4 charcoal for 1 steel(300 ticks x 4), 1 coal coke for 1 steel (1200 x1) , and a block of coal coke for 10 steel ingots, or 1 steel block

**Comment by majijn** [comment]
ah rip I took too long to load my mc instance an write this up.

edit: it REALLY makes more sense to me to have to coke the coals first, except the anthracite,
 maybe the anthracite could be added to the arc furnace and make it faster in the creation of steel, (and therefore cheaper RF/wise)?

**Comment by oitsjustjose** [comment]
Dang you put a lot more science into this than I did. I'll work on these adjustments now.

**Comment by majijn** [comment]
so my suggestion to give you the rundown is as follows, seeing how ive separated the suggestions a bit too much in each post.
have lignite and bituminous coal give one coke for each 8 items they can smelt in a furnace (and also give more creosote than vanilla coal, perhaps?)
then have anthracite as an additive to the arc furnace for 4 iron ingots or 4 iron grit to make steel, and either have it have  lower RF/t requirements, or have it a higher speed so that in the end it's a cheaper rf way of making steel with an arc furnace,

edit: this suggestion came to me because I keep running out of creosote haha, but I need to use vanilla coal for other mod's recipes too; and I couldnt keep up with manual harvesting of wood for charcoal and for treated wood.

**Comment by oitsjustjose** [comment]
So for the sake of playability I've done the following:

- Anthracite is natively usable in the Blast Furnace, smelting 2 steel with 1 anthracite
- Bituminous coal can be coked, allowing it to smelt 2 steel with 1 bituminous coal coke
- Lignite coal can be coked, allowing it to smelt 1.5 steel with 1 lignite coal coke
- Both coal cokes smelt twice as much in a normal furnace than their non-coked counterparts
- Coking either of the two new ores creates more creosote than coal

**Comment by majijn** [comment]
I was suggesting using IE's coke as an output for better compat with existing storage systems+coke blocks and thinking that adding items may be too much of a bother but that's a neat way of implementing that!

**Comment by majijn** [comment]
followup, would it be possible for this to have a separate config setting for the coals coke and the excavator compat?

edit: if not thats cool too!

**Comment by oitsjustjose** [comment]
I'll definitely consider it, that doesn't sound like a bad idea. I do need to do some configuration work for #186.

**Comment by majijn** [comment]
btw are excavator veins supposed to be all over the place randomly? i seem to recall them being supposed to being in the same spot as the in world veins, or was that me misunderstanding something? i found a limonite vein in a chunk i mined lapis from, after checking a chunk i mined hematite from and it came back as having nothing under

**Comment by oitsjustjose** [comment]
Nah they’re random because the API for IE doesn’t let me specify.
