### ISSUE TITLE
NPE When Prospecting Pick is disabled

### ISSUE THREAD

**Issue by justinrusso** [oitsjustjose/Geolosys#182]
https://github.com/oitsjustjose/Geolosys/blob/6ea8439509830b611c1fe8f08a0b98e332cc26f6/src/main/java/com/oitsjustjose/geolosys/common/config/ConfigParser.java#L57

Geolosys Version: 2.2.4

**Comment by oitsjustjose** [comment]
Mmmmmmmm oops. I’ll have a fix for it soon, Thanks!
