### ISSUE TITLE
[Crash] Switch from Creative to Survival

### ISSUE THREAD

**Issue by CREEATION** [oitsjustjose/Geolosys#183]
## Versions:
- Minecraft Forge: 14.23.5.2815
- Geolosys: 2.2.5

## What happens:
In spectator mode, I searched for the new ore underground, then I switched to creative mode. I gave myself diamond armor, a diamond pickaxe, the new tool from this mod, stone blocks, torches and the backback from [Quark Oddities](https://minecraft.curseforge.com/projects/quark-oddities). Then I switched to survival and the game immediatley crashed.

## What should happen:
Happy digging.

## Logs:
https://paste.dimdev.org/ucalecohiv.mccrash

## Additional comments:
Loaded up the world again just fine, in survival. Switching to the new tool crashes the game, though. Same error as described in the already linked logfile.

**Comment by CREEATION** [comment]
I barely took two breaths and you've already fixed it? Here, take this turtle of admiration: 🐢

**Comment by oitsjustjose** [comment]
Heh yep, I had just "fixed" this issue (turns out I hadn't) so I knew the issue as soon as I saw the log, unfortunately. And the CurseForge mods are quick this morning :smile:
