### ISSUE TITLE
Auto-melting Compatibility

### ISSUE THREAD

**Issue by Pentalf** [oitsjustjose/Geolosys#184]
Is this mod compatible with the auto-melting modifier of tools? 
I have Tinker's Construct 1.12.2
- Geolosys 1.9.3
- Minecraft Forge: 14.23.4.2707
- JourneyMap 1.12.2-5.5.2
- ImmersiveEngineering : -0.12-82

I want take iron ingots from Hematite, etc...

**Comment by oitsjustjose** [comment]
Yes, it is!

**Comment by Pentalf** [comment]
and how? its not working, a have pick with auto-melting mod, and when i trying mine hematit, i am gaining hematit, not iron ingot...

**Comment by Pentalf** [comment]
but in the same time when i mining rock, i am gaining rock, not cobblestones, so auto-melting is working with vanilla rocks...

**Comment by oitsjustjose** [comment]
Depends on two things:
1. That you've got smelting of clusters enabled (it's a config option)
2. That whatever mod is doing the auto-smelting is smelting the dropped item, _not_ the block broken; that is to say if you're breaking cobblestone, it doesn't drop the result of smelting smooth stone but the result of smelting cobblestone - the item it drops.

I've tested this before with Tinkers and it worked for me, if it doesn't anymore I'll have to test and see what's up.

**Comment by Pentalf** [comment]
so after enabling smelting of clusters and restarting game, i am gaining iron bits (1/9 iron ingot)...
Its default SevTech Ages mod pack

**Comment by oitsjustjose** [comment]
That's because BetterWithMods is enabled.

https://github.com/oitsjustjose/Geolosys/blob/9f71602a5bd0e2816ec42f3c7cc182ee53b7f8b6/src/main/java/com/oitsjustjose/geolosys/common/util/Recipes.java#L16-L29

It's not a config option, if smelting in the furnace is enabled _and_ betterwithmods is enabled then you'll get nuggets only.

**Comment by Pentalf** [comment]
and... is this problem can be solved? disable betterwithmods or...? 
PS thank you

**Comment by oitsjustjose** [comment]
I mean yeah you can disable BetterWithMods but that's the _entire basis_ of SevTech Ages. 

I don't think this is a problem that can be solved without adding a config option (unlikely as this is **default** behavior for BetterWithMods).
