### ISSUE TITLE
Thuamcraft/Projectred ores not spawning correctly. 

### ISSUE THREAD

**Issue by lorbog** [oitsjustjose/Geolosys#185]
## Versions:

- Minecraft Forge: 14.23.5.2815
- Geolosys: 2.2.6
- JourneyMap (optional):  5.5.4
- ImmersiveEngineering (optional):

## What happens:
  Ore form the project red mod that have been added to the custom ores section do not spawn during terrain generation.

## What should happen:
The projectred ores should spawn

## Logs (if necessary):
My custom ore settings

 S:"Custom Ore Entries" <
            libvulpes:ore0:0, 32, 10, 24, 5, libvulpes:ore0:0, [1, -1]
            libvulpes:ore0:8, 32, 10, 24, 5, libvulpes:ore0:8, [1, -1]
            libvulpes:ore0:10, 32, 10, 24, 5, libvulpes:ore0:10, [1, -1]
            projectred-exploration:ore:0, 20, 20, 60, 4, projectred-exploration:ore:0, [1, -1]
            projectred-exploration:ore:1, 20, 20, 60, 4, projectred-exploration:ore:1, [1, -1]
            projectred-exploration:ore:2, 20, 20, 60, 4, projectred-exploration:ore:2, [1, -1]
            projectred-exploration:ore:6, 24, 5, 12, 8, projectred-exploration:ore:6, [1, -1]
            thaumcraft:ore_amber:0, 40, 30, 60, 6, thaumcraft:ore_amber, [1, -1]
            thaumcraft:ore_cinnabar:0, 40, 30, 60, 6, thaumcraft:ore_cinnabar, [1, -1]
            nuclearcraft:ore:3, 40, 5, 30, 5, nuclearcraft:ore:3, [1, -1]
            nuclearcraft:ore:5, 40, 5, 30, 5, nuclearcraft:ore:5, [1, -1]
            nuclearcraft:ore:6, 40, 5, 30, 5, nuclearcraft:ore:6, [1, -1]
            nuclearcraft:ore:7, 40, 5, 30, 5, nuclearcraft:ore:7, [1, -1]
         >

## Additional Comments:

Maybe it due the dashes/ underscores in the names?

**Comment by oitsjustjose** [comment]
Ah, that's because the '-' in the mod-name probably gets replaced out with the regex I'm using. I'll fix this as soon as I can - sorry :\

**Comment by oitsjustjose** [comment]
This got incidentally fixed in v3.0.0 in the new JSON API and such :)
