### ISSUE TITLE
[Suggestion] Prospector's pick testing for veins

### ISSUE THREAD

**Issue by Metalit** [oitsjustjose/Geolosys#186]
By default, the prospector's pick tests for surface samples and not underground veins if you are above ground. Unfortunately, this means that if you remove all the samples and test again, it appears that there are no samples underground, even though there are. It would be nice if it was the other way by default (since it is a config option) or was somehow clarified.

**Comment by oitsjustjose** [comment]
This sounds like a good idea to explain the pros and cons within the config file :smile:
