### ISSUE TITLE
Geolosys Ores don't generate properly with Underground Biomes

### ISSUE THREAD

**Issue by mechobree** [oitsjustjose/Geolosys#187]
## Versions:

- Minecraft Forge: 14.23.5.2836
- Geolosys: 2.2.6
- Underground Biomes: 1.3.3 (Just incase it's needed)

## What happens:
When playing with both these mods together, the generation of geolosys' ores seems broken.
![javaw_04-29-15 05 00](https://user-images.githubusercontent.com/29335214/56972250-a7db0480-6b38-11e9-8ec7-1ec480ccb634.jpg)
A view of the ore generation using x-ray
![chrome_04-30-10 22 18](https://user-images.githubusercontent.com/29335214/56972283-b9241100-6b38-11e9-991d-89102c202d2a.png)
a closeup of the broken generation, it seems to be cut off abruptly 

## What should happen:
Not have large chunks of ore missing.

## Additional Comments:
I would send this to Underground Biomes issue page as well, but someone over there already listed another issue that is combined with this one, and the mod dev mentioned that the generation issue would most likely be fixed via your side, as well as the fact that there wasn't an issue about it here. 
[You can see that one here](https://github.com/Aang23/UndergroundBiomesConstructs/issues/66)

**Comment by oitsjustjose** [comment]
Thanks for letting me know about this! Since there's more info (From the UB dev) at the other thread, I'm going to reply most actively there.

**Comment by mechobree** [comment]
Alright, good luck!
