### ISSUE TITLE
Can't find download

### ISSUE THREAD

**Issue by CessnaSkyhawk** [oitsjustjose/Geolosys#189]
## Versions:

- Minecraft Forge: 1.12.2
- Geolosys: 3.0???
- JourneyMap (optional):
- ImmersiveEngineering (optional):

## What happens:
The download on CurseForge is for an older version, and therefore, when downloaded, the new crafttweaker stuff won't work, and I can't find a download anywhere else. I tried to do that fancy compilation thing, but whenever I open that gradle thing it just shows a log for a few seconds, runs some thing, and then closes

## What should happen:
The 3.0 version download should be downloadable

## Logs (if necessary):
This mapping 'snapshot_20180704' was designed for MC 1.12! Use at your own peril.This mapping 'snapshot_20180704' was designed for MC 1.12! Use at your own peril.

#################################################
         ForgeGradle 2.3-SNAPSHOT-7764e3e        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
                 Powered by MCP                  
             http://modcoderpack.com             
     by: Searge, ProfMobius, R4wk, ZeuX          
     Fesh0r, IngisKahn, bspkrs, LexManos         
#################################################
:help

Welcome to Gradle 2.7.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

BUILD SUCCESSFUL

Total time: 7.48 secs

## Additional Comments:
Sorry if this isn't formatted correctly or something - it's my first time using github :)

**Comment by oitsjustjose** [comment]
That's because I'm still working on it. There are a lot of things I'm making sure still work because internally, this is a very massive change to the code structure.

Soon I'll have a beta that I suggest you only use if you make a backup or are just testing!

**Comment by oitsjustjose** [comment]
[Here you are](https://minecraft.curseforge.com/projects/geolosys/files/2720191)

**Comment by CessnaSkyhawk** [comment]
Yay - thanks for responding so quickly! I was planning to use the new biome oregen as the base for a new modpack I'm working on, so I'll test it out sometime soon and let you know if anything seems off with it. :)
