### ISSUE TITLE
no clusters under samples

### ISSUE THREAD

**Issue by Zygus42** [oitsjustjose/Geolosys#19]
Geolosys-1.12-1.4

Been testing this version and have changed spawn figures to:

[geolosys.txt](https://github.com/oitsjustjose/Geolosys/files/1252076/geolosys.txt)

But now I'm finding lots of samples which have no clusters under them - using World Stripper mod to test.

**Comment by oitsjustjose** [comment]
This has been fixed already. Waiting for wiiv to finish the texture update before I release the 1.5 update.
