### ISSUE TITLE
Error parsing script that should be fine

### ISSUE THREAD

**Issue by notWaterGuy12** [oitsjustjose/Geolosys#194]
## Versions:

- Minecraft Forge:
forge-14.23.5.2838
- Geolosys:
Geolosys-1.12.2-2.2.6.jar
-Crafttweaker:
	CraftTweaker2-1.12-4.1.19.jar

## What happens:
Script for a multi-ore vein says that it expects a semi-colon despite the script following the system. Along with this, the ore import listed does not work, as it says that it doesn't exist

## What should happen:
Script should be making a multi-ore vein

## Script:
mods.geolosys.ores.addOre(
	[<embers:ore_quartz>, <appliedenergistics2:quartz_ore>, <bewitchment:gem_ore:0>, <bewitchment:gem_ore:1>, <bewitchment:gem_ore:2>, <bewitchment:gem_ore:3>, <bewitchment:gem_ore:4>, <bewitchment:gem_ore:5>, <bewitchment:gem_ore:6>, <bewitchment:gem_ore:7>, <bewitchment:gem_ore:8>, <thaumcraft:ore_amber>, <thaumcraft:ore_cinnabar>, <geolosys:ore_vanilla:6>, <minecraft:diamond_ore>],
	[25, 25, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3],
	[<geolosys:ore_sample_vanilla:4>],
	[100],
	6, 29, 50, 6, 1.0 as float, [-1, 1],
	[<minecraft:stone>],
);

Log is too large for pastebin

**Comment by oitsjustjose** [comment]
Two things:

1. CraftTweaker compact has not been implemented until the 3.0.x releases
2. In the 3.0.x releases I have fixed registering too early on my part thus
messing up compatibility with many mods.
