### ISSUE TITLE
Bring Back Cow Coal

### ISSUE THREAD

**Issue by The-Fireplace** [oitsjustjose/Geolosys#196]
## Versions:
- Geolosys: Non-mooing edition

## What happens:
Coal does not look like it moos at people

## What should happen:
Coal should look like it moos at people

## Logs (if necessary):
The logs of it mooing at people are in your memory @oitsjustjose , think back.

**Comment by oitsjustjose** [comment]
Closed with status meme, whose color is `696969`.
