### ISSUE TITLE
Manual missing ore entries

### ISSUE THREAD

**Issue by IronPiston** [oitsjustjose/Geolosys#197]
## Versions:

- Minecraft Forge: 14.23.5.2838
- Geolosys: 3.00.c

## What happens:
Geolosys manual has no documentation on different ores, this was in previous versions

## What should happen:
The manual should list all available ores
![2019-06-30_18 58 05](https://user-images.githubusercontent.com/11603684/60403926-0177a380-9b69-11e9-9c4d-b1f2df06b0bc.png)
(Note that the only thing under "Resources" is stone varients)

**Comment by oitsjustjose** [comment]
This has been fixed already in a not-yet-releases version. I’d release it but my main machine has been in service for the past week.

**Comment by IronPiston** [comment]
Ah ok, thanks for the quick reply
