### ISSUE TITLE
[feature request] some method to help locate minerals

### ISSUE THREAD

**Issue by Zygus42** [oitsjustjose/Geolosys#2]
Was using World Stripper to test this mod, and what I notice most of all is that while I quite like the concept of a large deposit to set up a mine etc, your actual change of finding one, especially early game when you can only mine fairly slowly, is very small.  This in turn means that people could well become disenchanted with this process - not much more discouraging than an endless tunnel with nothing in it except stone.  So I would like to see some method of locating the ore deposits - maybe a machine, or maybe some samples of ore on the surface in the way that Terrafirmacraft does it, or maybe certain plants like to grow above the spots where certain minerals are found, or something.

**Comment by oitsjustjose** [comment]
[Check out the latest release](https://minecraft.curseforge.com/projects/geolosys/files/2451125), you'll be happy I think (I know I am).

Thanks for the suggestion, it changed my mindset on how the ore generation should be designed!
