### ISSUE TITLE
Please Add Back Custom Ores [1.12.1]

### ISSUE THREAD

**Issue by Darkosto** [oitsjustjose/Geolosys#20]
Hello!

I'm one of the users that has been making use of the custom ore entries for my pack, is there a possibility of adding them back. Maybe, instead of samples you can allow the player to define a block that can be used as a sample instead that lets players create custom samples instead of you needing to make them?

Thank you very much and have a great rest of your day!
Darkosto

**Comment by oitsjustjose** [comment]
That sounds like a great idea! I'll work on it tonight!

**Comment by Darkosto** [comment]
Awesome, thank you for being so understanding!

**Comment by oitsjustjose** [comment]
Hey @Darkosto how soon do you need this update?

Work and school are starting to ramp up, but most of my free time has been spend hanging out with friends lately. If this is urgent then it'll be a good excuse to tell them to GTFO of my house and I'll sit down and focus on testing it more.

**Comment by Darkosto** [comment]
It's not too urgent, I was going to do some work on my stream today to get an alpha version of my pack out to testers since I'm heading to PAX West until next Tuesday. The current mod version should work for a while :)

Thank you!

**Comment by oitsjustjose** [comment]
Tested it more; the new system is working nicely (same as before, but now "samples" will be the block that you have added). It works in combination with the "# of samples per chunk" config  :)

Expect an update soon (I promise this one is actually waiting until @wiiv has finished _all_ the textures remaining - he's so close! \o/
