### ISSUE TITLE
Immersive Engineering/Geolosys compat seems to be semi-broken

### ISSUE THREAD

**Issue by cloakable** [oitsjustjose/Geolosys#203]
## Versions:

- Minecraft Forge: 14.23.5.2838
- Geolosys: 3.0.2b
- JourneyMap (optional): 5.5.4
- ImmersiveEngineering (optional): 0.12-89

## What happens:
Excavator integration seems to be nonfunctional.

## What should happen:
Geolosys ores should probably show up in the Engineers manual (only Silt does, which is a non-Geolosys vein).

I also assume that the Core Sample Drill should find, say, a Cinnabar vein in the same chunk as a Cinnabar sample.

**Comment by cloakable** [comment]
Addition: Just added Silt to the Geolosys config file for removal and now the Engineers Manual shows zero veins.

**Comment by oitsjustjose** [comment]
Ah yeah, this has to do with when I moved the order of reading `geolosys.json` in and making it work.

It looks like there's a bit of a race condition, where if I wait too long to read in `geolosys.json`, I can guarantee that 99% of all blocks from other mods have been created and are ready, but it's too late for me to add recipes to Immersive Engineering. So there are a few options:

1. Remove most IE Compat, leave that to users to do via CraftTweaker, and just have IE compat **only** include automatically including Geolosys as the first item in the `preferredOres` entry of IE's config
2. Revert load order to how it was, maintaining the original IE compat but breaking some integrations with Geolosys and some mod blocks. I can make the error message more detailed so I know what mods I need to load after, but this isn't optimal for me either.....
3. Request IE to allow for recipes to be added in later stages of initialization.

**Comment by oitsjustjose** [comment]
Ok, I've come to a resolution.

I'm going to continue to do everything in `init()` (such as compatibility stuff, like this IE compat). That'll make sure all of that works.

*But*, if an ore isn't properly registered from the JSON in `init()`, it will be registered in `postInit()`. This allows the ore/stone to *still* generate via Geolosys, but mod compat may be broken.

It's the best I can do I think.
