### ISSUE TITLE
"Enable Fortune on all Geolosys ores" Crash

### ISSUE THREAD

**Issue by Cellbind** [oitsjustjose/Geolosys#207]
## Versions:
- Minecraft Forge: 14.23.5.2838
- Geolosys: 3.0.3
- JourneyMap (optional): 5.5.5
- ImmersiveEngineering (optional): 0.12-89

## What happens:
Minecraft crashes when "Enable Fortune on all Geolosys ores" in the config is set to true while generating new chunks. Also crashes when loading back into the world.

## What should happen:
Minecraft should not crash while generating new chunks.

## Logs (if necessary):
Crash Report:
https://pastebin.com/f3Q071d6
Session Log(Couldn't pastebin this one):
https://puu.sh/E8eJf/2d33733ecb.log

## Additional Comments:
Reverting to a 3.0.2b, or disabling "Enable Fortune on all Geolosys ores" allows the world to load normally (tested on original world, and a recreated world that ran into an identical crash).

-------

Potentially related: Mining Platinum does not drop anything while both "Enable Osmium Exclusively", and "Enable Fortune on all Geolosys ores" are enabled, further testing is required, however.

**Comment by oitsjustjose** [comment]
Yikes, that was my bad. I don't know why I didn't think that fortune could/should be 0 in some instances. I tested the platinum exclusively thing now that I've fixed this bug, and I think that may have had something to do with that. 

I just fixed this issue in 5ea56ba1618a011c3d41b502f2ccb457cb6773b5
