### ISSUE TITLE
JSON File Not Being Downloaded

### ISSUE THREAD

**Issue by nephatrine** [oitsjustjose/Geolosys#209]
## Versions:

- Minecraft Forge: forge-1.12.2-14.23.5.2838
- Geolosys: Geolosys-1.12.2-3.0.4

## What happens:

Installed geolosys. Created world. No geolosys samples/deposits generate in the world. No ability to obtain ores. :(

## What should happen:

Geolosys deposits should generate.

## Logs (if necessary):

[05:16:54] [main/INFO] [geolosys]: Could not find geolosys.json. Downloading it from GitHub...
[05:16:54] [main/ERROR] [geolosys]: File C:\Users\nephatrine\AppData\Roaming\.MCUpdater\instances\br0wnbr1x\config\geolosys.jsoncould neither be found nor downloaded. Unable to load any ores unless they are from CraftTweaker.

## Additional Comments:

I can go download geolosys_ores.json from here, rename it, and throw it into my config directory manually... but it'd be lovely if it included a default json to fallback to in case downloading fails and/or have it made it more explicit (maybe a chat message on world load) that it has failed to save people wandering around for an hour trying to find ore.

**Comment by nephatrine** [comment]
Wow. That was super quick. Thanks.

**Comment by oitsjustjose** [comment]
No problem! I'll push up a release ASAP - I broke most links (accidentally,
and there's nothing I can do about it..) when I moved the master branch to
1.12.x 🤔
