### ISSUE TITLE
Ore Samples Not Requiring Tool

### ISSUE THREAD

**Issue by ChiefLogan3010** [oitsjustjose/Geolosys#21]
Really enjoying this mod but one issue i have encountered is being able to mine ore samples by hand, which allows a player to collect diamonds and such with no infrastructure.

**Comment by jena-th** [comment]
- In so little quantities it's ridicule.
- if you collect the sample you have no way to tell what's underground.
- How could you tell what a sample is without collecting it in the first place ?
- Seeing floating sample in the air in case of digging wouldn't be "nice".

**Comment by ChiefLogan3010** [comment]
- Diamonds in any quantity before other resources breaks balance and progression.
 - A possible solution would be the sample dropping a sample itself which contains a tooltip with what ores are in each vein. 
 - You don't need the ore/mineral itself to know what it is, a useless item with some info in a tooltip would be enough.
 - I never said anything of the sort?

**Comment by oitsjustjose** [comment]
I've been thinking on it. My solution will be a config file called "Samples are no fun" (false by default) in which - if enabled - breaking or right-clicking a sample sends the player a chat message saying "You break the sample apart and find <type> in the area".

Enough arguing, please - configs are made for this reason! Everyone has different preferences.

**Comment by ChiefLogan3010** [comment]
That would be perfect! Wasn't meaning to argue, just pointed out that this little change could be used to fix progression in some packs, configs are definitely the way to go.

**Comment by jena-th** [comment]
Sorry, I didn't want to feel like arguing, thank you @ChiefLogan3010 for bringing food for thoughts. And thank you @oitsjustjose to be open to new configs, all mod devs are not like you :)
