### ISSUE TITLE
Cant find  Samples!!

### ISSUE THREAD

**Issue by minerboy101** [oitsjustjose/Geolosys#210]
## Versions:

- Minecraft Forge:Latest
- Geolosys:Latest
- JourneyMap (optional):Latest 
- ImmersiveEngineering (optional):latest version

## What should happen:
Ive made alot of worlds and i cant find samples at all  i find bits of ore around the world but no iron or samples ive explored thousands of blocks to find nothing 

## Additional Comments:

feed back would be nice i really need this fixed

**Comment by oitsjustjose** [comment]
You're using Geolosys 3.0.5 uploaded today?

If so, send me your `geolosys.json` within the `config` folder in your Minecraft directory?

**Comment by minerboy101** [comment]
im trying the new version u made today now ill  give feeed back

**Comment by minerboy101** [comment]
New version seems to work by its self ill test it with mods.

**Comment by minerboy101** [comment]
Alright made a new world things work now thanks.
