### ISSUE TITLE
[Suggestion] Biome Dictionary Support Not Documented

### ISSUE THREAD

**Issue by nephatrine** [oitsjustjose/Geolosys#212]
Instead of hardcoding biome names in the geolosys.json, would love to be able to put in biome dictionary names instead. This would make things easier for packs with a vast number of biomes in them.

**Comment by oitsjustjose** [comment]
It's not clear in the docs (I'll get to that), but you can -  you can use keynames like `DESERT` in combination with specific biomes (i.e. `biomes: [DESERT, minecraft:plains]` is valid)

**Comment by nephatrine** [comment]
Oh thanks, that's awesome. I guess I should have just tried it first.
