### ISSUE TITLE
1.14 Geolosys crashing server

### ISSUE THREAD

**Issue by Lewdicolo** [oitsjustjose/Geolosys#214]
## Versions: 

- Minecraft Forge: 1.14.4 - 28.1.26
- Geolosys: Geolosys-1.14.4-4.0.1.jar
- JourneyMap (optional):
- ImmersiveEngineering (optional):

**Comment by oitsjustjose** [comment]
This log tells me nothing, just that some "`ItemStackTileEntityRenderer`" is causing the crash. I don't add any tile entities, did you add a tile entity to the `geolosys.json` file?

Either way, can you send me `debug.log` from within your `logs` directory when it crashes?

**Comment by oitsjustjose** [comment]
Nevermind - I was able to recreate the issue and I think I've solved it - let me test some.
