### ISSUE TITLE
Conflict with ToroQuest

### ISSUE THREAD

**Issue by Inf0214** [oitsjustjose/Geolosys#215]
## Versions: 1.12.2-3.0.7

- Minecraft Forge: forge-14.23.5.2847
- Geolosys: 3.0.7
- JourneyMap (optional): 5.5.5
- ImmersiveEngineering (optional): 0.12-91

## What happens:
Conflict with [ToroQuest](https://www.curseforge.com/minecraft/mc-mods/toroquest)
No villages spawn because it counts the ore spawns as village. 

## What should happen:
Spawn village and ore, without affecting each other.

**Comment by oitsjustjose** [comment]
I literally have no idea what his code is doing wrong to make this happen, but this definitely isn't on my end.

I place ores just like Vanilla does, and I place samples just like Vanilla does. If it's incompatible with my mod for placing samples on the surface, then the dev needs to re-evaluate how they choose where generation can be placed.

**Comment by oitsjustjose** [comment]
Reference: https://github.com/ToroCraft/ToroQuest/issues/197

**Comment by oitsjustjose** [comment]
Closing as stale and not supporting 1.12 any further.
