### ISSUE TITLE
Custom ores

### ISSUE THREAD

**Issue by LEWeee** [oitsjustjose/Geolosys#216]
Not really a bug or anything, I would just like to ask, is it possible to create my own ores using Geolosys without there being any other mod to add those ores? Like I would just add my own ore and then make it drop some other item (like, levers, for example).

**Comment by LEWeee** [comment]
I had no idea what I was thinking when I accidentally called it Charcoal Pit lmao

**Comment by oitsjustjose** [comment]
No, it's not possible nor is it a thing within the scope of the mod honestly. Sorry :frowning: I think it's a little early in the modded 1.14 life cycle for user-defined blocks
