### ISSUE TITLE
Granite Deposits reported as Autunite and Granite

### ISSUE THREAD

**Issue by colby-boucher** [oitsjustjose/Geolosys#219]
# Versions

Forge Version: 14.23.5.2847

Mod Version: 3.0.8

# Other Mods

https://www.modlister.com/user/Mummelpuffin

The Prospector's Pick sometimes reports "Autunite and Granite Found in this Area" when there is only granite. I first noticed the bug with MMD OreSpawn (listed on modlister as OreSpawn), because in worlds where OreSpawn had a hand in generation (even after it's uninstalled) I noticed it occur extremely often.  Without OreSpawn I notice it happen more rarely, though this may have to do with MMDLib's "fallback generation" when OreSpawn isn't present.  Are granite spawns in Geolosys relatively rare? Because that might account for the difference in frequency. I haven't had a chance to check for granite when it shows up without OreSpawn installed.

The one time I saw the bug occur without OreSpawn installed, there was granite around, but the pick *sometimes* managed to list it as a regular granite deposit. Again, this may have to do with MMDLib's fallback generation, though that's just a guess.

Admittedly, compatibility with other ore generators probably isn't a priority, but I figured I'd bring it up.

**Comment by oitsjustjose** [comment]
Thanks for this, I *swear* I had fixed this already but I'll look into it again :)
