### ISSUE TITLE
Suggestion: add prospector pick

### ISSUE THREAD

**Issue by Efimero** [oitsjustjose/Geolosys#22]
Since we're going for a mod-friendly terrafirma ore style, it would be really nice to have a Prospector Pick item that can tell you how much ore is around you in a vague way.
It would help a lot in locating those veins if they happen to be very deep and not directly below a sample.

**Comment by oitsjustjose** [comment]
I would, but I've spent *hours* thinking about how I could easily implement this since I - unlike TFC - do not track _where_ ores have generated in the past.

Fortunately, the new (as of 1.5) ore generation makes it almost impossible to miss ore veins!

**Comment by Efimero** [comment]
scan a 25x25x25 cube around the player and count the ores??

**Comment by oitsjustjose** [comment]
25x25x25 is too much (will literally cause the game to stop)....

how about 5x5x5; that's still 125 blocks in its worse case.

**Comment by Efimero** [comment]
how about a 25x25x25 area, but not every block? like say you take the clicked block, the block 5 away in each direction and the block 5 away in each direction from those etc recursively until you have enough, that would still give good enough results in a large area and would be quick
