### ISSUE TITLE
modded ores do not generate

### ISSUE THREAD

**Issue by Warbringer12** [oitsjustjose/Geolosys#221]
# Versions

Forge Version:
28.187
Mod Version:
Geolosys 1.14.4 4.0.9

put this into config didn't generate samples
	"blocks": [
        "funmod:insanity_ore",
        100
      ],
      "samples": [
        "funmod:insanity_ore",
        100
      ],
      "yMin": 3,
      "yMax": 25,
      "chance": 4,
      "size": 32,
      "dimBlacklist": [
        "the_nether",
        "the_end"
      ],
      "type": "DENSE",
      "density": 1.0,
    },

**Comment by oitsjustjose** [comment]
I assume that you've got it set up something like:

```json
{
	"ores": [{
		"blocks": [
			"funmod:insanity_ore",
			100
		],
		"samples": [
			"funmod:insanity_ore",
			100
		],
		"yMin": 3,
		"yMax": 25,
		"chance": 4,
		"size": 32,
		"dimBlacklist": [
			"the_nether",
			"the_end"
		],
		"type": "DENSE",
		"density": 1.0
	}],
	"stones": {}
}
```

I also noticed that you had an extra comma after `"density": 1.0`. I'm not sure if that's an issue as well.

**Comment by oitsjustjose** [comment]
Closed because this issue seems stale. Feel free to re-open if the issue persists.
