### ISSUE TITLE
Thinkers EFLN bug with coal

### ISSUE THREAD

**Issue by ghost** [oitsjustjose/Geolosys#223]
# Versions
1.12.2
Forge Version:
2847
Mod Version:
3.0.10
# Other Mods
Tinkers' Construct
Immersive Engineering
Bugs:
it like https://github.com/oitsjustjose/Geolosys/issues/159
but some different
i think because EFLN is 100%Chance drop 100% items
even the [air] block will drop Tons of Sulfur
so...
![image](https://user-images.githubusercontent.com/51057953/69798343-189be980-120c-11ea-9fe7-9d3a01cb47a3.png)

![image](https://user-images.githubusercontent.com/51057953/69797672-0e2d2000-120b-11ea-9263-e5f2e9a4577a.png)

Modpack:
https://www.curseforge.com/minecraft/modpacks/real-tech

**Comment by oitsjustjose** [comment]
This is **super** weird but I've been able to reproduce this issue. I'm going to look into this some more - I'm not sure what the heck it is but this isn't correct behavior either way.

**Comment by ghost** [comment]
> This is **super** weird but I've been able to reproduce this issue. I'm going to look into this some more - I'm not sure what the heck it is but this isn't correct behavior either way.

thank for help)
