### ISSUE TITLE
AppEng&UB Compat: Certus Quartz doesn't drop 

### ISSUE THREAD

**Issue by adosikas** [oitsjustjose/Geolosys#224]
# Versions

Forge Version: 14.23.5.2847

Mod Version: 1.12.2-3.0.10

# Other Mods
```
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] AutoRegLib-1.3-32
  [✔️] bettercaves-1.12.2-1.5.1
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2441-universal
  [✔️] buildcraft-all-7.99.24.3
  [✔️] chiselsandbits-14.33
  [✔️] Farseek-1.12-2.4
  [✔️] Geolosys-1.12.2-3.0.10
  [✔️] ImmersiveEngineering-0.12-92
  [✔️] InventoryTweaks-1.63
  [✔️] jei_1.12.2-4.15.0.292
  [✔️] jeiintegration_1.12.2-1.5.1.36
  [✔️] journeymap-1.12.2-5.5.5
  [📁] memory_repo (folder)
  [✔️] OceanFloor-1.12.2-1.0.2
  [✔️] Quark-r1.6-177
  [✔️] QuickLeafDecay-MC1.12.1-1.2.4
  [📁] railcraft (folder)
  [✔️] railcraft-12.0.0
  [✔️] RTG-1.12.2-6.1.0.0-snapshot.1
  [✔️] Streams-1.12-0.4.7
  [✔️] theoneprobe-1.12-1.4.28
  [✔️] UndergroundBiomesConstructs-1.12-1.3.7
```

It appears that assorted quartz doesn't drop certus quartz when generating in the UB variant(ie `undergroundbiomes:metamorphic_stone_geolosys.ore_vanilla.quartz`), but does in the normal form (`geolosys.ore_vanilla`).

Screenshots (I manually added certus quartz to the config because i couldn't find out why before)

Drops Nether Quartz only
![Drops Nether Quartz only](https://i.imgur.com/1eDZqNq.png)

Also drops Certus Quartz:
![Also drops Certus Quartz](https://i.imgur.com/MECUM3a.png)

Technically this is a UB bug, but given the triple-mod compatibility and looking at the way the AE compat is implemented, I think a fix here would be simpler.

**Comment by oitsjustjose** [comment]
I can't say that this is on my end actually -- while I can control what UBC ores drop, UBC has better control of its drops than I do and I think it should be on them. I'd suggest posting it there and linking here and if I'm wrong I'll gladly implement a fix :smile: I just want to avoid writing hacky code if it can be done more correctly. 

UBC GitHub: https://github.com/Aang23/UndergroundBiomesConstructs/issues
