### ISSUE TITLE
UndergroundBioms pom is 502'd

### ISSUE THREAD

**Issue by Marco-MP** [oitsjustjose/Geolosys#227]
# Versions

Forge Version: ForgeGradle 2.3-SNAPSHOT-6084129e

Mod Version: 3.0.10

# Other Mods

# Logs (if applicable)
[forgegradle.log](https://github.com/oitsjustjose/Geolosys/files/4024049/forgegradle.log)

Relevant Line:
> Could not GET 'https://maven.altillimity.com/content/groups/maven/exterminatorjeff/undergroundbiomes/undergroundbiomes/1.3.7-57-1.12.2/undergroundbiomes-1.3.7-57-1.12.2.pom'. Received status code 502 from server: Bad Gateway

Hi there,
I tried building Geolosys just now and noticed that the UndergroundBiomes POM from exterminatorjeff seems to have found its end.
Since his Version saw the last commit at 2013 I would suggest referencing to a newer fork like https://github.com/Aang23/UndergroundBiomesConstructs

If this is already in the making I am sorry to disturb.

Cheers,
Marco

**Comment by oitsjustjose** [comment]
Thanks, yeah I haven't been working on the 1.12.x branch at all but I've been running into this issue the last few weeks.

It's weird, while the Maven would make you think I'm using an ancient version of the API, the ExterminatorJeff Maven is actually being updated with Aang23's works so it _should_ be up to date, it just isn't working. I'll see if there are other ways to work around this.
