### ISSUE TITLE
Registration issue found in latest.log

### ISSUE THREAD

**Issue by NielsPilgaard** [oitsjustjose/Geolosys#228]
# Versions

Forge Version: 1.14.4-28.1.109

Mod Version: 1.14.4-4.0.11

# Other Mods

A ton, the modpack is Enigmatica 4. I don't think the modlist is relevant in this case, but I will ofcourse include it upon request.

# Logs (if applicable)
Outtake of latest log: https://gist.github.com/NillerMedDild/7d7a249332c963f78d7705f9dce9c90a
Full latest log: https://gist.github.com/NillerMedDild/e6c33f4caf42220c8f3feee353fb9f6c

**Comment by oitsjustjose** [comment]
This isn't an error, it's just a side-effect of disabling Geolosys's ingots.

**Comment by NielsPilgaard** [comment]
Hm, alright.
