### ISSUE TITLE
[Feature Request] Different stones using ore textures

### ISSUE THREAD

**Issue by ghost** [oitsjustjose/Geolosys#229]
# Versions

Forge Version: `28.1.111`
Mod Version: `1.14.4 4.0.11`

Could the ore texture be applied dynamically to the stone it is embedded in? Similar to how Underground Biomes does it? It looks kind of jarring to have a ore made for vanilla stone embedded around a stone like granite.

Also sorry, I didn't realize that this issue would get tagged as a bug.

**Comment by oitsjustjose** [comment]
UBC's method is very involved - I've already not had much luck with dynamic textures for samples, and I'm swamped with school work, Thesis and work. I don't think I'll have much time for something as big as this for a good little while - I may re-explore this concept this summer though.

**Comment by ghost** [comment]
No worries, good luck with all your work. Sorry, I didn't realize it would be very complicated to implement.

**Comment by Gliese-832-c** [comment]
Technically you could work around that, by using ContentTweaker to create custom ore blocks that look like the Geolosys ores, but with the UBC stone texture, and then make those spawn seperately.

**Comment by oitsjustjose** [comment]
Closing this for now - I don't foresee the time to do this anytime soon but I'm always open to PRs ^_^

In the meantime @Gliese-832-c's solution would probably be the best and most likely to work as expected.
