### ISSUE TITLE
Segustion: more config options.

### ISSUE THREAD

**Issue by darkshadow543** [oitsjustjose/Geolosys#23]
Can you make a configuration in the file that determines hardness, like how long it takes to mine, and the quantity of the ore dropped?

**Comment by oitsjustjose** [comment]
Sorry, I've made enough configs for things. They messy up the code and complicate a lot of it, because I end up having to refer to a config for almost every code block I end up wanting to write.

The quantity dropped and hardness are going to be set in stone - no pun intended.
