### ISSUE TITLE
(Question) configuration

### ISSUE THREAD

**Issue by Tealk** [oitsjustjose/Geolosys#230]
# Versions
Forge Version: 1.12.2-14.23.5.2847
Mod Version: 1.12.2 3.0.10

Hello,

it is not a bug report but i did not know where else to ask what some config settings mean.
I'll just list them here, maybe you can explain them to me in more detail:

- Enable Cluster Smelting
- Enable Coals
- Enable Ingots
- Replace Stone Variant Deposits

And do I have to activate the following if I want to have ores from other mods also as geologys cluster or does it have another meaning? The description with the chunk confuses me.

- Retroactively replace existing ores in world

**Comment by oitsjustjose** [comment]
Sure, here are some details:

- Enable Cluster Smelting: Toggles the ability to smelt clusters (the drop from ores). Mostly saves time from having to remove the smelting manually with CraftTweaker
- Enable Coals: Geolosys's Coal is capable of dropping variants of coals based on depth - this toggles that feature
- Enable Ingots: Whether or not to even add Ingots (if you have other mods already adding ingots you may not want EVEN MORE ingots)
- Replace Stone Variant Deposits: whether to replace vanilla stone variants with Geolosys's (e.g. diorite, andesite, etc.)
- Retroactively replace existing ores in world: As you enter chunks, non-Geolosys ores in the ore dictionary (vanilla and modded ores) will be replaced with corresponding Geolosys Variants.

Hope this helps!
