### ISSUE TITLE
Feature Suggestion: Minimum vein size for the prospector's pick

### ISSUE THREAD

**Issue by Gliese-832-c** [oitsjustjose/Geolosys#235]
# Versions

Forge Version: 2847

Mod Version: 3.0.10

# Other Mods

No real need for a modlist but whatever: https://imgur.com/a/iVZZXT3

# Feature request

The way I generate ores in my pack is the following: Geolosys generates rare but huge mega veins, and CoFH world generates small ore deposits everwhere. Those deposits are still pretty rare though, so if you need a lot of resources you still should mine the megaveins. The problem is, if I use the prospectors pick, it detects those small veins. So a way to set the minimum size the prospector's pick can detect would be nice. This could be implemented as a config option, I, for example, would set the minimum size to 20. This will make only big veins be recognized.

(I don't use Github a lot, so if someone could show me how to change the label to "feature request" or something similar to that, please do)

**Comment by oitsjustjose** [comment]
So looking into this, this is honestly a pretty big performance concern on my end. I'm worried that by increasing the complexity of the search algorithm to include an active count of `currentlyFoundOresInChunk` there will be a pretty big performance degradation, plus it's just a ton of work from a coding perspective. I think I may close this, but in future versions I may reconsider. Sorry 😢
