### ISSUE TITLE
[Feature Request?] Dimension Whitelist

### ISSUE THREAD

**Issue by CvoidWyvern** [oitsjustjose/Geolosys#237]
Correct me if I'm wrong but I can't find anything in the documentation saying that there can be a dimension whitelist. Best I can think of to do right now for this behavior is give it an array of every possible dim id with the wanted dims removed. Is there any better way of doing this? I plan on using multiple mods that can dynamically create new dimensions so even just giving it a blacklist of every dimension the pack adds wouldn't work.

**Comment by oitsjustjose** [comment]
This sounds like a good feature for the last update I plan for 1.12! Thanks for the input, I'll get on this as soon as I can!

**Comment by oitsjustjose** [comment]
So I'm *considering* refactoring the config style to look something like this:

```json
{
  "ores": [
    {
      ...,
      "biomes": {
        "list": [ "SANDY", "minecraft:plains", "biomesoplenty:meadow" ],
        "whitelist": true
      },
      "dimensions": {
        "list": [ "the_nether", "the_end" ],
        "whitelist": false
      }
    }
  ],
  "stones": [
    {
      ...
    }
  ]
}
```

This would apply for all versions - 1.12, 1.14 and 1.15. It would be a little bit of work but it'd help a lot with general usability.

**Comment by CvoidWyvern** [comment]
That looks a lot better, one thing I would ask for is also being able to give just a mod in the dimensions list for when you'd want generation in one mod's dynamically added dimensions and not another's.

**Comment by oitsjustjose** [comment]
I haven't forgotten about this by the way -- I've been really busy lately and this would be a pretty big overhaul to the pluton generation code (the configs are now datapacks so it's actually much easier), but I just don't have the time nor the motivation to really work on it currently. But it hasn't been forgotten.

Thanks for your patience :heart:

**Comment by oitsjustjose** [comment]
That was a huge pain, but it's done :) 

I'm happy with the result. So basically for a breakdown:

```json
{
  ...
  "dimensions": {
    "isBlacklist": false,
    "filter": [ "overworld" ]
  }
}
```

**If you're using the old `geolosys.json` method, you won't get this feature at all. That's it.**

If you're using the new datapack mechanic and you **DON'T** use this new syntax, it'll gladly use the old one (for as long as that code is maintainable at least) -- NO old datapacks should be broken :smile:
