### ISSUE TITLE
[1.12.1] Feature Request: Twilight Integration

### ISSUE THREAD

**Issue by Darkosto** [oitsjustjose/Geolosys#24]
Heya!

Is it possible we could work together to create a special handler for the Twilight Forest? I'd like to use Geolosys within every dimension and since the Twilight lowers sea level to around Y=30 samples spawn but may not have the height to properly spawn the ore chunk.

I'd love to work out a way to see if we can make this work together. This is not a trap, I promise >.>

Thanks!
Darkosto

**Comment by oitsjustjose** [comment]
I’ll work on it tonight, have you noticed if Geolosys at least succeeds in disabling normal ore gen in TF stone?

And what do you suggest I do about the TF ore caverns? Those seem to always generate with normal ores as I’m pretty sure it’s hard-coded.

**Comment by Darkosto** [comment]
Those are great questions! :)

I have not noticed other ores in the stone, so that seems to be okay.

The hollow hills are an interesting point, I like the idea of them and have been using them in the modpack. I wonder if there's a way to allow Geolosys to hook into the "structure" and populate it's own ores? This would maintain some of your mod's mechanics. 

Also, I left out from my initial message: Samples spawn regardless of whether or not the ore chunk spawns. For example, coal is a big offender.

Let me know if you have any other questions, or if you have time I'm currently streaming so I can give you info in real time :D

**Comment by Darkosto** [comment]
I hate to be that guy (no rush, just sharing):

https://pastebin.com/pa2R8Qpe

I had regenerated my config to make sure it wasn't on my end and it still crashed once I used the new file with my custom settings :)

**Comment by oitsjustjose** [comment]
Hmmm... that crash should only occur specifically if you don't have one of the ingots required.

Do you still have every single ingot that Geolosys adds? I might need to clean up some code here and there in case you disable a certain ore, but this should still *only* crash if you don't have every ingot required and do have the `Enable Ingots` config set to false.

**Comment by oitsjustjose** [comment]
You can also look in the full log file to see which entry is missing (or send it over and I can gladly tell you!)

**Comment by Darkosto** [comment]
I'll need to check to see which ones I'm missing. I had Enable Ingots set to false in the previous version, it only begun crashing in this newer update.

**Comment by Darkosto** [comment]
It looks like I'm missing Platinum. I can add that using Content Tweaker and it should fix the problem up :)

**Comment by oitsjustjose** [comment]
I honestly don't know why I throw exceptions for this; I guess I could just make it ignore the entry if you don't have the ingot <_<

Want a test build? :P

**Comment by oitsjustjose** [comment]
Latest commit makes smelting stuff less strict - if you don't have an ingot it just notifies you and moves on. No need to crash the game really. Not sure what I was thinking.

Did you see the TF issue I created? Anything I should add to it?

**Comment by oitsjustjose** [comment]
[Hope this works out!](https://puu.sh/xCguq/54f6b6bd78.jar)
