### ISSUE TITLE
proPickExtras config doesn't work

### ISSUE THREAD

**Issue by ellbristow** [oitsjustjose/Geolosys#241]
Here is my proPickExtras line in the common config:
`proPickExtras = ["mekanism:osmium_ore", "mekanism:salt_block"]`

During startup Forge reports this is an invalid Key and replaces it with []:
`[net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key prospecting.proPickExtras was corrected from [mekanism:osmium_ore, mekanism:salt_block] to []`

This means the prospector cannot detect osmium or salt, which I want it to

Forge version 31.1.74
Mod Version 1.15.2-4.0.14

**Comment by oitsjustjose** [comment]
I'll have to test this and see how it goes, it may be a syntax issue on your end or a bug on mine! Sorry for the inconvenience!

**Comment by oitsjustjose** [comment]
Should be fixed in 0e9ff6b, I believe this was a load-time issue.
