### ISSUE TITLE
[Error] [RecipeSerializer]: Recipe Serializer being returned as null by the RecipeManager.

### ISSUE THREAD

**Issue by Lanse505** [oitsjustjose/Geolosys#242]
# Versions
Forge Version: 31.2.0
Mod Version: 1.15.2-4.0.21

# Other Mods
https://gist.github.com/Lanse505/e9e473d1161dd998bec0ac1135ccb171

# Logs (if applicable)
https://gist.github.com/Lanse505/0cbcfe3dc6b55518b4c86a8d6681de22#file-logs-L2285

**Comment by Lanse505** [comment]
There are a few of these errors spread through-out the log.

My assumption would be that you're not registering your recipe serializers to the registry?
Though I haven't had time to dig into your code to debug yet since I'm in Finals Week.

**Comment by oitsjustjose** [comment]
I'm not adding any custom recipe serializers, these are normal smelting / blasting JSON recipes using all vanilla functionality, but the issue may be that you've disabled ingots and so it's complaining as the ingots aren't available to complete the recipe? I thought I had implemented `exists` tags for the recipes but maybe not.

**Comment by oitsjustjose** [comment]
This should've been fixed long ago when I removed a few settings and fixed a handful of Datapack things that changed with 1.16. If you're still having issues let me know.
