### ISSUE TITLE
[Error Logging]: Invalid Tags

### ISSUE THREAD

**Issue by Lanse505** [oitsjustjose/Geolosys#243]
# Versions
Forge Version: 31.2.0
Mod Version: 1.15.2-4.0.21

# Other Mods
https://gist.github.com/Lanse505/e9e473d1161dd998bec0ac1135ccb171

# Logs (if applicable)
https://gist.github.com/Lanse505/0cbcfe3dc6b55518b4c86a8d6681de22#file-logs-L2123-L2182

**Comment by oitsjustjose** [comment]
Same as before, is this due to you disabling Geolosys ingots?

**Comment by Lanse505** [comment]
So this is weird, I haven't actually touched the geolosys configs yet.
But the ingots were turned off 🤔 , this might just be user error.
I'll enable them again and close this enough.
