### ISSUE TITLE
Entering the bumblezone or theabyss:death with geolosys installed causes server threads to die.

### ISSUE THREAD

**Issue by croche2574** [oitsjustjose/Geolosys#246]
# Versions

Forge Version: forge-31.2.33

Mod Version: Geolosys-1.15.2-4.0.21

# Other Mods
[Forge]   Expanded Storage
Snow! Real Magic!
Kiwi
Abnormals Core
Allomancy 
Apotheosis
AppleSkin
Applied Energistics 2
Aquaculture 2
Atmospheric
AttributeFix
AutoRegLib
Autumnity
Bamboo Blocks
Basic Nether Ores
Berry Good
Better Advancements
Better Animals Plus
Bloomful
Bookshelf
Botania
Building Gadgets
Buzzier Bees
Caelus API (Forge)
Citadel
Cloth Config API (Forge)
Clumps
CodeChicken Lib 1.8.+
CoFH Core
Collective
Common   Capabilities
Controlling
Cooking for Blockheads
Corpse
CraftTweaker
Create
Crossroads MC
Culinary Construct
Curios API (Forge)
Curious Elytra (Forge)
Cyclops Core
Double Slabs
DRP - Global Data Pack
Druidcraft
Dungeon Crawl
Dungeons Plus
Enchantment Descriptions
End: Reborn
Ender Storage 1.8.+
Engineer's Decor
Essentials
FastFurnace
FTB Ultimine
Gaia Dimension
Hwyla
Immersive Engineering
Infinite Music
Item Filters
JAOPCA
JEITweaker
Just Enough Items (JEI)
Just Enough Resources (JER)
Kottle
LibraryEx
Light Overlay (Rift/Forge/Fabric)
Macaw's Bridges
Macaw's Doors
Macaw's Furniture
Macaw's Roofs
Macaw's Windows
Mahou Tsukai
Mana Gear
Mekanism
Mekanism Generators
Mine and Slash
MineColonies
MixinBootstrap
Mouse Tweaks
Nasty Mobs
Nature's Aura 
Nature's Compass
NetherEx
NetherPortalFix
No Default Auto-Jump
No Hostiles Around Campfire
No Recipe Book
Occultism
Oh The Biomes You'll Go
Pam's HarvestCraft 2 - Crops
Pam's HarvestCraft 2 - Food Core
Pam's HarvestCraft 2 - Trees
Patchouli
Performant
Phosphor (Forge)
Placebo
PlantTech 2
Productive Bees
Quark
Quark Oddities
Rats
Realistic Horse Genetics
ReAuth
Repurposed Structures (Forge)
Rotten Creatures
Rough Mobs Revamped 
Savage & Ravage
Save My Stronghold!
Screenshot to Clipboard (Forge)
Serene Seasons
Silent Gear 
Silent Lib
Silent's Gems
Simple Storage Network
spark
Spice of Life: Carrot Edition
Storage Drawers
Structure Gel API
Structurize
Swamp Expansion
SwingThroughGrass
The Abyss Project
The Bumblezone (Forge)
The Endergetic Expansion
The Midnight
The Undergarden
Toast Control
TrashSlot
Traveler's Backpack
Upgrade Aquatic
Valhelsia Structures
Village Spawn Point
Wawla - What Are We Looking At
Wither Skeleton Tweaks
Woot
World Stripper
YUNG's Better Caves
YUNG's Better Mineshafts (Forge)

# Logs (if applicable)
[2020-07-31-1.log](https://github.com/oitsjustjose/Geolosys/files/5008442/2020-07-31-1.log)

**Comment by croche2574** [comment]
A possible solution would be to offer a blacklist dimension config option, as the server worker deaths occur shortly after geolosys capability is attached to the dimension when you first enter.

**Comment by oitsjustjose** [comment]
I still haven't been able to reproduce this issue -- are you still having any problems? I can't imagine why  a server thread would die, especially after I had to rework so much code in v5.0.0.


I'm going to close this for now, as it's stale. If you have any updates let me know and I'll gladly re-open the issue and get back to work on debugging this.
