### ISSUE TITLE
Geolosys oreblocks are not tagged

### ISSUE THREAD

**Issue by ActualLily** [oitsjustjose/Geolosys#248]
Geolosys is incompatible with mods that assume ore blocks are tagged as `forge:ores` and `forge:ores/[name]`, in my case most notably with Scannable, which assumes ores are tagged as such. 

The dropped clusters are tagged as `forge:ores`, but since they're items dropped from the blocks, world interactions do not detect them.

This was tested on Geolosys 1.15.2 - 4.0.21, with Forge 31.2.36.

Geolosys config is default. Scannable config line 5 is as follows:

`blockColors = ["geolosys:coal_ore=0x111111", "geolosys:teallite_ore=0x938273", "geolosys:beryl_ore=0x00b174", "geolosys:bauxite_ore=0xb1a17d", "geolosys:cinnabar_ore=0x6e1809", "geolosys:gold_ore=0xdfbe3e", "geolosys:lapis_ore=0x004985", "geolosys:platinum_ore=0x9ea5b7", "geolosys:limonite_ore=0xdabb83", "geolosys:sphalerite_ore=0x493d5e", "geolosys:autunite_ore=0xadca00", "geolosys:quartz_ore=0xd6deea", "geolosys:galena_ore=0x8a8c9d", "geolosys:malachite_ore=0x357659", "geolosys:azurite_ore=0x253e6f", "geolosys:hematite_ore=0x692e1c", "geolosys:kimberlite_ore=0xe4e4e4"]`

**Comment by ActualLily** [comment]
Manually adding the block tags with crafttweaker fixes the issue. However, the ore blocks still should have block tags by themselves without requiring an user workaround.

**Comment by oitsjustjose** [comment]
I suppose I can go ahead and tag the blocks themselves, I don't see much harm in that. The intention was that the _cluster_ was the tagged ore for recipe compatibility with other mods, but since the player cannot silk touch Geolosys ores by default I don't see an issue also assuming the same logic for the block itself.
