### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by ChloeDawn** [oitsjustjose/Geolosys#25]
Game crashes with an `IndexOutOfBoundsException` during `postInit`.

**Mod version:** [1.7](https://minecraft.curseforge.com/projects/geolosys/files/2480279)
**Forge version:** [1.12.1-14.22.1.2485](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.1-14.22.1.2485/forge-1.12.1-14.22.1.2485-changelog.txt)

**Crash report:** [crash-2017-09-19_19.05.22-client.txt](https://gist.github.com/InsomniaKitten/481bdb28a5be21ee6083db75ee685fcd)
**Mod config:** [geolosys.cfg](https://gist.github.com/InsomniaKitten/c66edf30edc24995e368d44d7f8ef326)

**Comment by oitsjustjose** [comment]
[Try this build](https://puu.sh/xCguq/54f6b6bd78.jar).

I'm betting that you don't have every Ingot necessary to disable `enableIngots` like it says in the config...

**Comment by ChloeDawn** [comment]
Yeah that fixed the crash ^^
