### ISSUE TITLE
[Generation Bug] Other mods clusters destroying Geolosys clusters

### ISSUE THREAD

**Issue by juraj-hrivnak** [oitsjustjose/Geolosys#252]
# Versions

- Forge Version:
`1.12.2 - 14.23.5.2854`

- Mod Version:
`Geolosys-1.12.2-3.0.10`

# Other Mods
  [❌] AdvancedRocketry-1.12.2-1.7.0-235-universal.jar (disabled)
  [✔️] animania-1.12.2-base-2.0.1.25
  [✔️] antiqueatlas-1.12.2-4.6.3
  [✔️] AppleCore-mc1.12.2-3.4.0
  [✔️] AppleSkin-mc1.12-1.0.14
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] ASMC-1.12.2-1.0.2
  [✔️] auginter-1.1.0-1.12.x
  [✔️] AutoRegLib-1.3-32
  [✔️] BadMobs-1.12.2-1.1.40
  [✔️] base-1.12.2-3.13.0
  [✔️] Baubles-1.12-1.5.2
  [❌] BetterAdvancements-1.12.2-0.1.0.77.jar (disabled)
  [✔️] BetterDiving-1.12.2-1.5.8
  [✔️] BetterFps-1.4.8
  [✔️] BetterQuesting-3.5.329
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2444-universal
  [✔️] BiomeTweaker-1.12.2-3.2.369
  [✔️] BiomeTweakerCore-1.12.2-1.0.39
  [✔️] blockgravity-2.0.5
  [✔️] Bookshelf-1.12.2-2.3.590
  [✔️] BurningTorch-1.1.3
  [✔️] Ceramics-1.12-1.3.7
  [✔️] ClientTweaks_1.12.2-3.1.11
  [✔️] clothesline-1.12.2-0.0.3.0-bundle
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] CoFHWorld-1.12.2-1.4.0.1-universal
  [✔️] comforts-1.12.2-1.4.1.3
  [✔️] CompatSkills-1.12.2-1.17.0
  [✔️] ContentTweaker-1.12.2-4.9.1
  [✔️] Controlling-3.0.10
  [✔️] CookingForBlockheads_1.12.2-6.5.0
  [✔️] coroutil-1.12.1-1.2.37
  [✔️] CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
  [✔️] CraftTweaker2-1.12-4.1.20.607
  [✔️] CreativeCore_v1.10.34_mc1.12.2
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] Cuisine-0.5.22-build929
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] Cyclic-1.12.2-1.20.8
  [✔️] dawnoftime_builder_edition-1.0.7
  [✔️] Divergent-Underground-1.12-0.64.0
  [✔️] DynamicSurroundings-1.12.2-3.6.2.1
  [✔️] DynamicSurroundingsHuds-1.12.2-3.6.0.0
  [✔️] DynamicTrees-1.12.2-0.9.21
  [✔️] DynamicTreesBOP-1.12.2-1.4.4
  [✔️] DynamicTreesForestry-1.12.2-1.0.9
  [✔️] DynamicTreesPHC-1.12.2-2.0.5
  [✔️] EmergingTechnology-1.12.2-1.3.26-alpha
  [✔️] Exotic Birds 1.12.2-3.2.0
  [✔️] FantasticLib-1.12.2.044
  [✔️] Farseek-1.12-2.5.1
  [✔️] FE-1.12.2-0.1.3.1
  [✔️] foamfix-0.10.11-1.12.2
  [✔️] forestry_1.12.2-5.8.2.422
  [✔️] Forgelin-1.8.4
  [✔️] ForgeMultipart-1.12.2-2.6.2.83-universal
  [✔️] gamestagebooks-1.12.2-1.0.2-universal
  [✔️] GameStages-1.12.2-2.0.123
  [✔️] Geolosys-1.12.2-3.0.10
  [✔️] horse_colors-1.12.2-1.4.0.1
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] CharcoalPit-[1.12]-1.20
  [✔️] Chunk Pregenerator V1.12-2.4E
  [✔️] ido-1.12.2-1.1.0
  [✔️] ImmersiveEngineering-0.12-98
  [✔️] immersivepetroleum-1.12.2-1.1.9
  [✔️] ImmersivePosts-0.2.1
  [❌] ImmersiveRailroading-1.12.2-forge-1.8.0-7e0f82.jar (disabled)
  [✔️] InventoryTweaks-1.63
  [✔️] ItemPhysic_Full_1.4.34_mc1.12.2
  [✔️] ItemStages-1.12.2-2.0.49
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.16.1.302
  [✔️] journeymap-1.12.2-5.5.4
  [❌] journeymap-1.12.2-5.7.1.jar (disabled)
  [✔️] JourneyMapStages-1.12.2-2.0.9
  [✔️] JustEnoughPetroleum-0.1
  [✔️] Kiwi-1.12.2-0.5.3.32
  [❌] Koopa's+Critters+1.12+V1.11.jar (disabled)
  [❌] LibVulpes-1.12.2-0.4.2-75-universal.jar (disabled)
  [✔️] lightningtweaks-1.12.2-2.0.0.0-alpha1
  [✔️] LittleTiles_v1.5.0-pre199_73_mc1.12.2
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] matmos-1.12.2-35.2
  [✔️] MCMultiPart-2.5.3
  [✔️] MCTImmersiveTechnology-1.12.2-1.8.91
  [❌] Mekanism-1.12.2-9.8.3.390.jar (disabled)
  [❌] MekanismGenerators-1.12.2-9.8.3.390.jar (disabled)
  [📁] memory_repo (folder)
  [✔️] MixinBootstrap-1.0.5
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] MrTJPCore-1.12.2-2.1.4.43-universal
  [✔️] multiblockstages-1.2.0
  [✔️] NaturesCompass-1.12.2-1.8.5
  [✔️] NoAdvancements-1.12.2.002
  [✔️] nonetherPortals_v1.0.0formc1.12.2
  [✔️] noRecipeBook_v1.2.2formc1.12.2
  [✔️] NotEnoughPets-1.12.2-v2.2.0
  [✔️] NoWorldgen5You-1.12.2-1.0.6
  [✔️] NuclearCraft-2o.4.7-1.12.2
  [✔️] Nutrition-1.12.2-4.6.1
  [✔️] OreLib-1.12.2-3.6.0.1
  [❌] oreveins-2.0.15.jar (disabled)
  [✔️] outfox-0.1.5-mc1.12.2
  [✔️] Pam's HarvestCraft 1.12.2zg
  [✔️] particleculling-1.12.2-v1.0.1
  [✔️] Patchouli-1.0-22
  [✔️] phosphor-forge-mc1.12.2-0.2.7-universal
  [❌] Photoptics-1.12.2-0.1.1.1.jar (disabled)
  [✔️] platforms-1.12.0-1.4.6
  [✔️] PrettyBeaches_1.12.2-1.1.0
  [✔️] ProjectRed-1.12.2-4.9.4.120-Base
  [✔️] ProjectRed-1.12.2-4.9.4.120-fabrication
  [✔️] ProjectRed-1.12.2-4.9.4.120-integration
  [✔️] ProjectRed-1.12.2-4.9.4.120-lighting
  [✔️] ProjectRed-1.12.2-4.9.4.120-mechanical
  [✔️] ProjectRed-1.12.2-4.9.4.120-world
  [✔️] Puddles-1.1
  [✔️] Quark-r1.6-179
  [✔️] questbook-3.1.1-1.12
  [✔️] randompatches-1.12.2-1.22.1.10
  [✔️] RealFirstPerson2-1.12.2-1.3.2
  [✔️] RecipeStages-1.1.3
  [✔️] RecurrentComplex-1.4.8.2
  [✔️] Re-Fraction V1.0
  [✔️] Reskillable-1.12.2-1.13.0
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] RTG-1.12.2-6.1.0.0-snapshot.1
  [✔️] rustic-1.1.7
  [✔️] scarper-1.1
  [✔️] Scavenge V1.12-1.8.3.2
  [✔️] SereneSeasons-1.12.2-1.2.18-universal
  [✔️] shetiphiancore-1.12.0-3.5.9
  [✔️] SimpleDifficulty-1.12.2-0.3.4
  [✔️] SnowRealMagic-0.3.3
  [✔️] Sound-Physics-1.12.2-1.0.9
  [✔️] SpiceOfLife-mc1.12-1.3.12
  [✔️] StandardExpansion-3.4.173
  [❌] Stellar+API-1.12.2-0.4.2.9.jar (disabled)
  [❌] Stellar+Sky-1.12.2-0.5.2.8.jar (disabled)
  [✔️] Streams-1.12-0.4.9
  [✔️] Surge-1.12.2-2.0.79
  [✔️] TConstruct-1.12.2-2.13.0.183
  [✔️] TidyChunk-1.12.2-1.0.0.0
  [✔️] TinkersComplement-1.12.2-0.4.3
  [✔️] TipTheScales-1.12.2-1.0.4
  [❌] TrackAPI-1.2.jar (disabled)
  [✔️] tropicraft-MC1.12.2-7.1.9.115
  [❌] UndergroundBiomesConstructs-1.12-1.3.8.jar (disabled)
  [❌] UniversalModCore-1.12.2-forge-1.0.0.jar (disabled)
  [✔️] VanillaFix-1.0.10-150
  [✔️] Waddles-1.12.2-0.6.0
  [✔️] WailaHarvestability-mc1.12-1.1.12
  [✔️] walljump-1.12.2-1.3.2
  [✔️] Wawla-1.12.2-2.6.275
  [✔️] weather2-1.12.1-2.6.12
  [✔️] World-Stripper-1.6.0-1.12.2
  [✔️] worleycaves-1.12.2-1.5.2
# Logs (Probably not neceseary)
https://paste.ee/p/O0t94

### The Issue
`In these two first photos, ApliedEnergetics is overwriting the clusters`
![2021-01-08_17 20 02](https://user-images.githubusercontent.com/71150936/104039662-f201fd80-51d6-11eb-8cd0-bb47f6112d55.png)
![2021-01-08_17 20 12](https://user-images.githubusercontent.com/71150936/104039679-f62e1b00-51d6-11eb-8330-c72f3634c401.png)

`In this photo, Quark's clay generation is  overwriting`
![2021-01-08_17 20 39](https://user-images.githubusercontent.com/71150936/104039689-fa5a3880-51d6-11eb-8baa-ea206989d656.png)

`This bug was also discovered with Rustic's Slate`

**Comment by oitsjustjose** [comment]
Unfortunately I'm no longer supporting 1.12, and this isn't a bug on my end anyways. I can't prevent someone else's mod from generating over top of my blocks, but that other mod has control over what blocks their world gen replaces.

Might want to reach out to Mangoose and Vazkii about these issues if they're still supporting their mods on 1.12 as well. Sorry!

**Comment by juraj-hrivnak** [comment]
Yes, no worries! I will probably use other mod to generate the clusters.
But thanks for making this mod!
