### ISSUE TITLE
Ore with out sample

### ISSUE THREAD

**Issue by Mimic0445** [oitsjustjose/Geolosys#257]
I am adding some mod ores that you haven't added support for but...

The 1.12.2 version does not allow an ore with out an accompanying sample. (Crashes on world gen)
I set the sample to minecraft:air. This effectively makes an ore have no sample.

The side effect is that now the Prospector's Pick detects air making it useless because it always detects air first.

I would suggest changing the mod to allow an ore to have no sample. Or create a black list of blocks the Prospector's Pick can not detect.

**Comment by oitsjustjose** [comment]
This will **literally** be the last update I make in 1.12, but you make a good point.

Will you try [this build](https://www.mediafire.com/file/u4cv1d9sodq8j8v/Geolosys-1.12.2-3.0.11-BETA.jar/file) out and let me know if it solves the prospector's pick detecting air?

**Comment by Mimic0445** [comment]
Thanks for the quick update.

The build you linked shows "geolosys.pro_pick.tooltip.found_surface" if I use it above an ore deposit and "geolosys.pro_pick.tooltip.nonefound_surface" if I am not above an ore deposit.

I believe this means your change is working correctly but I am missing localization files.

**Comment by oitsjustjose** [comment]
Interesting that the localization isn't working, it should but I haven't
developed in 1.12 for so long that it could be something with my
development setup I threw together for this. I'm glad it's working, I'll
continue to work on it as I'm able to and should have a release out soon.

Thanks!

**Comment by oitsjustjose** [comment]
Sorry to dig up old dirt! I'm working on a huge refactor that allows you to set a sample as `null` with any chance (including 100%), so this would technically work. Unfortunately I only have so much time in the day so this feature will only be for 1.16 🙁

Closing as I know this feature will be out soon (ideally today!) and will not be able to be backported due to time constraints.
