### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by madmax3004** [oitsjustjose/Geolosys#258]
Server seems to have crashed, no clue what caused it but Geolosys seems to be involved:
https://pastebin.com/bbhggwHD

Geolosys Version: 5.0.0
Forge Version: 35.1.37

EDIT:

Seems like one of our players was in the middle of mining a Quartz deposit.

**Comment by oitsjustjose** [comment]
Your edit makes sense. I'll look into it this tomorrow and hopefully have a hot fix for it out tomorrow as well :)
