### ISSUE TITLE
[1.16] Disabling Ingots doesn't let me join singleplayer worlds

### ISSUE THREAD

**Issue by Zhwible** [oitsjustjose/Geolosys#259]
If I disable ingots in the config, I get a message saying my datapacks are incompatible or something. I'll get more info in a second.

**Comment by Zhwible** [comment]
![world save error](https://user-images.githubusercontent.com/78271482/106362802-d3cd8000-62f2-11eb-805b-20e32dbc764c.PNG)

Safe mode doesn't actually do anything. 

Main menu button works.

**Comment by oitsjustjose** [comment]
I can't seem to reproduce this issue. Do you happen to have other mods installed? If so, can you provide a modlist?

**Comment by EternalShadow17** [comment]
same problem using only geolosys and immersive engineering, and then again with only mekanism, so basicly any mod that ores I believe

**Comment by oitsjustjose** [comment]
@EternalShadow17  awesome, thanks for the info! I'll try that environment and see how it goes.

**Comment by oitsjustjose** [comment]
So unfortunately this is a result of a change in Vanilla in 1.16.2 or 3 (I don't know which exactly). Now, if you try to register an item tag with a nonexistent item you'll get this error. I can't find any workaround for this except to remove the config option and make people deal with the ingots. Sorry about that, it's just not within my control. If Forge ever adds a way to programmatically add item tags, I will be able to re-implement this config at that time.
