### ISSUE TITLE
Feature Crash with Setting Waterlogged Property on Non-Waterloggable Blocks

### ISSUE THREAD

**Issue by LokyLive** [oitsjustjose/Geolosys#260]
# Versions

Minecraft 1.16.5

Forge Version: 36.0.13

Mod Version: 5.0.0

I've certainly done a mistake in my Json file but i won't find it.... could i got any help please ?

#Crash Report
[crash-2021-01-31_10.26.46-server.txt](https://github.com/oitsjustjose/Geolosys/files/5899486/crash-2021-01-31_10.26.46-server.txt)

# Datapack 
[deposits.zip](https://github.com/oitsjustjose/Geolosys/files/5899482/deposits.zip)

**Comment by oitsjustjose** [comment]
The problem is the structure of your datapack:

```
.
└──YOUR_DATAPACK/
    ├── pack.mcmeta (REQUIRED)
    └── data/
         └── geolosys/
              └── deposits/
                   └── ALL_JSON_FILES_IN_YOUR_ZIP
```

***HOWEVER***, the crash report you've posted doesn't seem to be datapack related. I'll look into it briefly.

**Comment by LokyLive** [comment]
Ok so my Json are fine ! 
I will wait for update so thank you ,p

 About the path i've just zip the deposits folder to send here, atm i use Kubejs for my pack and i'm not using zip format.
