### ISSUE TITLE
values=[true, false]} as it does not exist in Block{minecraft:air} ???

### ISSUE THREAD

**Issue by LokyLive** [oitsjustjose/Geolosys#261]
Minecraft version : 1.16.5
Forge Version:36.0.14

Mod Version: 5.0.1

Game crash on world generation when loaded with custom JSON files
[kubejs.zip](https://github.com/oitsjustjose/Geolosys/files/5939234/kubejs.zip)

# Crash Logs 

https://pastebin.com/JWqDPdmt

**Comment by LokyLive** [comment]
I'm really out of solution so if you got any suggestion you're welcome 

An other crash report:
http://oitsjustjo.se/paste?id=nTP3Y3Nix

**Comment by oitsjustjose** [comment]
334869d7a20fc5cdc15f1aaf98d1103117549409 should fix this
