### ISSUE TITLE
[1.16.5] Field Manual won't open

### ISSUE THREAD

**Issue by ozBillo** [oitsjustjose/Geolosys#262]
Started using Geolosys in 1.16.5 a few days ago and I haven't been able to open the Field Manual.
The tooltip says item.patchouli.guide_book

Geolosys-1.16.5-5.0.2.jar
Patchouli-1.16.4-50.jar
Forge 36.0.22
MultiMC 5 0.6.11-1430

**Comment by Hubry** [comment]
The book.json in Geolosys is 1 directory too deep than the spec says, and the only reason it worked is Vazkii/Patchouli#326 - treating a file that ends with `book.json` literally anywhere in the directory tree as the book definition.

**Comment by oitsjustjose** [comment]
Ah good to know! I thought it was kind of weird being where it was.

Thanks!!

**Comment by ozBillo** [comment]
It works fine with Patchouli-1.16.4-48

**Comment by oitsjustjose** [comment]
Fixed in the latest release as well.
