### ISSUE TITLE
Ore Blocks are not in forge blocks/ores tag

### ISSUE THREAD

**Issue by Thutmose** [oitsjustjose/Geolosys#267]
## Versions:

- Minecraft Forge: 36.1.1
- Geolosys: 1.16.5-5.1.2

## What happens:

Geolosys ores do not show any tags for ores, when looking at the blocks in world, this inhibits some interactions which check for forge/ores tag on the blocks themselves.

No tags here:
![image](https://user-images.githubusercontent.com/2363472/112244037-ff9b2100-8c24-11eb-8b98-56abf049c91e.png)

## What should happen:

Geolosys ores should show the forge/ores tag.

Tags for Iron Ore:
![image](https://user-images.githubusercontent.com/2363472/112243960-e003f880-8c24-11eb-88d0-9f4f24cc1627.png)

## Additional Comments:

This mostly just requires including a copy of what is currently in `data/forge/tags/items/` in `data/forge/tags/blocks`, and not including the clusters in the one in `blocks`.

**Comment by oitsjustjose** [comment]
Easy enough. Fixed.

https://user-images.githubusercontent.com/3887324/112315920-9cd37500-8c78-11eb-84f0-bf4cd2a091c4.mp4
