### ISSUE TITLE
Logs drop from coal ore instead of sulfur

### ISSUE THREAD

**Issue by Bees-Please** [oitsjustjose/Geolosys#268]
- Minecraft Forge: 36.1.2
- Geolosys: 5.1.3

Current behavior: minecraft:logs drop from geolosys:coal_ore as per the loot modifier sulfur.json
![image](https://user-images.githubusercontent.com/65506993/112715896-60825d80-8ea0-11eb-8d56-d8dadbb118b2.png)

Expected behavior: forge:dusts/sulfur should drop from geolosys:coal_ore in place of logs.

**Comment by oitsjustjose** [comment]
😊 oops -- I left that in from my testing, didn't I! Let me fix that, thanks for catching that :heart:

**Comment by oitsjustjose** [comment]
Fixed in 23084ca62fa0d6503b4272a2be9208733af5763f
