### ISSUE TITLE
[1.16.5]Too many lakes

### ISSUE THREAD

**Issue by FEMT1915** [oitsjustjose/Geolosys#269]
## Versions:
- Minecraft Forge:1.16.5-36.1.0
- Geolosys:5.1.4
- Patchouli-1.16.4-50
- 
## What happens:
(Sorry. I'm not good at English. I used Google translate.)
A huge number of lakes are generated when I use this mod. It occurs mainly in plains and forests, regardless of seed.
![2021-04-10_21 54 39](https://user-images.githubusercontent.com/68454377/114270814-5b4d1300-9a49-11eb-9dec-34afda0282e6.png)

**Comment by davidjjung** [comment]
Agreed--and not just plains for me; savannahs and tundras are also prone to this. Great mod otherwise--best of luck figuring it out if it hasn't already been resolved!
![image](https://user-images.githubusercontent.com/72636500/120871817-c22f0a00-c56a-11eb-83c7-7d22452c60fe.png)

**Comment by pr1kol-zz** [comment]
Same problem
![asdjasdasalala](https://user-images.githubusercontent.com/42146272/120936549-0b20c300-c711-11eb-9d87-7e23777fcc30.png)

**Comment by Quarris** [comment]
Woah, I assume you guys have tested the exact same seed without geolosys as well to see that those lakes don't spawn? This is wild

**Comment by EwyBoy** [comment]
I created a PR fixing this issue:
https://github.com/oitsjustjose/Geolosys/pull/274
