### ISSUE TITLE
Geolysis not working in other dimesnions

### ISSUE THREAD

**Issue by Winddbourne** [oitsjustjose/Geolosys#271]
## Versions:

- Minecraft Forge: 
- Geolosys: 1.16.5-5.1.4
- JourneyMap (optional): no
- ImmersiveEngineering (optional): 1.16.5-4.2.4-134

## What happens:
Normal minecraft ore generation happens in other dimensions. I've tested this with both the advanced cave generation mod and the ratlantis mod.  

## What should happen:
Vanilla ore generation should be turned off and geollysis ore plutons should be showing up. 

## Additional Comments:
I did look for a dimension setting configuration in geolosys-common thinking that perhaps I had to specify which non overworld dimensions I wanted the mod to impact but I found nothing.

**Comment by oitsjustjose** [comment]
You must use MInecraft datapacks to configure which dimensions a pluton can generate. You can read the docs [here](https://mods.oitsjustjose.com/Geolosys#datapacks) to see how to do this. Ores _should_ in theory be turned off. I can't think of any reason why that wouldn't work - ores in the nether and end are turned off and I didn't do anything special to enable that, so I would assume the same for the other world types.

**Comment by Winddbourne** [comment]
Good to know. My overworld is a skyblock so the only place I could actually see any impact was the mining dimension and Ratlantis. At least the last one should be generating ore as an overworld but  they might be their own world type.
