### ISSUE TITLE
[1.16.5] Incorrect Forge Ore Tag

### ISSUE THREAD

**Issue by realTIMematrix** [oitsjustjose/Geolosys#273]
## Versions:

- Minecraft Forge: 36.1.24
- Geolosys: 5.1.4
- Mekanism: 10.0.21

## What happens:

Teallite Ore has two different forge:ore tags: forge:ores/tin and forge:ores/emerald

Mekanism Enrichment Chamber shows two receipes for Teallite Ore: 2 Tin Dust and 2 Emeralds and can only produces one of this receipes.

## What should happen:

Teallite Ore should only have the forge:ores/tin TAG and not the forge:ores/emerald

**Comment by oitsjustjose** [comment]
This is done on purpose -- IRL teallite has traces of Emerald, so it behaves like emerald in many ways. Hence the tag.

You can change the tag yourself with CraftTweaker / Datapacks though!
