### ISSUE TITLE
LAYER type deposits are generating samples but no ore when overriding plutons with data pack

### ISSUE THREAD

**Issue by Whiskey-Sunshine** [oitsjustjose/Geolosys#278]
## Versions:

- Minecraft Forge: 1.16.5-36.1.2
- Geolosys: 5.1.5
- JourneyMap (optional): N/A
- ImmersiveEngineering (optional): 5.0.2-137

## What happens:
Ore samples are generated on the surface, but the ore itself is not generated beneath the ground at all when a data pack override is used to change plutons to LAYER type.

## What should happen:
The plutons should generate in a layer type as specified by the .json entries

## Logs (if necessary):
Strangely enough, logs show no errors on generating plutons.

## Additional Comments:
I was admittedly getting very annoyed with sparse plutons and wanted to make things feel a bit more like the older 1.12.2 version, and started getting confused when world stripper was revealing emptiness where ores should have generated. After some time checking repeatedly, I noticed that the issue was coming from only ores that were generated with the LAYER type. DIKE, DENSE, SURFACE_LAYER, and SPARSE all worked correctly, still. 

[geolosys_overrides.zip](https://github.com/oitsjustjose/Geolosys/files/6871904/geolosys_overrides.zip)
[geolosys_overrides_no_layer.zip](https://github.com/oitsjustjose/Geolosys/files/6871905/geolosys_overrides_no_layer.zip)

Using the first datapack, all plutons generated with LAYER chosen (In this case, several coal types, lapis, cinnabar, and mystical world quicksilver) did not generate. With the second, they successfully generated. Some deposit sizes greatly increased for visibility.

Additional screenshots showing missing ores after using worldstripper, with a dense gold pluton showing that that one did generate correctly.
https://imgur.com/a/mASaCje

**Comment by oitsjustjose** [comment]
I believe this *should* be fixed in the [1.16.Refactor branch](https://github.com/oitsjustjose/Geolosys/tree/1.16.Refactor) but I'm not 100% sure, so I will port your datapack to the new format and verify that it works as expected.

**Comment by oitsjustjose** [comment]
Stale - closing until someone mentions they can reproduce in Geolosys 6.0.0+
