### ISSUE TITLE
[Question / Feature] 1.17 ore system (fortune)

### ISSUE THREAD

**Issue by TheSnowyChickens** [oitsjustjose/Geolosys#279]
## Versions:

- Minecraft Forge: 1.16.5
- Geolosys: 5.1.5
- JourneyMap (optional): no
- ImmersiveEngineering (optional): no
- Forge: 36.2.2

## Additional Comments:
Hello,
with 1.17 Mojang changed the behavior from non redstone/dia/emerald/coal/qzartz ore blocks to work with fortune.
I have a feeling that you'll be doing this for the 1.17 release anyway, so now the question if this is a possibility for 1.16.5 too.
:D

It would be awesome if you could do this for 1.16.5. (with or without the raw ore blocks)
The player base would certainly like it. 👍 

Ty for reading

**Comment by oitsjustjose** [comment]
See, I disagree with this design choice. Normally I'd say "let's make it a config option" but making datapacks dynamic to a config option is a **significant** pain. Not to mention that [I don't plan to port to 1.17](https://blog.oitsjustjose.com/?id=aGh2M2Px-), I really don't see a need for this to be a part of Geolosys specifically.

You can create this functionality **right now** with a datapack. See [here](https://minecraft.fandom.com/wiki/Data_Pack) on how to do it.

**Comment by TheSnowyChickens** [comment]
Ohh, I had no clue, that I can do it with datapacks. :D
(but ty for the info, I try to manage it (I am not a datapack pro, so maybe I need time))

Ohhhh, okay, skipping 1.17 is maybe the best way for all modders, because with 1.18 everything changes again.
I understand that. 👍

**Comment by TheSnowyChickens** [comment]
@oitsjustjose 
a quick hello.

is it possible to join on your discord to ask you stuff about custom ore gen with datapacks ?
(the DC link on curse don't work, a screen with the message "invalid link" appears)
