### ISSUE TITLE
ConfigGUI is inop

### ISSUE THREAD

**Issue by bookerthegeek** [oitsjustjose/Geolosys#28]
## HEYO ##

Sorry to be a bother about it, I did look for previous issues (I did see #26), but while the config is there nothing is editable when opening it, causing a sever lack of functionality... 

Also, how would one go about adding a drop to an ore? For instance Thermal Foundation adds some odd drops (A COFH item and a flowing liquid block). Would the ModPack maker be the one to integrate that, or would you be able to add some integration with that?

Thank you for the mod by the way, I have been looking for this style of mod for a while now. I look forward to TOrmenting my players with it.

#### Versions ####
- Minecraft 1.12.2
- jre1.8.0_131
- forge-1.12.2-14.23.0.2512-universal.jar
- Geolosys-1.12.1-1.8

<details>
<summary>Full Mod List (Sorry if the Spoiler does not work) </summary>

-  appliedenergistics2-rv5-alpha-8
-  base-1.12-3.3.1
-  Baubles-1.12-1.5.1
-  bdlib-1.14.2.8-mc1.12.1
-  Better With Addons-0.28
-  BetterWithMods-1.12-2.0.14
-  binnie-mods-1.12.2-2.4.0.78
-  blockdrops-1.12-1.3.0
-  Botania r1.10-349
-  BrandonsCore-1.12-2.3.3.132-universal
-  Chameleon-1.12-4.1.3
-  ChickenChunks-1.12-2.4.0.70-universal
-  Chunk Pregenerator Version 1.3
-  CodeChickenLib-1.12-3.1.3.313-universal
-  CoFHCore-1.12-4.3.5.13-universal
-  CoFHWorld-1.12-1.0.1.8-universal
-  compacter-1.3.0.2-mc1.12
-  ContentTweaker-1.12-4.1.0
-  CookingForBlockheads_1.12.1-6.3.6
-  CraftTweaker2-1.12-4.0.8
-  diethopper-1.1
-  Draconic-Evolution-1.12-2.3.4.265-universal
-  EnchantingTable-1.12-1.1.2
-  EnderStorage-1.12-2.4.0.122-universal
-  externaltweaker-1.12-0.3
-  FarmingForBlockheads_1.12-3.1.5
-  forestry_1.12.2-5.6.0.200
-  FriendlyFire-1.12.2-1.5.8
-  FTBLib-4.1.6
-  FTBUtilities-4.1.6
-  gendustry-1.6.5.4-mc1.12
-  Geolosys-1.12.1-1.8
-  ImmersiveEngineering-0.12-74
-  ImmersiveEngineering-0.12-74-core
-  immersivepetroleum-1.12-1.1.3
-  immersivetech-1.12-1.3.2
-  industrialcraft-2-2.8.16-ex112
-  IndustrialWires-1.6-20
-  InventoryTweaks-1.63
-  ironchest-1.12.2-7.0.34.820
-  jei_1.12.2-4.8.0.106
-  jeibees-0.9.0.4-mc1.12.1
-  jeiintegration_1.12.1-1.4.2.31
-  jepb-1.12-1.2.1
-  journeymap-1.12-5.5.0
-  Mantle-1.12-1.3.1.21
-  mcjtylib-1.12-2.4.4
-  mod_ChunkBorders_0.3.6_mc1.12.2
-  mod-tabbychat-2.3.3-mc1.12.2
-  modtweaker-4.0.3
-  MTLib-3.0.0
-  NoNausea-MC1.12-1.0
-  notenoughwands-1.12-1.5.9
-  PersistentBits-1.12-1.0.6a
-  Pulver-1.12-1.1
-  RandomThings-MC1.12.2-4.0.6.1
-  RedstoneArsenal-1.12-2.3.5.13-universal
-  RedstoneFlux-1.12-2.0.1.2-universal
-  restrictedportals-1.12-0.6.2
-  roots-2-0.103
-  roughMobs1.0.13-1.12.1
-  sentek-1.7
-  SilentBoss-1.5.0
-  StorageDrawers-1.12.1-5.3.3
-  SuperMiner-2.6.34.336
-  TConstruct-1.12-2.7.3.30
-  theoneprobe-1.12-1.4.18
-  ThermalCultivation-1.12-0.1.1.6-universal
-  ThermalDynamics-1.12-2.3.5.12-universal
-  ThermalExpansion-1.12-5.3.5.19-universal
-  ThermalFoundation-1.12-2.3.5.14-universal
-  Tinkers' Addons-1.12.1-1.0.7
-  topaddons-1.12.2-1.1.1
-  torchmaster_1.12.2-1.6.0.50
-  Traverse-1.12.1-1.3.1
-  twilightforest-1.12.2-3.0.0-universal
-  World-Stripper-1.4.1-1.12.1
-  xnet-1.12-1.4.0
</details>

**Comment by oitsjustjose** [comment]
The ConfigGUI only works from the main menu because all of the settings require a Game restart. 

As for custom drops: I won't be supporting custom drops; I believe some other mods can do this, this for you, but I'm not sure what they are called (maybe ask [r/feedthebeast](http://reddit.com/r/feedthebeast)?
