### ISSUE TITLE
[Suggestion] (BLOCK KINDS) Support for Stone -> Block Mappings

### ISSUE THREAD

**Issue by oitsjustjose** [oitsjustjose/Geolosys#280]
As per Rorax, add the ability to support BlockKinds, which are a specific type of BlockStateMatcher that support a specific mapping of stone -> ore i.e. only replace diorite with dioritic ores, etc.

```json
"blocks":[{
        "block": "geolosys:coal",
        "chance": 50
},  {
  "blockkinds":[{
      "blocktype": "minecraft:diorite",
      "replace": "geolosys:coal_diorite"
  },  {
      "blocktype": "minecraft:granite",
      "replace": "geolosys:coal_granite"
  }, {
      "blocktype": "minecraft:andesite",
      "replace": "geolosys:coal_andesite"
  }, {
      "blocktype": "minecraft:stone",
      "replace": "geolosys:coal"
  } ],
  "chance": 50
}]
```

**Comment by userofbricks** [comment]
this is what I need!

**Comment by oitsjustjose** [comment]
BlockKinds were implemented in their own way already and will only be supported in 1.18+ - I will not be backporting this feature, but if someone else did it in a PR knock yourself out!

[Relevant Commit](https://github.com/oitsjustjose/Geolosys/commit/3a4cff4ddddf467872efc9b83a3197827ca06e63)
