### ISSUE TITLE
[1.12] Allow disabling ores.

### ISSUE THREAD

**Issue by MagmaSlime123** [oitsjustjose/Geolosys#283]
Please add a config option to disable ores/ore samples completely and their generation. I'm not using most of the mods that add stuff like Lead, Tin, Nickel, Yellorium, etc.

I mainly care about Vanilla ores and don't need random useless ores sitting in the Creative inventory or generating.

**Comment by oitsjustjose** [comment]
I'm not supporting 1.12 anymore and haven't for a while. Sorry about that.

**Comment by MagmaSlime123** [comment]
Remove the older versions then.

Not sure why a few config options can't be added.

**Comment by copygirl** [comment]
Ah, yes. Prevent everyone from using Geolosys on 1.12, just because you can't have your feature.
