### ISSUE TITLE
Coal not dropping sulfur dust at all on my server despite enabled it in the configs

### ISSUE THREAD

**Issue by Dyshonored** [oitsjustjose/Geolosys#285]
## Versions:

- Minecraft Forge:
- Geolosys: 1.16 x 5.1.5
- JourneyMap (optional):
- ImmersiveEngineering (optional): 1.16.5-5.0.5-140

## What happens:
I mined 100+ coal ore on my modded SMP server and did not get a single sulfur dust item, despite having "drop sulfur" entry in the config set to true. I am not using any datapacks that modifies the drop rate at all. It's as if the drop sulfur setting is disabled.
## What should happen:
Sulfur dust should be obtained from 50% of the time as specified in the mod file's default data folder
## Additional Comments:
I tried running the same modpack in single player but sulfur dust are dropping properly. This issue only seems to affect my server.. Both my server and the single player game are on forge 36.2.4 btw.

**Comment by oitsjustjose** [comment]
Can you still reproduce this in the latest version of Geolosys for 1.16?

**Comment by oitsjustjose** [comment]
Do you have any mods installed which provide sulfur? If not, this won't work.
