### ISSUE TITLE
Customize pluton gen with configs?

### ISSUE THREAD

**Issue by BigAl607** [oitsjustjose/Geolosys#287]
I've had an idea in mind for a modpack relying heavily on Geolosys. As it is right now, the plutons spawn too frequently, too close together, and too small for what I need for the pack. Is there a way, or could you implement a way, to have the plutons spawn in multiple, connecting chunks, spawn farther apart than they currently do, and spawn less frequently. This last option I have in mind more for the lead & silver plutons which seem to spawn a lot more often than other plutons do.

If this isn't something you could easily add, I don't want to make a bunch of extra work for you. I have looked at the current configs, and I'm not sure I understand how they currently work. I have experience in java, but it's been a long time ago.

**Comment by oitsjustjose** [comment]
Which version are you on?

**Comment by BigAl607** [comment]
I'm passing up on the older version and will be using the latest release, 1.18.1-7.0.1 beta-1

**Comment by oitsjustjose** [comment]
Sorry for never really thoroughly explaining this - I've been busy for the last *year* so I really just try to get to issues when I can.

So the current system uses Datapacks. You can read up on Datapacks and the Geolosys Datapack system [in the Docs](https://docs.geolosys.com). That *is* the configuration system, and there aren't any plans to change that.

If you need help, we have a [wonderful Discord Server](https://discord.geolosys.com) if you need further help!

**Comment by BigAl607** [comment]
Thanks, I'll definitely be digging in soon. I get being busy. No need to apologize to me for that.
