### ISSUE TITLE
[1.18.1][Bug] No Patchouli yet

### ISSUE THREAD

**Issue by andr9528** [oitsjustjose/Geolosys#288]
## Versions:

- Minecraft 1.8.1
- Minecraft Forge: 39.05
- Geolosys: Geolosys-1.18.1
- Patchouli: M.I.A

## What happens:
With the mod enabled, The game fails to load as no version of 'Patchouli' exists for version 1.18.1 of minecraft - yet.

## What should happen:
Game should load, but not add the ingame book which is the one that makes use of 'Patchouli' to my knowledge.

## Additional Comments:
How did you manage to create a version for 1.18.1, when a dependency hasn't been updated for 1.18.1 yet? 
Did you just use the 1.16.5 version, and assume no changes is going to happen?

**Comment by oitsjustjose** [comment]
I literally put a link to it in the change log on CurseForge

**Comment by andr9528** [comment]
Sorry, didn't know there was a link in the changelog.

To my defence it isn't obvious to find the Changelog for versions for minecraft 1.18.1. 
You have to go to Files -> Scroll to Recent Files -> Click View All --> Click desired version of mod. Only then will the changelog be shown. All of this is imposible via the CurseForge app, which is how i mainly find mods.

I think it is so obscure because the file is listed as a alpha version.
