### ISSUE TITLE
[1.12.2] Suggestion/Question about mod integration

### ISSUE THREAD

**Issue by LukewarmYeti** [oitsjustjose/Geolosys#29]
I've seen below that people have asked about mekanism intergration etc. 

If this isn't currently being worked on, is there anyway (I'm a noob with config files so maybe this can already be done but I'm not noticing it) to add a drop to the already existing ores?

Example: 1. Ore that drops lapis also has a chance to drop apitate (forestry)
2. Ore that drops aluminium can also drop osmium (mekanism) etc. 

This can be done in the same way that the quartz ore can drop nether quartz or certus quartz.

**Comment by oitsjustjose** [comment]
I don't think I'll be adding that. It sounds like you should maybe look into creating your own ores in ContentTweaker, then using Geolosys to generate them? Not particularly sure, but unfortunately I don't plan to implement ~~a migraine~~ that much modularity into Geolosys.

**Comment by LukewarmYeti** [comment]
Its fine I stopped using your mod a while ago, thanks anyway!
