### ISSUE TITLE
Funky behavior with isBlacklist for biomes

### ISSUE THREAD

**Issue by SuspiciousMango** [oitsjustjose/Geolosys#290]
## Versions: 

- Minecraft Forge: 36.2.20 for MC 1.16.5
- Geolosys: 6.0.1 (the refactored beta)
- JourneyMap (optional): 5.7.3
- ImmersiveEngineering (optional): N/A

## What happens: 
I believe I'm having a similar issue to https://github.com/oitsjustjose/Geolosys/issues/244#issue-650236889 on the 1.16 version of the mod. I'm trying to spawn ore (specifically peat as a top layer deposit) in specific biomes. My file works perfectly fine without the biome section (so I'm pretty sure it isn't a syntax issue), but when the biome section is added and "isBlacklist" is set to true, the ores spawn everywhere, including the biomes on the blacklist. When "isBlacklist" is set to false, (the biome list should be a whitelist) the ores do not seem to spawn anywhere at all.

## Logs (if necessary): 
I dont have geolosys logging turned on, but if you feel it would help I'm happy to do so and send one your way

## Additional Comments:
With this as my peat.json, the deposits gen just fine, but they gen in every biome, which I don't want.
```
{
	"type": "geolosys:deposit_top_layer",
	"config": {
		"blocks": [
			{
				"block": "geolosys:peat",
				"chance": 1.0
			}
		],
		"radius": 5,
		"depth": 4,
		"samples": [
			{
				"block": "geolosys:rhododendron",
				"chance": 1.0
			}
		],
		"chanceForSample": 0.5,
		"generationWeight": 10,
		"blockStateMatchers": [ 
			"minecraft:grass_block",
			"minecraft:dirt",
			"minecraft:podzol"
		],
		"dimensions": {
			"isBlacklist": true,
			"filter": [
				"the_nether",
				"the_end"
			]
		}
	}
}
```

With this as my peat.json, peat doesn't gen at all, in any biome, whether or not it is on the (what should be a) whitelist. At least as far as I can tell.
```
{
	"type": "geolosys:deposit_top_layer",
	"config": {
		"blocks": [
			{
				"block": "geolosys:peat",
				"chance": 1.0
			}
		],
		"radius": 5,
		"depth": 4,
		"samples": [
			{
				"block": "geolosys:rhododendron",
				"chance": 1.0
			}
		],
		"chanceForSample": 0.5,
		"generationWeight": 10,
		"biomes": {
			"isBlacklist": false,
			"filter": [
				"minecraft:bamboo_jungle",
				"minecraft:bamboo_jungle_hills",
				"minecraft:birch_forest",
				"minecraft:birch_forest_hills",
				"minecraft:dark_forest",
				"minecraft:dark_forest_hills",
				"minecraft:flower_forest",
				"minecraft:forest",
				"minecraft:giant_spruce_taiga",
				"minecraft:giant_spruce_taiga_hills",
				"minecraft:giant_tree_taiga",
				"minecraft:giant_tree_taiga_hills",
				"minecraft:jungle",
				"minecraft:jungle_edge",
				"minecraft:jungle_hills",
				"minecraft:modified_jungle",
				"minecraft:modified_jungle_edge",
				"minecraft:savanna",
				"minecraft:swamp",
				"minecraft:swamp_hills",
				"minecraft:taiga",
				"minecraft:taiga_hills",
				"minecraft:tall_birch_forest",
				"minecraft:tall_birch_hills",
				"minecraft:wooded_hills"
			]
		},
		"blockStateMatchers": [ 
			"minecraft:grass_block",
			"minecraft:dirt",
			"minecraft:podzol"
		],
		"dimensions": {
			"isBlacklist": true,
			"filter": [
				"the_nether",
				"the_end"
			]
		}
	}
}
```

With this as my peat.json, peat is back to generating anywhere, in any biome (even though those specific biomes should be blacklisted).
```
{
	"type": "geolosys:deposit_top_layer",
	"config": {
		"blocks": [
			{
				"block": "geolosys:peat",
				"chance": 1.0
			}
		],
		"radius": 5,
		"depth": 4,
		"samples": [
			{
				"block": "geolosys:rhododendron",
				"chance": 1.0
			}
		],
		"chanceForSample": 0.5,
		"generationWeight": 10,
		"biomes": {
			"isBlacklist": true,
			"filter": [
				"minecraft:bamboo_jungle",
				"minecraft:bamboo_jungle_hills",
				"minecraft:birch_forest",
				"minecraft:birch_forest_hills",
				"minecraft:dark_forest",
				"minecraft:dark_forest_hills",
				"minecraft:flower_forest",
				"minecraft:forest",
				"minecraft:giant_spruce_taiga",
				"minecraft:giant_spruce_taiga_hills",
				"minecraft:giant_tree_taiga",
				"minecraft:giant_tree_taiga_hills",
				"minecraft:jungle",
				"minecraft:jungle_edge",
				"minecraft:jungle_hills",
				"minecraft:modified_jungle",
				"minecraft:modified_jungle_edge",
				"minecraft:savanna",
				"minecraft:swamp",
				"minecraft:swamp_hills",
				"minecraft:taiga",
				"minecraft:taiga_hills",
				"minecraft:tall_birch_forest",
				"minecraft:tall_birch_hills",
				"minecraft:wooded_hills"
			]
		},
		"blockStateMatchers": [ 
			"minecraft:grass_block",
			"minecraft:dirt",
			"minecraft:podzol"
		],
		"dimensions": {
			"isBlacklist": true,
			"filter": [
				"the_nether",
				"the_end"
			]
		}
	}
}
```
on a world using the above json, I literally spawned next to a peat deposit in a birch forest (one of the "blacklisted" biomes)
![image](https://user-images.githubusercontent.com/32881537/148470655-018e1d66-0a47-4f1a-8c2d-ef1915bb7b2e.png)

**Comment by SuspiciousMango** [comment]
Nevermind. After further testing I've figured out my issue. Removing the "minecraft:" before the biome name fixed it. Will be closing this issue for now. It might be worth it to put something in the documentation that lets people know to exclude the mod name from the biome list.

**Comment by oitsjustjose** [comment]
I was just looking into this, that's super strange that the namespace (`minecraft:`) can't be included, it should work regardless. I'll continue to look into this, thanks for the FYI :)

**Comment by Tellik** [comment]
After trying to figure out what and why was going on, I saw this.

I'm having the same issue, however it just is ignoring everything and doing what it wants. If I put something wrong, like the namespace, it doesn't generate at all. If I put just the biome name, like swamp or plains, it still generates in those biomes ignoring the black list.
