### ISSUE TITLE
Geolosys should use BlockTags to control what blocks Samples can be placed on.

### ISSUE THREAD

**Issue by Darkhax** [oitsjustjose/Geolosys#292]
## Versions:

- Minecraft Forge: 36.0.59
- Geolosys: 7.0.1-beta4

## What happens: Ore samples are spawning on top of houses, trees, and other worldgen features.
![image](https://user-images.githubusercontent.com/2250798/151287253-4d7b1d48-e264-4767-9f29-bcca7ee6db3d.png)

**Comment by oitsjustjose** [comment]
Yeah there's a `samplePlacementBlacklist` in the Common Config that works for this, but in thinking on this a bit I've realized that maybe making a whitelist-based Block Tag (like `geolosys:can_place_sample_on`), it could include only the blocks to place samples on and could be expanded in modpacks.

Leaving this open and re-titling, unless there's an urgent need for some other workaround.

**Comment by oitsjustjose** [comment]
Fixed in 007aa9b

**Comment by Darkhax** [comment]
Nice, thank you.
