### ISSUE TITLE
Seems like geolosys is using the wrong classloader for Patchouli?

### ISSUE THREAD

**Issue by PJRamaglia** [oitsjustjose/Geolosys#294]
## Versions:

- Minecraft Forge: forge-1.18.1-39.0.63
- Geolosys: Geolosys-1.18.1-7.0.1-beta-4
- JourneyMap (optional): N/A
- ImmersiveEngineering (optional): N/A

## What happens: 
Please refer to lines 114 - 153 of my server's latest.log file.  It appears there is an error between Geolosys and Patchouli.

## What should happen: 
N/A

## Logs (if necessary): 
https://gist.github.com/PJRamaglia/c6c85c118a8b34bab1615ac98440dee9

## Additional Comments: 
N/A

**Comment by Hubry** [comment]
I should probably say that this is my hypothesis, they came to Vazkii's discord with this log.

This completable future [here](https://github.com/oitsjustjose/Geolosys/blob/34de49e5c5677fe5629dafe64fc4c89884252da3/src/main/java/com/oitsjustjose/geolosys/client/patchouli/processors/PatronProcessor.java#L18) should probably be using a thread with the context classloader set to the transforming classloader (`Thread.currentThread().getContextClassLoader()` should work fine).  
Or should just return some sort of raw data that would be processed on the game thread.

**Comment by oitsjustjose** [comment]
Yeah you're right, I had to write that in really quickly in the middle of my work day so I didn't really put a lot of thought there.

Will fix soon.

**Comment by oitsjustjose** [comment]
Hopefully fixed in 2585c4c, please let me know if that's not the case.

**Comment by oitsjustjose** [comment]
Hopefully fixed in 2585c4c, please let me know if that's not the case.
