### ISSUE TITLE
Geolosys-1.18.1-7.0.2 Set Block Errors Spamming Server Log

### ISSUE THREAD

**Issue by TheWitherlord** [oitsjustjose/Geolosys#296]
## Versions:

- Minecraft Forge: **1.18.1-39.0.75**
- Geolosys: **1.18.1-7.0.2**
- JourneyMap (optional): **1.18.1-5.8.0beta14**
- ImmersiveEngineering (optional): N/A

## What happens:
Dedicated server gets spammed by setblock errors, the config option for debug logs are set to false if that helps.
## What should happen:
I assume the server log shouldn't be spammed by errors.
## Logs (if necessary):
**https://gist.github.com/TheWitherlord/9fbd0d6418db423f342a6488ef1abd8d**

**Comment by oitsjustjose** [comment]
This is a [Vanilla Bug](https://bugs.mojang.com/browse/MC-230004) that I cannot fix.
