### ISSUE TITLE
Biome types aren't working in biome filter

### ISSUE THREAD

**Issue by ghost** [oitsjustjose/Geolosys#297]
## Versions:

- Minecraft Forge: 39.0.79
- Geolosys: 7.0.2

## What happens:

Using a biome type (e. g. `MOUNTAIN`) in the biome filter doesn't generate the deposit in these biomes. Regular biome names work though. This bug results in many ores not generating even with the default configuration.

## What should happen:

The ore should generate in all biomes that are in the specified biome types.

**Comment by oitsjustjose** [comment]
On vacation until Monday and then I'm planning and prepping for my wedding in late March. I'll get to this as soon as I can.

**Comment by oitsjustjose** [comment]
Fixed in 17cbccea5cae5f406e3c4a1f556d489d6f4eaafe
