### ISSUE TITLE
copper found at bedrock level

### ISSUE THREAD

**Issue by Zygus42** [oitsjustjose/Geolosys#3]
Using Geolosys-1.12-1.1-alpha, I noticed that the tin-bearing deposits were quite close to the surface, but copper was found down at bedrock level.  I'm not certain what the ore type was called, as I neglected to have JEI on at the time of testing.

**Comment by oitsjustjose** [comment]
Generally, Tin & Copper bearing deposits can be found at any depths. Azurite & Teallite are found deeper in the ground, where Malachite & Cassiterite can be found in the upper Y levels.

Happy mining!
