### ISSUE TITLE
Geolosys ore blocks dropping minecraft ore blocks when silk touched

### ISSUE THREAD

**Issue by CrusaderRabbit** [oitsjustjose/Geolosys#300]
## Versions:

- Minecraft Forge:
- Geolosys: Geolosys-1.18.1-7.0.3.jar
- JourneyMap (optional): NA
- ImmersiveEngineering (optional): 
ImmersiveEngineering-1.18.1-7.1.0-145.jar

## What happens:
When silk touching Geolosys ore, you get vanilla Minecraft ore back (IE. silk touch mining geolosys:hematite_ore gives you minecraft:iron_ore

## What should happen:
Silk touching ore should return geolosys ore blocks

**Comment by oitsjustjose** [comment]
Intended - this was done for compatibility purposes (for example, Astral Sorcery requires Vanilla Iron Ore). If there's enough proof that this isn't necessary as a result of modders making their mods more data-driven, I'll re-open this issue and get to work :)
