### ISSUE TITLE
Add a chance to get the resource from a sample

### ISSUE THREAD

**Issue by oswaldino** [oitsjustjose/Geolosys#301]
I would like to suggest the following:

If a player or entity (i.e. Create's drill) digs the sample, it has a certain % of generating a resource. This should be set in the config.

If the sample is picked via the prospector's pick, the chance is 100% (or just higher, could be set in the config gile, but the defautl should be 100% imo).

There also should be a config array that would contain special chances for the specific samples to drop their resource. It would be a bit mor ligcal if diamond would drop less than iron.

**Comment by oitsjustjose** [comment]
This can be easily done on your own with a datapack, so I'd say this is beyond the scope of Geolosys.
