### ISSUE TITLE
"Detected setBlock in a far chunk" log spam in 7.0.4

### ISSUE THREAD

**Issue by BlackxSnow** [oitsjustjose/Geolosys#303]
## Versions:

- Minecraft Forge: 40.0.52
- Geolosys: 1.18.2 7.0.4

According to the 7.0.3 changelog, this should've been fixed, but I'm experiencing it now in a fresh install.

## Logs (if necessary):
`[18Apr2022 22:57:50.161] [Worker-Main-81/ERROR] [net.minecraft.Util/]: Detected setBlock in a far chunk [6, 2], pos: BlockPos{x=98, y=41, z=38}, status: minecraft:features, currently generating: Placed Reference{ResourceKey[minecraft:worldgen/configured_feature / geolosys:deposits]=Configured: com.oitsjustjose.geolosys.common.world.feature.DepositFeature@260f616c: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@a3100d5}`

**Comment by oitsjustjose** [comment]
Just released this fix in 7.0.5, once again thank you so very much.
