### ISSUE TITLE
Bizarre compatability issues with Bigger Reactors

### ISSUE THREAD

**Issue by C1ffisme** [oitsjustjose/Geolosys#308]
## Versions:

- Minecraft Forge: 40.1.15
- Geolosys: 1.18.2-7.0.5
- Bigger Reactors: 1.18.2-0.6.0-beta.1

## What happens:

The game crashes after startup

## What should happen:

The game should not crash after startup

## Logs (if necessary):

https://paste.ee/p/kWL4M

## Additional Comments:

Installing with quartz and phosphophyllite still works, but as soon as Bigger Reactors is added to the mix, the game will not start up properly. Sometimes this results in the whole game straight-up crashing, but with just quartz + phosphophyllite + Bigger Reactors + Patchouli + Geolosys, Minecraft at least displayed the error in the Minecraft window.

**Comment by oitsjustjose** [comment]
This really is strange. Let me look into it, but @lukebemish pushed a huge PR the other day that should hopefully resolve a handful of the issues with the way Geolosys was written. Let me try to resolve another bug or two and then I'll release a new version and you can re-test.

**Comment by lukebemish** [comment]
Oh, yeah, I consistently got this crash on the old version, sometimes just with Geolosys on its own. My PR should have fixed it.

**Comment by oitsjustjose** [comment]
Wack. Thank you for all those changes ❤️❤️❤️

**Comment by oitsjustjose** [comment]
Just released the version with @lukebemish's latest changes.

**Comment by C1ffisme** [comment]
The game starts now, but after updating the mod and adding BiggerReactors I get this message at the bottom of the screen. I'm not sure yet if this is BiggerReactors or Geolosys doing this. The message doesn't go away even by right-clicking a bed or using the prospector's pick

![2022-05-05_16 48 27](https://user-images.githubusercontent.com/9893266/167031254-5cd8a87a-40ba-4e2f-b644-07bb4bbb3c96.png)

Leaving and rejoining the world seems to increase the "total" number.
