### ISSUE TITLE
[Suggestion] Dimension blacklist/whitelist per vein

### ISSUE THREAD

**Issue by ChiefLogan3010** [oitsjustjose/Geolosys#31]
Hi, really enjoying the mod but just have one feature request that would help in the making of my pack, I'd like to be able to have some ores generate in certain dimensions, but not in others as a way of gating some resources behind advanced rocketry. This would be most helpful in creating custom entries. I'm aware that there's a blacklist for the entire generation, however there isn't one for each ore afaik.

**Comment by oitsjustjose** [comment]
So I'll be honest, I'm in a pickle here. 

I agree with the necessity for a feature like this, but at the same time I'm debating: 

a. If it's worth the hassle
b. If it's going to result in a ridiculously long config file.

I've been thinking, I might need to look into some better config options in the future. I was thinking something like combining ALL configs together, like IE does. It'd look like:

<pre>
"Coal" {
    64 <-- size (0 disables)
    8 <-- chance
    [ 1, -1 ] <-- dimension blacklist
}
</pre>
Of course, while this seems really easy to do on the *text* side of things, I'm concerned about how to outfit the "Mod Options" GUI config to use it.
