### ISSUE TITLE
[Feat] Improper ore-block replacement in vanilla veins

### ISSUE THREAD

**Issue by akkad-abraham** [oitsjustjose/Geolosys#310]
## Versions:

- Minecraft Forge: 40.1.0
- Geolosys: 7.0.7

## What happens:
Ore blocks in veins are being replaced with tuff in all kinds of veins (copper/iron).

## What should happen:
Ores in copper veins should be replaced with a more suitable stone-block (preferably minecraft:stone)
Ores in Iron veins should be replaced with deepslate

## Additional Comments:
The lack of an option to replace the vanilla ores with geolosys equivalent can also be addressed

**Comment by oitsjustjose** [comment]
Just built a new release and pushed it to Modrinth & Curseforge - should be publicly available soon! Thanks so much for the contribution :heart:
