### ISSUE TITLE
mekanism osmium

### ISSUE THREAD

**Issue by AmazigJj** [oitsjustjose/Geolosys#34]
osmium somehow?

**Comment by oitsjustjose** [comment]
Already implemented?

**Comment by AmazigJj** [comment]
In that case i am just an idiot, sorry

**Comment by oitsjustjose** [comment]
LOL no you're not - the documentation doesn't make mention of it yet (I just pushed a commit earlier that adds it).

If enabled in config, it drops from Platinum.
