### ISSUE TITLE
[1.12.2] [1.8.2] Disable osmium in config, still spawns / drops osmium.

### ISSUE THREAD

**Issue by codetaylor** [oitsjustjose/Geolosys#35]
MC: 1.12.2
Forge: 14.23.0.2550
Geolosys: 1.8.2

**What happens:**
When I disable osmium in the config, platinum ore still drops osmium clusters and samples on the surface still drop osmium.

**What I expect to happen:**
When I disable osmium in the config, platinum ore drops _only_ platinum cluster and the surface samples drop _only_ platinum.

**Notes:**
This is a great mod, I love it! Thank you for making it. :)

I believe that the issue of the ore dropping osmium even when it is disabled is because of this line [(BlockOre.java#L114)](https://github.com/oitsjustjose/Geolosys/blob/master/src/main/java/com/oitsjustjose/geolosys/blocks/BlockOre.java#L114). I believe that it should drop platinum here instead of osmium. I also notice that the switch in BlockSample#getDrops() method does not respect the config values in this case [(BlockSample.java#L194)](https://github.com/oitsjustjose/Geolosys/blob/master/src/main/java/com/oitsjustjose/geolosys/blocks/BlockSample.java#L194).

I would like to mention that this same issue exists for uranium and yellorium, and for similar reasons. I think that this line [(BlockOre.java#L135)](https://github.com/oitsjustjose/Geolosys/blob/master/src/main/java/com/oitsjustjose/geolosys/blocks/BlockOre.java#L135) should drop uranium instead of yellorium and, again, the switch in BlockSample#getDrops() doesn't respect the config values in this case [(BlockSample.java#L206)](https://github.com/oitsjustjose/Geolosys/blob/master/src/main/java/com/oitsjustjose/geolosys/blocks/BlockSample.java#L206).

I am happy to submit a PR to solve this issue, but I don't want to step on your toes and thought it would be a good idea if I talked to you first.

Thanks again! :)

**Comment by oitsjustjose** [comment]
Oops, I was "code drunk" at the time. That's what I get for coding for work _and_ three senior-level university classes *and* fun. :P

Fixing now!

**Comment by codetaylor** [comment]
Thanks! :)

Looks like the BlockSample will still drop osmium and yellorium regardless of the config setting though. (case 8 and 9 of the switch statement)

**Comment by oitsjustjose** [comment]
Right you are. Just changed around that mechanic.. I don't know why I was calculating them anyways
