### ISSUE TITLE
[Suggestion] Per ore biome black/whitelist

### ISSUE THREAD

**Issue by Jomik** [oitsjustjose/Geolosys#36]
It'd be nice if you could sort of specify in which biomes ores can and can't spawn.

**Comment by oitsjustjose** [comment]
Sounds like you’re looking for a lot more modularity than I am willing and able to support. I suggest using Geolosys to add the resources, then using CoFH world / Core for more specific world generation. You can use other mods (Content Tweaker I believe?) to modify the drops.

**Comment by Jomik** [comment]
@oitsjustjose Just so I avoid making a new one. I can't really achieve the same effect of spawning samples above the deposits with other mods.
Would it not be within the scope if this mod to add a biome list? Preferably weighted, but not necessary..?
