### ISSUE TITLE
Spawn Osmium without Platinum

### ISSUE THREAD

**Issue by Jomik** [oitsjustjose/Geolosys#39]
I don't have platinum in my modpack, thus I would like to simply have Osmium veins spawn, or at least have the platinum veins only drop osmium 👍

**Comment by oitsjustjose** [comment]
This is a totally reasonable request. I'll implement this soon!

**Comment by Jomik** [comment]
Amazing! I simply register platinum cluster as oreOsmium at the moment :p

**Comment by Jomik** [comment]
@oitsjustjose Can we get a release with this? It's been 21 days now :(

**Comment by oitsjustjose** [comment]
Soon. Just waiting for a Baryl texture from @wiiv and then we’re set for a release I’d say!
