### ISSUE TITLE
samples not always spawning

### ISSUE THREAD

**Issue by Zygus42** [oitsjustjose/Geolosys#4]
Geolosys-1.12-1.2-alpha
forge-1.12-14.21.1.2406-installer-win

I really like the new system by the way.   Are samples meant to spawn for every patch of minerals ?  Or is it intentional that some aren't ?

Tested with worldstripper.  Example:
seed:-279657698697289762
locs where there's ore but no samples:
     -460, 0
     -370, 50

**Comment by oitsjustjose** [comment]
It's intentional as a real-life feature (and to avoid potential surface spam of samples everywhere!) :)

**Comment by Zygus42** [comment]
Sorry to come back to this closed item, but would it be possible to have this as a setting in the config ?  For my new server world, I would quite like an item on the surface for each, but I can see that other people would want different amounts - so maybe a percentage chance from 0 to 100 ?

**Comment by Zygus42** [comment]
In fact, having done some more testing, I would quite like to see multiple samples for each node, so that they're a tad easier to find, as they're few and far between.  Still playing with the settings to see if I can get a bit more of the stuff happening.
