### ISSUE TITLE
Mekanism Digital Miner can't break Geolosys ores

### ISSUE THREAD

**Issue by Jomik** [oitsjustjose/Geolosys#40]
Full description is here: https://github.com/aidancbrady/Mekanism/issues/4841

**Comment by oitsjustjose** [comment]
Since it looks like The Digital Miner is having problems with *vanilla* ores even, I'm going to wait to do anything until a proper solution is implemented on Mekanism's end. Sorry for the inconvenience though D:

**Comment by Jomik** [comment]
Yeah, I saw that comment I posted there. Figured we'd keep it here for reference.
I had to add your blocks to ore dict to even detect them to begin with though :) Waiting for mekanism to fix

**Comment by Jomik** [comment]
Fixed in dev on Mekanism.

**Comment by oitsjustjose** [comment]
Great, thanks for the FYI :heart:
