### ISSUE TITLE
Feature Request: Silk Touch Iron Ore Veins for Vanilla Ore Block

### ISSUE THREAD

**Issue by Darkosto** [oitsjustjose/Geolosys#41]
Hey Jose!

Is it possible to allow the Iron Ore veins to drop the vanilla ore block when silk touched just like the other vanilla ores you have setup? I think gold ore doesn't allow this either.

Thank you :) Have a great day!
Darkosto

**Comment by oitsjustjose** [comment]
Gold ore don't allow this for some reason.. and you're right about iron - they were the only ones I *didn't* do it for because I never thought someone'd need it. But sure, I can do it!
