### ISSUE TITLE
Titanium/Rutile

### ISSUE THREAD

**Issue by Jomik** [oitsjustjose/Geolosys#42]
I decided to add Advanced Rocketry to my pack, and it uses Titanium, which comes from Rutile.
Is there a chance that you would add support for this? 😄 To begin with, I believe I will just make a custom gen using your config, but it would be awesome to get the proper looking sample, etc.

**Comment by oitsjustjose** [comment]
I don't plan on adding a Geolosys variant for every single ore someone adds, like ruby, vanilla emerald, rutile, sapphire, tungsten, etc. Some of them just *happen* to fit into another ore (like Yellorium and Osmium) so I had no valid argument as to why not. For those that don't fit in, that was part of why I worked so hard on the custom entries feature. 

If you're concerned about making a sample for your custom entries, I'd suggest something like [ContentTweaker](https://minecraft.curseforge.com/projects/contenttweaker) and use chisels n bits to create the model (like I did).

**Comment by Jomik** [comment]
That is perfect. I didn't think I could create a sample model with CnB

**Comment by oitsjustjose** [comment]
Yup, just create the model, hold it in your hand and type `/c&b.exportmodel` into chat :)

I did this because modelling with programs is **not** my forte, and it feels more minecraft-esque when done with C&B anyways :)

**Comment by Jomik** [comment]
Hehe! And licenses actually allow me to steal your sample.json model, and the texture from AdvRocketry, so it's perfect! 😄  Good job on the custom entry system! :D
