### ISSUE TITLE
Config resets

### ISSUE THREAD

**Issue by RiverC** [oitsjustjose/Geolosys#43]
I've noticed sometimes my configuration file resets to defaults, in at least one case I'm sure it is because I made changes that invalidated the config. However, this was confusing to me because the changes I made to custom rocks and ores seemed like they simply didn't work; the failure appears to be silent. 

When developing changes it'd be nice if the loading crashed with an error when the config is bad, instead of resetting its contents. I know resetting the contents is more robust in terms of failures.

This is sort of an open-ended issue, I don't really know what the best behavior for this issue is according to your specifications, it's simply that I would lose all of my changes. At first I thought I was losing my mind :)

**Comment by oitsjustjose** [comment]
This is odd behavior, as I never *weote* it to reset the config. I do know this: Forge will reset it if you mess up the syntax **anywhere**, silently. Sounds like you might be having that issue?

**Comment by RiverC** [comment]
Unsure. It does happen, and I end up with defaults and lose all of my tweaks. Could we at least get a prominent warning somewhere about this? (I'm using 1.12)

**Comment by oitsjustjose** [comment]
No unfortunately I can’t. That’s something that Forgebdoes and is completely out of my control. Best I can suggest is to use the Mod Options GUI in-game.

**Comment by RiverC** [comment]
Question: is the config loaded on game-load, or on loading/creating a new world? That could help me a bit too
