### ISSUE TITLE
[Feature Request] Emerald Ore Compat

### ISSUE THREAD

**Issue by Darkosto** [oitsjustjose/Geolosys#44]
Hey Jose, 

Would you consider adding support for Emerald Ore? I really enjoy the Geolosys veins and would love to convert emerald over. I would use the custom generation but I don't have an emerald ore sample.

Thanks and hope you had a great weekend! :D 
Darkosto

**Comment by oitsjustjose** [comment]
Yup, been dodging this but I really need to do it, so I'm on it!

Asked Wiiv to make a texture; soon as he has, it'll be all done!

**Comment by Darkosto** [comment]
Thank you very much :)

**Comment by oitsjustjose** [comment]
Done! 1.8.4 is out :D
