### ISSUE TITLE
Disable nickel

### ISSUE THREAD

**Issue by Jomik** [oitsjustjose/Geolosys#46]
I would like to be able to disable Nickel drops from Limonite, so I can use it purely as a larger source of iron. 👍

**Comment by oitsjustjose** [comment]
Just disable limonite and increase hematite, the result is the same.

**Comment by Jomik** [comment]
Aren't they generated at two separate heights and separate sizes?
It follows the logic from copper and tin deposits too then. Hmm 😢

**Comment by oitsjustjose** [comment]
If you don’t have nickel in your pack it sounds like you don’t really need azurite or Teallite either; sounds small enough that you can make do with only having one variant of mineral per ingot.

**Comment by Jomik** [comment]
Will you accept a PR?
And not having variants at different heights would leave the underground quite bare.

**Comment by oitsjustjose** [comment]
> Will you accept a PR?

Not really. The reason I'm opposed to your idea is because it *Geologically* does not make sense, not because I'm too lazy or because it's hard to do.

> And not having variants at different heights would leave the underground quite bare.

If you properly modify the configs, then it wouldn't; just ramp up the deposit sizes and you'd see it fill out the gaps :)

**Comment by Jomik** [comment]
Oh fair enough. I will play around with it. What mods use nickel?

**Comment by oitsjustjose** [comment]
Most popularly, the CoFH mods (like Thermal Expansion) and Immersive Engineering.

**Comment by Jomik** [comment]
Oh, I may reconsider IE. Thanks again! :)

**Comment by oitsjustjose** [comment]
Also, [there is this](https://minecraft.curseforge.com/projects/block-drops-tweaker) :)
