### ISSUE TITLE
Minor things

### ISSUE THREAD

**Issue by RiverC** [oitsjustjose/Geolosys#48]
1. I have trouble determining the difference between tealite and cassiterite. Most ores of the same mineral look different enough that you can tell if it is the deep or shallow one from the sample color, but with tin it's very difficult. Cassiterite is sometimes called "wood tin" because of its veins like the inside of wood, perhaps exaggerating its brownness, especially in the sample, might make it a bit easier.

2. I've adjusted sample numbers to make iron more findable (first map took me several hours flying around in creative to locate a vein) but the result is all ores have more samples. To put into perspective that same map I found diamonds on the island I started on, and with the increased sample size it was enough diamonds to immediately make a diamond pick. Probably there should be a variable sample count based on the mineral type; whether it's specific to the ore or varies based on the depth is up to you, but given the number of diamonds I usually need it was much easier to just wander around and get diamonds from kimberlite samples than to mine them.

**Comment by oitsjustjose** [comment]
Thanks for the input, I really appreciate it!

> 1. ...

I see your point here. I've tweaked @wiiv's texture (same texture, just some brown):

![image](https://user-images.githubusercontent.com/3887324/34463709-b80f6f64-ee32-11e7-8ac8-d167a4dd00e0.png)

I'll be honest, I'm not crazy for it. I don't know. 

> 2. ...

You've got a few options for this actually:

> "first map took me several hours flying around in creative to locate a vein"

You can always increase the world generation of Hematite / Limonite. 

> "increased sample size it was enough diamonds to immediately make a diamond pick"

You could've enabled the `samples drop nothing` config. That being said, I kind of like the variable sample count idea; I might come up with an algorithm for that (larger vein size = more samples).

I'll keep you updated with these ideas!

**Comment by RiverC** [comment]
Thinking of how it was implemented in TFC, the samples dropping some actual ore was the only way to actually *get* a pick! 

As for cassiterite, it's not so much the texture of the _ore_ as it is the texture of the _sample_! The sample is what confuses me, and since both give you 'tin cluster' when you pick them up, I'm never truly sure if it was tealite or cassiterite until I mine down. Whereas with copper and iron I can easily rule out the other type. 

Edit: one other thing I noticed that you may wish to address. I found that samples generate on top of frozen ocean. While it's fun hunting ore on the frozen sea, maybe this wasn't entirely intended!

**Comment by oitsjustjose** [comment]
Fair enough about TFC samples I suppose. After playing with it a lot on my server, I agree that Iron is far too rare. I'll be bumping up Hematite's default generation rate in the next release (today, probably.

The samples currently all rely on their ore deposit's texture. That can change easily, and it would mean cassiterite mineral blocks would look the same, but the sample would look like:

![image](https://user-images.githubusercontent.com/3887324/34463872-232f6754-ee38-11e7-86b8-c55420941fd0.png)

**Comment by RiverC** [comment]
Oh, yes. That is very clear now!

**Comment by oitsjustjose** [comment]
Cool. I've re-worked some of the ore-gen balance too; this should make finding Hematite more reasonable. 

Working on new sample code now.

**Comment by oitsjustjose** [comment]
I'm liking this new sample generation a lot:

![image](https://user-images.githubusercontent.com/3887324/34464044-4dd7174e-ee3e-11e7-85c9-5fc9bf9c1cd9.png)


(Pictured: Teallite and Cinnabar; both mineral deposits are very large)
