### ISSUE TITLE
Config spawning chances not right

### ISSUE THREAD

**Issue by Zygus42** [oitsjustjose/Geolosys#5]
Geolosys-1.12-1.2-alpha
forge-1.12-14.21.1.2406-installer-win

I was trying to adjust the values of the spawning in my test world, and something just wasn't right, so I reset it all and just focused on the Hematite.  I only changed the line:
I:"Hematite Pluton Chance Per Chunk"=
at 1 I wasn't able to find any, which is fair enough.  At 100, I was getting maybe 1 Pluton/Vein per 50 or so chunks.  Certainly nowhere near the 1 Pluton/Vein per chunk that a 100% chance should have given me.

**Comment by oitsjustjose** [comment]
Oops, I need to remove these configs as they're no longer valid since I made the change that only one vein spawns per chunk. And no - I won't make that configurable, that's simply a mechanic of the mod that is how I plan to keep it.

I'll be removing the unused configs now though :)

**Comment by Zygus42** [comment]
Thing is that I'm not getting 1 vein per chunk - i'm getting maybe 1 vein of something per 100 chunks.  No way are people going to get enough iron to play the game that way.

**Comment by oitsjustjose** [comment]
I've actually been testing in my modpack for my server and I definitely have enough iron. I had to run 157 blocks from home to get it, but I did :)

You're not *guaranteed* exactly 1 vein per chunk. It's all based on chance.

**Comment by Zygus42** [comment]
![2017-07-20_00 57 29](https://user-images.githubusercontent.com/20757445/28379725-46e217f0-6ce7-11e7-9d3b-6c70806cf5d6.png)


This is a picture of a 14 chunk x 17 chunk hole I dug with Minestripper.  That's 238 chunks or 60,928 blocks.  It has 6 nodes in it all up, 2 of which contain iron, and only 1 of which had a sample on the surface.  Ie. 1 in 40 chunks has a node.  

By the time one of the players on my server manages that 60,000 to 1 shot of finding the sample, I will long ago have expired from all the complaining.  

So, while this mod was sounding pretty good for us, I guess we're going back to funores with the biome specific spawning I worked out for our last server world.
