### ISSUE TITLE
gunpowder

### ISSUE THREAD

**Issue by AlexRover** [oitsjustjose/Geolosys#50]
Hello, do not you have plans to add sulfur and nitrate as in TFC for the preparation of gunpowder? And any plans for development in general?) Thank you in advance

**Comment by oitsjustjose** [comment]
> Hello, do not you have plans to add sulfur and nitrate as in TFC for the preparation of gunpowder?

I like the idea of adding sulfur if it is already available from another mod, but I will probably not add nitrate. I haven't seen any mods aside from TFC utilize it.

> And any plans for development in general?

I assume you meant this to mean "did I have any plans as to what I'm doing next" and not "did I plan to update the mod, ever". 

I can't say that I do. I find myself very happy with where it is currently, and don't know that I really need to make any major changes.

**Comment by AlexRover** [comment]
There are nail-making fashion models, for example Dark Roleplay Medieval, but even the presence of sulfur and saltpeter allows the authors of the assemblies to add a real gunpowder recipe

**Comment by oitsjustjose** [comment]
Working on sulfur now; I don't believe I'll be adding anything beyond that though. Thanks for the suggestions!
