### ISSUE TITLE
[Request] Allow ore veins to spawn in other blocks than stone

### ISSUE THREAD

**Issue by SeriousCreeper** [oitsjustjose/Geolosys#52]
Heya,

i might be wrong, but from what i experience (and checked in code), the ore veins currently only replace "Blocks.Stone", correct?

If so, would it be possible to get a config option to allow other blocks as well? Most of my underground is currently made out of Deep Stone from Minestrappolation 5, so i don't really find any geolosys ore veisn in the world. 

An option to allow a custom minX/minY for veins would be super useful as well, especially for modpack creators (which is what i'm doing currently). 

Cheers,
SC

**Comment by oitsjustjose** [comment]
Sure, I can do that :)

**Comment by SeriousCreeper** [comment]
Really appreciate that, thanks a bunch! :D
