### ISSUE TITLE
[Request] JourneyMap Integration

### ISSUE THREAD

**Issue by dncspurs** [oitsjustjose/Geolosys#53]
A JourneyMap plugin that lets you shift+right click a sample to add a waypoint to JourneyMap automatically.

https://bitbucket.org/TeamJM/journeymap-api

**Comment by oitsjustjose** [comment]
I love this idea. I’ll work on it soon!

**Comment by oitsjustjose** [comment]
Done! Sneak right clicking a sample will mark it with a proper name :)
