### ISSUE TITLE
Feature Request: Allow Osmium To Have Its Own Vein

### ISSUE THREAD

**Issue by Darkosto** [oitsjustjose/Geolosys#54]
Heya Jose!

Is it possible to have a config option to split Osmium into its own vein/sample? It would make things a little on my end and trying to separate platinum and osmium.

Thank you!
Darkosto

**Comment by oitsjustjose** [comment]
🤔 

I can look into it, might I ask why? I'm only bothered by it since it's not completely geologically accurate D:

**Comment by Darkosto** [comment]
Absolutely!

This is strictly for gameplay/progression reasons in my pack. I have ores unlock over the course of the modpack and Platinum actually unlocks 2 full stages before Osmium. Since having both in the same vein would give the player the osmium ahead of time it wouldn't be conducive for them to share in my unique situation. That's mainly why I had asked if you would consider a config option since by default you can keep them combined :)

Hopefully that's a bit more helpful! Thank you :D

**Comment by justinrusso** [comment]
If you're torn on this, what about just adding a config to disable the osmium? Osmium ore can be added as a custom ore entry

**Comment by oitsjustjose** [comment]
There is already, I'm just torn because while I see the point Darkosto is making, I don't know how I feel about making a pretty major geological inaccuracy for it..

**Comment by Darkosto** [comment]
No problem then! Would you mind if I make a change myself and that way Geolosys can maintain its integrity?

**Comment by oitsjustjose** [comment]
Like your own branch? Or.... I could make you a branch? :)

**Comment by Darkosto** [comment]
Actually, I could use a mod designed to create custom blocks and use a custom ore vein entry. You wouldn't have to add anything extra :)
