### ISSUE TITLE
feature request:  iridium,ruby,sapphire, and titanium support

### ISSUE THREAD

**Issue by robjw95** [oitsjustjose/Geolosys#55]
Great mod but would it be possible to add iridium as a rare drop of platinum?  Add Corundum for rubies, sapphires and maybe titanium as rare drop?  This would allow more mods to be covered like tech reborn easier.

**Comment by oitsjustjose** [comment]
I'll think on it. I'm not opposed, but I don't know how much work I want to force @wiiv to deal with 😛

**Comment by deveyus** [comment]
Just want to add to desire for Titanium, (Rutile) ore being adds being nice!  Also if we could get sources for Thorium, Boron, Lithium and Magnesium, that'd be awesome.

**Comment by oitsjustjose** [comment]
I think when dealing with this many random one-off resources that are used by only one or two mods, I'll leave it to the user to create a custom ore entry. Thanks for the input though!
