### ISSUE TITLE
Request: Add ingots for metal alloys, as well as blocks and nuggets

### ISSUE THREAD

**Issue by WrongWeekend** [oitsjustjose/Geolosys#56]
This mod works well with Tinker's Construct and other, smaller mods because of the way ore is spawned, making players go out to search for and collect rarer mineral resources with different properties. It also adds ores no longer in TiC without adding a bulk of other content like Thermal Foundation or IndustrialCraft (armors, mobs, energy, machines, etc) so other aspects of gameplay are not changed.

The mod offers ingots for pure metals, so copper, silver, tin, aluminum, and lead are usable. But alloy ingots made from the metals are not present (specifically bronze, electrum, invar, brass, and constantan) so they cannot be alloyed in TiC without addition of one of the above mentioned bigger mods. Blocks and nuggets for each metal would be useful as well, but not wholly necessary.

**Comment by jena-th** [comment]
imho It's not the goal of this mod

**Comment by oitsjustjose** [comment]
Agreed. I don't think I'll be adding these things - I hate redundant metals in a modpack (hence the `enableIngots` option). I feel as though that's the exact purpose of ThermalFoundation though!
