### ISSUE TITLE
Small issue with slow oregen

### ISSUE THREAD

**Issue by Lucasterio** [oitsjustjose/Geolosys#58]
This is a small issue. When using a big modpack, using the mod "World Profiler" by far the biggest contributor to chunk terrain generation delay was this mod (which i love <3).

By comparison, Rockhounding mod, adding about 10 different kinds of stone per separate biome, took usually 1/5 of the time.

Please take a look, for us big modpackers.

Thanks

**Comment by oitsjustjose** [comment]
I'll try to improve, but when you say "this is a small issue" it isn't at all. I know how I can improve the performance, but it leads to a pretty big change to the mechanics of the game itself.

I'll see what I can do.

**Comment by oitsjustjose** [comment]
[This commit](https://github.com/oitsjustjose/Geolosys/commit/d544630cc19eda13ec7866f4a566493f5af62c74) fixes the cascading ore generation issue some (not completely, but rather a lot). This is the best I can do without either:

a. A complete re-write of the generation system
b. Compromising the base mechanics of Geolosys

I haven't checked with WorldProfiler, but this commit did drastically reduce the number of cascading world gen warnings in the console.

**Comment by Lucasterio** [comment]
Oh I totally meant "small issue" in that it isn't a bug or a problem, its just that when I put several worldgenning mods together my modpack started to lag, and that made me sad :_(
