### ISSUE TITLE
[Feature request] Dimensional blacklisting for custom ores 

### ISSUE THREAD

**Issue by Saereth** [oitsjustjose/Geolosys#62]
being able to add custom ores into the generation is nice but having control over what dimensions those also spawn in as with the dimension list in the ore json file would be more ideal. Any chance of getting this functionality in the future or does it exist in some fashion and I've overlooked it?

**Comment by oitsjustjose** [comment]
This functionality doesn't exist but I'm not sure I'm going to be doing all of that. It would require a pretty big overhaul.

Maybe in the future I'll change the custom stone and ore entries to a JSON Format that I parse, but that'll be a ton of work.
