### ISSUE TITLE
[Bug] Ores will not spawn in the Nether with appropriate settings.

### ISSUE THREAD

**Issue by Rosethorns** [oitsjustjose/Geolosys#65]
Minecraft: 1.12.2
Forge: 14.23.2.2613
Geolosys: 1.8.5

Description:
Geolosys Ore Veins will not spawn in the nether despite taking appropriate steps to ensure that they will.

Steps to reproduce:
1. Remove -1 (The nether) from the dimension blacklist of appropriate ores in the geolosys_ores.json
Example:
![image](https://user-images.githubusercontent.com/2171914/36584368-4a5ca910-18de-11e8-99bf-4eee04c78be4.png)

2. Add any valid blocks that you want the ores to spawn in to the S:"Blocks mineral deposits can replace"  list.
![image](https://user-images.githubusercontent.com/2171914/36584412-779774d2-18de-11e8-928f-ada3500e44f7.png)

3. Create a new world with a new Nether or spawn new chunks in the nether

What should happen:
Ores in the geolosys_ores.json not black listed from the nether should spawn in the materials added to the replaceable list (I.E Netherrack)

**Comment by oitsjustjose** [comment]
Pretty sure it's [this line](https://github.com/oitsjustjose/Geolosys/blob/master/src/main/java/com/oitsjustjose/geolosys/world/OreGenerator.java#L35) that I wrote long before I ever offered a dimension blacklist config. I'm going to test later (at work now, can't have someone seeing me playing Minecraft) and then I'll be able to confirm!

**Comment by oitsjustjose** [comment]
Confirmed fixed:

![2018-02-23_12 08 44](https://user-images.githubusercontent.com/3887324/36606649-5d652e34-1892-11e8-9d3d-e1ff8a52f698.png)

**Comment by oitsjustjose** [comment]
I've [pushed an update](https://minecraft.curseforge.com/projects/geolosys/files/2534315) that fixes this bug and includes the new IE compat layer :)
