### ISSUE TITLE
[Feature Request] Configurable search range for Prospecting Pick

### ISSUE THREAD

**Issue by Luke616** [oitsjustjose/Geolosys#67]
Title, in my opinion the search range of the pick is a bit short, and I would love to be able to configure it. I believe the current search range is 6 blocks in the direction you are looking, and 3 blocks up/down?

Fantastic mod by the way, really brilliant stuff. Always enjoyed the prospecting aspect of TFC and wished I could have something similar in other modpacks. Thank you for this.

**Comment by oitsjustjose** [comment]
Implemented in 1.8.7 :)

**Comment by Luke616** [comment]
Thank you very much!
