### ISSUE TITLE
[Suggestion] Default ore chance seems a little too rare

### ISSUE THREAD

**Issue by MechanosG** [oitsjustjose/Geolosys#68]
As the title says, default ore chance seems a little too rare.  I'm using the World Stripper mod to remove giant areas so I can get an idea of how often Geolosys ores are spawning compared to normal vanilla ore.  Doing so and removing a 6x6'ish chunk area at a time, I'm lucky to find 1 or 2 ore deposits.  I tested new areas about 15'ish times.  I feel that ideally the space apart should be low enough that players don't get frustrated when they mine out an entire mountain, which currently would result in only 1 or 2 ores.  I've had similar problems with gregtech oregen before, where players would need a specific resource type, but all progress ends up halted because RNG never spawns a vein.  This results in players leaving.

This gets worse if you're trying to find something like redstone and diamond.  Which until today, I had no idea was kimberlite and cinnabar.  I assume instead of random mining, you're supposed to travel the surface 'till you find samples of kimberlite and cinnabar, then dig out the ground underneath.  But I have never once seen those specific samples, and given how low the chance is for ore generation to begin with, I'm going to assume they must be very rare.

Another related issue, is custom ores.  Before some helpful Reddit gents told me about kimberlite and cinnabar, I was convinced my modpack was devoid of diamond and redstone.  So I tried to add both in as custom ores in Geolosys.  This worked and they spawned, but no matter how high I set the chance of spawning, they too were very rare as if the chance of spawning were capped, or some other mechanic prevents new ore with-in X distance of another vein.  Perhaps your Vanilla ore disabling is detecting most of the custom vanilla ore veins and turning them to stone?

Either way, in the mean time I'm going to experiment with greatly increasing the chances of veins and see how it goes.

**Comment by oitsjustjose** [comment]
I definitely agree that the default rarity for Kimberlite and Cinnabar are too rare (cinnabar especially), so I'll work to find a balance point for them.

As for rarity of any ore: **all mineral veins in this mod are limited to just one per chunk**. You'll never find the heart of more than one deposit in a chunk. If you're looking for large, less-sparse deposits then CoFH World might be more up your alley.

Thanks for the input!

**Comment by MechanosG** [comment]
That's interesting.  Even when I set the custom ores above 100% chance of spawning, most chunks were completely devoid of any Geolosys veins.

Assuming that was a fluke in custom ores, if I were to say..  set one of the default Geolosys ores chances to something really high..  would it end up preventing other ore types from spawning due to nearly every chunk choosing to take the high percentage one, and the one vein limit preventing the rest?  For example, if I set Cinnabar to 75%, would other ores only ever have a chance of spawning 25% of the time?  Or are all the percentages taken into consideration, so that even if Cinnabar had 100%, there's still a chance another ore will take the spot instead?

**Comment by oitsjustjose** [comment]
All the percentages taken into consideration. It's just somewhat of a weighted system. Things with higher percentages have a higher chance of being chosen, y'know? Not that they're always going to spawn in a chunk, but that they're more likely to.

The config is still being (forcefully) limited by my own generation code that I won't change.

**Comment by MechanosG** [comment]
I never insinuated that I wanted more than 1 vein per chunk.  I was simply asking because..  you mentioned that I should be able to get one vein per chunk, max.  And so far, it feels like I get 1 vein every 10'ish chunks, if that.  I wanted to fill some of those empty chunks with some Cinnabar and Kimberlite veins, and to do so, I need to understand what "chance" to give them, to make that happen.  I mean, I get it.  You want people to go hunting for ore.  Kinda the theme of the mod.  That's fine for some modpacks.  While it may not be intended usage, I personally find Geolosys as a nice addition to other mods that add ores.  Sort of a pleasant surprise to find a giant cloud of ore, or find samples leading you to a giant cloud, instead of relying 100% on said clouds.  Not to mention the TFC/GT style ore names is nice.

Either way, the pack I'm building requires a lot of mining resources.  I have other mods that supplement ore here and there so that players won't be starving out while looking for Geolosys' veins.  But they happen to not add anything redstone/diamond related.  And possibly gold.  So I apologize if I derailed my own suggestion, but that's my only reason for asking in my second post.  I'm trying to make Geolosys "fit" instead of jumping ship to a likely laggier oregen mod.

**Comment by oitsjustjose** [comment]
Ah, no worries at all! I'm glad that someone else felt the same way about the default generation rates though!!
