### ISSUE TITLE
I think you broke nether spawning again

### ISSUE THREAD

**Issue by Rosethorns** [oitsjustjose/Geolosys#69]
Sorry for the casual title I just thought I would try and make you smile with a bug before I go to bed :P 

Here is my geolosys_ores.json https://pastebin.com/HJZpRZHC

No ores for as far as the eye can see (and the searching not pictured :P )

![image](https://user-images.githubusercontent.com/2171914/37253754-b214b584-259a-11e8-83b5-2c08be58ef61.png)

Really excited about the height options though :D

Edit: I refreshed both configs before testing this.

**Comment by oitsjustjose** [comment]
aaaaaaaaarghhhhh so, I genuinely don't know what happened but at some point several commits got undone...

My changelog was out of date, and the hard coded nether and end blacklist returned >_>

Fixing (**again**) now. Sorry :|

**Comment by oitsjustjose** [comment]
[Soon](https://minecraft.curseforge.com/projects/geolosys/files/2540031)™️
