### ISSUE TITLE
Cannot find anything

### ISSUE THREAD

**Issue by TheLimePixel** [oitsjustjose/Geolosys#7]
So I simply cannot find anything. I first tried it in a custom mod pack with BoP generation, then in a default world and then just the mod with Hwyla. I've covered around a hundred chunks in all those world in spectator mode and I haven't found anything. I didn't try World Stripper, but I'm sure that I would have found something by now just by being in spectator mode with Hwyla. It's quite strange when by the looks of it, it works fine for others in the GitHub.

**Comment by oitsjustjose** [comment]
Spectator mode + Hwyla is not a good way of trying to find these ores. Spectator mode will show you caves, but the odds that a cave spawns in the same place as a mineral deposit is very low. Without an adjacent open air space, you won't *see* anything by flying through the underground with Hwyla. 

Give CoFH core a try, using this command - you'll find it.

`/cofh clearblocks @p 128 256 128 stone gravel lava water grass dirt sand sandstone log leaves log2 leaves2`
