### ISSUE TITLE
[1.8.8] World creation doesn't work

### ISSUE THREAD

**Issue by Naxdar** [oitsjustjose/Geolosys#71]
World creation is hanging forever under the 1.8.8 version, last message in the console is :
[Server thread/INFO]: Preparing spawn area: 8%

Tested with no other mod.

**Comment by oitsjustjose** [comment]
Can I get a full crash report / log please? 

I've tested this on 1.8.8 an everything's working for me..

**Comment by Naxdar** [comment]
I found the problem after more testing, the old geolosys_ores.json file doesn't get automatically updated with the newest ores and must cause other problems down the line.

**Comment by oitsjustjose** [comment]
Ok! I'd still like a log, if possible - I've actually added a feature to fill in missing entries from the geolosys_ores.json file, so if it crashed it could've been that my fall-back code crashed...

**Comment by Naxdar** [comment]
There wasn't a crash, the game just freezed indefinitely.
Here is the full log up until the freeze during world generation :
[fml-client-latest.log](https://github.com/oitsjustjose/Geolosys/files/1800960/fml-client-latest.log)

**Comment by oitsjustjose** [comment]
Just uploaded 1.8.8b to CurseForge; it makes sure that if you don't have an entry, it gets added for you :)

**Comment by majijn** [comment]
world gen still isnt working even in 1.8.8b with old manual configs, I guess ill have to copy my settings onto the new format and see if it works then =/

if I try to generate new chunks in an old world it just... stalls, and leavign the world crashes java (so i dont get a crashlog, rip)
