### ISSUE TITLE
Geolosys preventing worlds from loading when ores are disabled in geolosys_ores.json

### ISSUE THREAD

**Issue by Luke616** [oitsjustjose/Geolosys#73]
In geolosys 1.8.7, I had disabled autunite and sphalerite, as my pack did not contain uses for zinc or yellorium. The way I had disabled these was by setting "autuniteSize" and "autuniteChance" (and sphalerite) both to 0. However, when doing the same in geolosys 1.8.8 and 1.8.8b, new worlds get stuck trying to generate on load. When removing these changes from the config, worlds load just fine.

[Here](https://minecraft.curseforge.com/projects/magiculture-2/files/2541517) is a link to the version of my modpack in which this issue occured, if you are having trouble replicating it yourself. No crash occurs, so unfortunately I don't have a crashlog for you.

Geolosys 1.8.8b
Forge 14.23.2.2624
Minecraft 1.12.2

Thanks!
Luke616

**Comment by oitsjustjose** [comment]
Thanks for including the pack configs! I think I *might* have figured it out...?

Does [this build](https://puu.sh/zIEWu/24b8965cf1.jar) work for you? I used your configs and it worked for me every time.

**Comment by Luke616** [comment]
That build seems to work great - thanks for the quick fix!

**Comment by oitsjustjose** [comment]
Cool! Thanks a lot, I've had this reported one other time and the solution that closed it wasn't satisfactory for me...

It'll be live [here](https://minecraft.curseforge.com/projects/geolosys/files/2541652) Soon™️
