### ISSUE TITLE
Can we Configure Value of 'Chance to gen' between 0 and 1?

### ISSUE THREAD

**Issue by MinerTomotomo** [oitsjustjose/Geolosys#74]
(I'm not good at English, sorry)
Please tell me how to configure very small size the value of 'Chance to gen'.
I want to configure Platinum's chance to gen "0.03".

**Comment by oitsjustjose** [comment]
Your English was fine!

I don't think I'll be adding this.. it'll require re-writing most of the ore generation system to accept float chances.... and I think that even "1" is ludicrously rare.

**Comment by MinerTomotomo** [comment]
thx :D
