### ISSUE TITLE
vanilla ores dont spawn

### ISSUE THREAD

**Issue by CharCharthemonkey** [oitsjustjose/Geolosys#75]
not sure if its a bug or not but the vanilla ores do not spawn at all or maybe spawn 1-2 ores per like 16x16 chunk is that intended or no? if yes then how to off set the ore requirements?

**Comment by oitsjustjose** [comment]
By "vanilla ore" do you mean the ones added by Geolosys (like Geolosys's Gold)?

Regardless, if you're talking about vanilla Minecraft ores, then this mod doesn't do what you might think it does.... vanilla Minecraft ores are disabled and replaced with mine. And if you're talking about Geolosys's vanilla ore variants, then the `geolosys_ores.json` file allows you to let more or less of my ores spawn..

**Comment by CharCharthemonkey** [comment]
the surface ones spawn yes but i literally dug down in a 32x32 area for where the ore was "supposed" to spawn and neither the normal vanilla ores nor anything but stone or modded ores spawned @oitsjustjose
