### ISSUE TITLE
sort of an addon to #75 

### ISSUE THREAD

**Issue by CharCharthemonkey** [oitsjustjose/Geolosys#76]
according to the geolosys json file the vanilla ores are "supposed" to spawn but they dont tho the surface marker things do spawn so wat am i missing? pretty plz

**Comment by CharCharthemonkey** [comment]
also if needed i can send u the pack im making with the mod to show that they are supposed to spawn but arent

**Comment by oitsjustjose** [comment]
I don't think you understand at all. 

No. 

The `geolosys_ores.json` file **only** has to do with ores that **my** mod creates. **Not Vanilla**. So if you see something in the `geolosys_ores.json` file that has the same name as vanilla, it's **not the vanilla version**. 

I hope this clears everything up for you.

**Comment by CharCharthemonkey** [comment]
i get that and the geolosys_ores.json file says the ores are supposed to spawn but they dont even spawn though the surface samples say they do sry if im being odd but im trying to figure out how to make the ores spawn like in sevtech ages but not nessecarily the exact same just in decent quantities

**Comment by oitsjustjose** [comment]
SevTech: Ages is now out, so I'm closing this on the basis that you can just go and look for yourself 🙂
