### ISSUE TITLE
NBT crash

### ISSUE THREAD

**Issue by CharCharthemonkey** [oitsjustjose/Geolosys#77]
Geolosys caused a massive NBT error crash with minecolonies 
[crash-2018-03-24_17.48.39-server.txt](https://github.com/oitsjustjose/Geolosys/files/1844915/crash-2018-03-24_17.48.39-server.txt)

**Comment by oitsjustjose** [comment]
Absolutely nowhere in this crash report is mention of my mod. Sorry.
