### ISSUE TITLE
Misisng config settings

### ISSUE THREAD

**Issue by Zygus42** [oitsjustjose/Geolosys#8]
Shouldn't there be entries in the config for:
              Coal
              Cinnabar
              Gold
              Lapis Lazuli
              Assorted Quartz
              Diamond
so that the size and gen chances of the clusters can be set ?

**Comment by oitsjustjose** [comment]
I hadn't planned on this since the vanilla ores are (unless in customized worldtype) not configurable anyways, but I can if you'd use that.

**Comment by Zygus42** [comment]
I think anyone using this mod wants to have as much control over the way ore spawns in their world as possible.  I certainly would use it - I'm aiming for smaller chunks but more of them.

I haven't tried using the "User Entries" section, but was thinking that maybe I could input the blocks listed above in that section ?  Have to give it a go.

**Comment by oitsjustjose** [comment]
Fixed in 1.4
