### ISSUE TITLE
[1.8.8c] Ore mining delay on servers 

### ISSUE THREAD

**Issue by primetoxinz** [oitsjustjose/Geolosys#82]
Geolosys ores have an odd delay when being mined on servers.(note: I also tried with a pickaxe, not just a TiC hammer and it still hapens)
In the clip below you see that normal blocks breakin instantly, but the Geolosys ore takes a couple extra seconds to disappear and drop.
I tried to reproduce it on SSP to no avail, so it is likely due to some network lag of some sort. 
[Clip to show it off](https://streamable.com/kpyw0)

**Comment by oitsjustjose** [comment]
How odd. This is legitimately confusing. I'll test it some on my own time when I can, but I don't know. Have you tried on different servers?

**Comment by primetoxinz** [comment]
I'll give it a try on a local server

**Comment by oitsjustjose** [comment]
Thanks! I'm just curious if it's network lag or that somehow my drop code is *that* complex... but I'm 90% sure it's not... I don't do any real trickery that I know of.

**Comment by primetoxinz** [comment]
Yeah, I checked the code to see what could be taking a while and nothing jumps out at me. I'll see what I can find.

**Comment by primetoxinz** [comment]
Ok, I can confirm this does not happen on a locally hosted server or singleplayer. I'm wondering if it has anything to do with other mods in SevTech

**Comment by oitsjustjose** [comment]
Unable to reproduce on my own SevTech 3.0.1 Server (4gb min, 6gb max ram) on a Mac Mini dedicated server:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/-rDTVtpMSuc/0.jpg)](https://www.youtube.com/watch?v=-rDTVtpMSuc)

**Comment by primetoxinz** [comment]
Weird, I'll try to get more information if it happens for me again.

**Comment by oitsjustjose** [comment]
Thanks!! And I believe that the issue exists, just don't know what I can really do about it if it's just TPS lag D:

**Comment by Electrofried** [comment]
Even with our servers running at 20 tps we get this issue. There is some sort of "processing" delay that looks much like the block breaking lag you get from low tps. Most notable when using something like a tinkers hammer to mine multiple blocks. I don't think it is TPS related as close inspection of server tps shows no deviation during the event. Perhaps it is something related to the block break event or item generation?

**Comment by oitsjustjose** [comment]
I honestly can't figure out what it'd be then. I've not experienced this issue on an underwhelming (yet capable) Mac Mini Server that's hosting the pack... 1.8.9c has helped reduce registry look-ups immensely, so maybe that'll help? I don't really know honestly.

**Comment by OldManCraft** [comment]
Latest version is doing it bad 1.8.10.c. The block lag feeling is only on Geolosys ores. Yes this is on a servers with forge 2651 SevTech 3.0.5

**Comment by oitsjustjose** [comment]
Then it’s 100% not me. Because I changed absolutely nothing in that class between 1.8.9 and 1.8.10

**Comment by danielmarkavis** [comment]
Currently was using 1.8.10.c Sevtech 3.0.4 and coal is taking a while to drop after breaking.

Updating to SevTech 3.0.6 (and server 3.0.5, with adding Environmental Tech 2.0.9c), seems to have fixed the issue (with coal).

Client might need updating to forge 14-23-2-2654.

**Comment by tiwuno** [comment]
After further testing, it seems to be an issue only related to the current age in Sevtech Ages. I.e. coal, tin, and copper lag in Age 1 but not Age 2. iron and lapis lag in Age 2 but not Age 3, etc.

Not sure what method the modpack developer is using to gate ores, but it definitely seems to be related to that.

**Comment by garyoneillj** [comment]
Just wanted to mention that this is still a big issue for me, playing on a locally hosted server.  I simply can't use tinkers' tools because although the animation plays to break blocks, they instantly re-appear (With a bronze hammer you even have enough time to re-break the 9 blocks, which instantly gives the ores).  After that delay if you just wait, the middle block of the 9 will break. 

I've also have the same issue using a normal pick (Ironwood) breaking just one block, it breaks, re-appears, and will break itself after a delay.  

Note, that if you replace the middle block with a cobblestone for example, then try to break it again, it works instantly with no delay and all 8 ores are broken.  This issue is even more prevalent with Coal it seems.

**Comment by oitsjustjose** [comment]
See: https://github.com/Darkosto/SevTech-Ages/issues/901#issuecomment-384151277
