### ISSUE TITLE
[Request] Configurable mining levels

### ISSUE THREAD

**Issue by ghost** [oitsjustjose/Geolosys#85]
If possible, could you add  an option to each entry in geolosys_ores.json to change the mining levels of the ores. That way we could change the progression to our needs. (e.g. I'm making a pack where I want to force people to make bronze tools first and then iron, so I want copper/tin to be level 1 and iron to be level 2) I could do this with another mod, but to keep the footprint small, it'd be nice if it could be done using a config setting.

**Comment by oitsjustjose** [comment]
There's already a ton of stuff going on in the `geolosys_ores` json as is, and there have already been complaints about it being to cluttered. I don't see a need to add another, and I don't particularly want to *encourage* people making Geolosys easier (but if they decided to add a mod, that's a different story). 

Sorry to make you add another mod, I prefer things that way too in my packs, but I just think this is for the better.

**Comment by ghost** [comment]
No problem. I thought no harm in asking. Another mod is not the end of the world :)
