### ISSUE TITLE
Silk Touching Limonite Ore Drops Vanilla Minecraft Ore

### ISSUE THREAD

**Issue by Vyraal1** [oitsjustjose/Geolosys#86]
https://github.com/Darkosto/SevTech-Ages/issues/1027

Reporting this also here, in fact I probably should've just reported it here in the first place.

**Comment by oitsjustjose** [comment]
I specifically implemented this feature *for* @Darkosto.

**Comment by darthvader45** [comment]
This is great for mods like Galacticraft, and that mod specifically requires ore blocks for the astro miner.  This makes it infinitely better.
