### ISSUE TITLE
Geolosys Ore Gen Funstuff

### ISSUE THREAD

**Issue by oitsjustjose** [oitsjustjose/Geolosys#87]
See [this](https://github.com/Darkosto/SevTech-Ages/issues/1026)

Likely fix: rewriting / refactoring generation code

**Comment by TexanMD** [comment]
I'm just looking at the source and don't have a way to test, but it looks like it is related to this line:
https://github.com/oitsjustjose/Geolosys/blob/c41a24983667dcc764a9b8b4af4cbffa22ec6ff3/src/main/java/com/oitsjustjose/geolosys/world/OreGenerator.java#L45

It looks like that is effectively attempting to generate 1 random ore for every chunk.  

With a large enough sample size should result in 1 / oreSpawnList.size() possible chunks for every ore, and then the number that actually have ore will be further reduced by the configured weight for each ore.

**Comment by oitsjustjose** [comment]
I’m actually happy with it behavior as of 1.8.10. Thanks though!!
