### ISSUE TITLE
[Suggestion] Adding option to retrogen

### ISSUE THREAD

**Issue by tjsd** [oitsjustjose/Geolosys#88]
Hello!
As you may know some people have oregen done by your mod in Sevtech modpack and there was some issues with how the ore was generated. Due to this many worlds now are not very playable without deleting chunks and using worldedit. I have seen other mods sometimes add the option to regen/retrogen their ores. Would this be possible to add to your mod?

**Comment by oitsjustjose** [comment]
I'd say yes, except it's not really - I can't *efficiently* scan the world for every *mod* and *vanilla* ore that needs to be removed and replaced with my ores, plus generate samples. There's not really an efficient way.
