### ISSUE TITLE
config Ore Cluster Sizes not correct

### ISSUE THREAD

**Issue by Zygus42** [oitsjustjose/Geolosys#9]
I set I:"Hematite Cluster Size"=48
and then mined a hematite pluton and got 260 odd bits of iron, 1 out of each block.  Is this the way it's meant to be ?

Other thing: It appears to be spawning a single Magma Block with Limonite and Azurite plutons.

**Comment by oitsjustjose** [comment]
Part 1: I'll look into it at some point (boy, you sure push a lot of issues...)

Part 2: Yes, that's intended. There's a [1% chance](https://github.com/oitsjustjose/Geolosys/blob/master/src/main/java/com/oitsjustjose/geolosys/world/WorldGenPluton.java#L85-L86) of a block in a pluton being a magma block if you're below Y=24. I had it as lava... not sure which I prefer. Magma would geologically makes sense (magma = molten earth beneath the surface) but I'm still debating if it minecraft-ically makes sense.

**Comment by Zygus42** [comment]
Consider if Beta-testing :)  I'm putting together our first 1.12 mod pack, and this am reporting many issues and/or suggestions to many mod makers :)

I think either is fine - kind of looked like it was something left over from testing :)

**Comment by oitsjustjose** [comment]
Tested out one last time just now; seems this is fixed.
