### ISSUE TITLE
IE Excavator Integration ignores Geolosys configs

### ISSUE THREAD

**Issue by justinrusso** [oitsjustjose/Geolosys#90]
Yellorium and Osmium are disabled from their respective ores, but I am still getting them from the excavator.

![image](https://user-images.githubusercontent.com/25138621/38158322-148a4d04-3460-11e8-958c-7e8a33b9e1f3.png)

**Comment by oitsjustjose** [comment]
This is odd, does the manual say it should be coming from Uranium / Platinum deposits, or is there a custom deposit coming from elsewhere?

**Comment by justinrusso** [comment]
Ive disabled all of our custom mineral veins and the book shows just one entry for platinum which is a geolosys chunk of both platinum and osmium at 50%

**Comment by oitsjustjose** [comment]
Alright, so in my dev-environment, this doesn't happen. This might be inter-mod.

**Comment by oitsjustjose** [comment]
The next update changes around the IE compat a little, but should fix this.
