### ISSUE TITLE
Assorted Quartz Does Not Drop Black, Certus, or Charged Certus Quartz any longer

### ISSUE THREAD

**Issue by justinrusso** [oitsjustjose/Geolosys#92]
I've created a test world with just Geolosys, AE, and AA and can confirm this is still an issue with just those mods.

Reference: https://github.com/Darkosto/SevTech-Ages/issues/1278

---
#### Versions:
Forge: 14.23.2.2641
Geolosys: 1.8.10b
Applied Energistics: rv5-stable-11
Actually Additions: 1.12.2-r133

**Comment by oitsjustjose** [comment]
This was already submitted to me via twitter and fixed in a recent commit.
