### ISSUE TITLE
Suggestion integration of Insane96 mod's ores as rare drops

### ISSUE THREAD

**Issue by alxcool** [oitsjustjose/Geolosys#93]
## Versions:

- Minecraft Forge: 2635 1.12.2
- Geolosys: 1.12.2 1.8.9c
- XaerosWorldMap_1.2.4_Forge_1.12
- ThermalExpansion-1.12.2-5.3.10.15-universal

...
Hi! I use to play soloplayer in a set of 135 mods and started including this one. This is a really amazing mod and I would like to suggest an addition to it.

What do you think about including, as rare drops, some items from the followings mods made by Insane96?
Carbonado
Galaxite
Vulcanite
Nethergoldore

I was reading the in-game documentation book and I was thinking that it may be cool to have an extra 1% drop chance of earning Carbonado as black diamond variant from (sorry forgot the name of the sample or ore who drop diamond.)

I hope you won't think as those ores as not realistic enough because the actual difficulty to mine a Carbonado gem make it really fun to obtain. Spawn in layer 2-5 and is quite rare.

**Comment by oitsjustjose** [comment]
> I hope you won't think as those ores as not realistic enough because the actual difficulty to mine a Carbonado gem make it really fun to obtain.

By "realistic" I mean ores that *actually* occur in real life. I think that none of these really meet that criteria, but you can always use the UserEntries section to add these.

**Comment by alxcool** [comment]
I've found some quite nice pictures :P. Let say that most famous world jewelry are given a name, but not all of them.
Here a Black diamond, like Carbonado
http://www.capetowndiamondmuseum.org/blog/2017/04/top-8-largest-diamonds-in-the-world/
Here all the color of quartz who remind me as Vulcanite / Galaxite. I was thinking that Quartz is the mining goal in the nether.
https://www.gemsociety.org/article/crystalline-quartz-buying-guide/

Note also that quartz is used as industrial sandblasting, and in a similar way to flint, could be used as fire stone!
