### ISSUE TITLE
Ore Gen

### ISSUE THREAD

**Issue by Ravin890** [oitsjustjose/Geolosys#96]
## Versions:

- Minecraft Forge: 14.23.2.2651
- Geolosys: 1.8.10c

## What happens:
Whenever you find any dust on the surface the easiest way to find the ores under it is to check your chunk boundaries and head to the south east corner. After digging straight down you will find the ores (I've tested on a few different worlds with the same result time after time)

## What should happen:
The ores should be randomly generated around the chunk which indicates the ores under it as opposed to always having atleast one ore in the south east corner.

**Comment by oitsjustjose** [comment]
Sure, I can do this really easily. Right now I add 8 to the gen's X and Z, but if I add 8, -8, and all permutations thereof, it'd be more randomized.

**Comment by Ravin890** [comment]
That would make it better compared to always knowing exactly where the ores will be.

**Comment by oitsjustjose** [comment]
I had to revert this commit; it was causing even worse cascading chunk lag than ever before. I wish I could just *not* do any of the +8 stuff and let it go, but *that* causes cascading chunk lag too :|

I can disable this notification myself (in case the user doesn't disable it themselves...) but then that could mask other bigger problems from my or other mods....
