### ISSUE TITLE
Can't get prospector's pick to work

### ISSUE THREAD

**Issue by brisingraerowing** [oitsjustjose/Geolosys#97]
## Versions:

- Minecraft Forge: 2654
- Geolosys: 1.8.10c
- JourneyMap (optional):
- ImmersiveEngineering (optional):

## What happens:
I find some samples on the surface and use the prospector's pick, and get back 'No deposits found' as the result.

## What should happen:
It finds a deposit.

## Additional Comments:
I verified that there was a deposit by removing stone around where it should be. I also tried the pick in the three chunks touching the corner the deposit was in, with the same results.

**Comment by oitsjustjose** [comment]
It works by right clicking when you’re ***close*** to a deposit. Samples will tell you where the deposit is, why would it tell you too?

The range is configurable. Default is a 5x5x5 In the direction you’re looking.

**Comment by brisingraerowing** [comment]
Ah, OK. This was my first time using the mod, so I wasn't sure.

**Comment by darthvader45** [comment]
Huh, I set it to the max of 255, right-clicked it in a chunk that had a ton of coal samples, and still gave "no deposits found."  Is there just no deposit there?

**Comment by oitsjustjose** [comment]
It should be, check the corners of the chunk.

**Comment by darthvader45** [comment]
Alrighty, I'll check.

Edit: Nothing.  Checked all corners of the chunk I found the samples in.  Will screenshot the chunk, with samples circled.  Any idea why it isn't working?  Also, what are the y level ranges in the manual for?  Samples or deposits?  Finally, why are comments not available on the CurseForge page?

One more thing, I'm using 1.8.10c.  Maybe it's the version.  If deleting the config doesn't make it work, then I'll go back a version and see if that works.  Might just be that version.

![no deposit chunk](https://user-images.githubusercontent.com/2816420/39019885-daa69b94-43f8-11e8-9bbf-6859f1c5656b.png)

**Comment by darthvader45** [comment]
Okay, happened with a chunk populated by quartz samples.  Seems perhaps the vein generation broke in 1.8.10c.  Might need to go back a version to see if it is fixed.  If so, might need to fix this.

Edit:  Last working version where I found ore deposits where samples were found was 1.8.8c.  Seems deposit gen broke somewhere between 1.8.8c and 1.8.10c.  Might want to figure out what went wrong.

Also, found some server log stuff that happened after I enabled that server log printing thing.  Something about cascading worldgen lag.  Might want to check that.

[11:05:41] [Server thread/WARN] [FML]: Geolosys loaded a new chunk [-27, 24] in dimension 0 (overworld) while populating chunk [-27, 25], causing cascading worldgen lag.
[11:05:41] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[11:05:41] [Server thread/WARN] [FML]: Geolosys loaded a new chunk [-27, 23] in dimension 0 (overworld) while populating chunk [-27, 25], causing cascading worldgen lag.
[11:05:41] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
