### ISSUE TITLE
IndexOutOfBoundsException in BlockOreVanilla.getDrops

### ISSUE THREAD

**Issue by arlyon** [oitsjustjose/Geolosys#98]
## Versions:

- Minecraft Forge: 14.23.1.2577
- Geolosys: 1.8.10c

## What happens:

I've been working on a mod that breaks blocks and seem to be running into a `IndexOutOfBounds` on this line when calling `BlockOreVanilla.getDrops`: 
https://github.com/oitsjustjose/Geolosys/blob/b66f4d9a741571245c2cd9ccaab2d9c280f1f01d/src/main/java/com/oitsjustjose/geolosys/blocks/BlockOreVanilla.java#L139

Problem arises when breaking a coal block. Looks like despite having sulfur enabled, `OreDictionary.getOres("dustSulfur")` returns an empty list which is why get(0) fails. Strangely `OreDictionary.doesOreNameExist("dustSulfur")` returns true even if it isn't in the OreDict.

As it says in the code, this happens only around 1 in every 50 calls.

**Comment by oitsjustjose** [comment]
Fixed! Thanks :)
