### ISSUE TITLE
Age 3 Windmill / Kinetic Dynamo Advancement missing the word power in description

### ISSUE THREAD

**Issue by n3twoik** [oitsjustjose/Geolosys#99]
Sorry, wrong mod, didn't even realize it wasn't for sevtech. Not sure how I got here. Thanks for Geolosys, it's a great mod.

**Comment by oitsjustjose** [comment]
A. This is just a nit picky issue, you can easily figure out what to do without that single word

B. I’m not the developer of this pack, or any modpack. I’m the developer of a single mod in the pack, and have nothing to do with it. 

C. You didn’t even read the thing in my template that says to delete lines if you read it...


Next time, take your time please (and more importantly ***post your issue in the right repository***.
